kqed/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <description>This is the URL for the logo. This field is automatically populated by the image upload.</description>
        <inlineHelpText>This is the URL for the logo. This field is automatically populated by the image upload.</inlineHelpText>
        <label>Logo Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <label>Organization</label>
    </recordTypes>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account additional locations</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Telephone Number</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>Zip Code</description>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State or Province</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street Address</description>
        <label>Street</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Member_Benefit__c.object
<CustomObject>
    <description>Member Discount Partners offer discounts to the members, you can view which Organizations offer discounts by searching on an Organization name.</description>
    <fields>
        <fullName>Benefit_Link__c</fullName>
        <description>This can be a link to the Business Member Partner page or a link to a benefit page.</description>
        <label>Benefit Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Business_Member_Partner__c</fullName>
        <description>Business Member Partner associated with offer benefit</description>
        <inlineHelpText>Business Member Partner associated with offer benefit</inlineHelpText>
        <label>Business Member Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category&apos;s associated with member benefit</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Up-to-the-minute Additions</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Education &amp; Family Fun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Drink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Performances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museums</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Blank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abbot Kinney Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure, Recreation &amp; Attractions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts &amp; Crafts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstores / Magazines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s Corner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classes &amp; Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concerts, Clubs &amp; Performing Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion, Clothing &amp; Beauty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Foods &amp; Gourmet Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furnishings &amp; Decor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts, Galleries &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Street Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana Avenue Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music Stores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Care &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Coast Plaza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spas &amp; Salons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theatre &amp; Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Featured__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Member Benefit featured?</description>
        <label>Featured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <description>This is the URL for the logo. This field is automatically populated by the image upload.</description>
        <inlineHelpText>This is the URL for the logo. This field is automatically populated by the image upload.</inlineHelpText>
        <label>Logo Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Top_Two_Featured__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Top Two Featured</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Discount Organization</label>
    <nameField>
        <label>Member Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Discount Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Member_benefit_Location__c.object
<CustomObject>
    <description>Junction Table for relating Member Benefits to Location</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Member_Benefit_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Benefit__c</fullName>
        <label>Member Benefit</label>
        <referenceTo>Member_Benefit__c</referenceTo>
        <relationshipName>Member_Benefit_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Partner Location</label>
    <nameField>
        <label>Member Discount Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Partner Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/TestMemberBenefitController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestMemberBenefitController {

    static testMethod void initMemberBenefitController() {
        
        Account bmp = new Account(
           Name = 'Whiskeys Smokehouse', 
           Logo_Url__c = ''
        );
        insert bmp;
        
        Location__c loc = new Location__c(
           Name = 'Boylston St', 
           Account__c = bmp.id, 
           Street__c = '885 Boylston Street', 
           City__c = 'Boston', 
           State__c = 'MA', 
           PostalCode__c = '02116', 
           Phone__c = '(617) 262-5551', 
           Latitude__c = 42.348442,
           Longitude__c = -71.083608
        );
        insert loc;
        
        Member_Benefit__c mb = new Member_Benefit__c(
           Name = 'Test', 
           Offer__c = 'Get 15 cent wings at Whiskeys Smokehouse, Boylston Street, Sunday to Thursday 3pm to 2am with a purchase of an alcholic beverage.',  
           Category__c = 'Food & Drink', 
           Benefit_Link__c = 'http://www.whiskeysmokehouseboston.com', 
           Business_Member_Partner__c =  bmp.id
        );
        insert mb;
        
        Member_Benefit__c mbf = new Member_Benefit__c(
           Name = 'Test', 
           Offer__c = 'Get $1 Pizza at Whiskeys Smokehouse, Boylston Street, Sunday to Thursday 3pm to 2am with a purchase of an alcholic beverage.',  
           Category__c = 'Food & Drink', 
           Benefit_Link__c = 'http://www.whiskeysmokehouseboston.com', 
           Business_Member_Partner__c =  bmp.id, 
           featured__c = true, 
           Top_Two_Featured__c = true
        );
        
        insert mbf;
        
        Member_benefit_Location__c mbl1 = new Member_benefit_Location__c(
           Name = '15 cent wings at Boylston St', 
           Location__c = loc.id, 
           Member_Benefit__c = mb.id
        ); 
        insert mbl1;
        
        Member_benefit_Location__c mbl2 = new Member_benefit_Location__c(
           Name = '$1 Pizza at Boylston St', 
           Location__c = loc.id, 
           Member_Benefit__c = mb.id
        ); 
        insert mbl2;
        
        MemberBenefitController mbc = new MemberBenefitController();
        mbc.isTest = true;
        
        // All Member benefits
        mbc.showMemberBenefits();
        System.assertEquals(mbc.memberBenefitMap.get(mb.Id).Id, mb.Id);
        System.assertEquals(mbc.memberBenefitMap.get(mbf.Id).Id, mbf.Id);
        
        // Only whiskeys member benefits
        PageReference mbPage = Page.MemberBenefits;
        mbPage.getParameters().put('searchTerm', 'Whiskeys Smokehouse');
        Test.setCurrentPageReference(mbPage);
        mbc.showMemberBenefits();
        System.assertEquals(mbc.memberBenefitMap.get(mb.Id).Id, mb.Id);
        System.assertEquals(mbc.memberBenefitMap.get(mbf.Id).Id, mbf.Id);
        
        // searching member benefits, search term is set above
        mbc.searchMemberBenefits();
        System.assertEquals(mbc.memberBenefitMap.get(mb.Id).Id, mb.Id);
        System.assertEquals(mbc.memberBenefitMap.get(mbf.Id).Id, mbf.Id);
        
        // wings and category = food & drink
        mbc.getCategories();
        mbc.category = 'Food & Drink';
        mbc.searchMemberBenefits();
        System.assertEquals(mbc.memberBenefitMap.get(mb.Id).Id, mb.Id);
        System.assertEquals(mbc.memberBenefitMap.get(mbf.Id).Id, mbf.Id);
        
        // member benefit detail for MB
        PageReference mbdPage = Page.MemberBenefitDetail;
        mbdPage.getParameters().put('memberBenefitId', mb.Id);
        Test.setCurrentPageReference(mbdPage);
        //mbc.memberBenefitId = mb.Id;
        mbc.showMemberBenefit();
        System.assertEquals(mbc.memberBenefitWrapper.memberBenefit.Id, mb.Id);
        System.assertNotEquals(mbc.memberBenefitWrapper.memberBenefit.Id, mbf.Id);
        
        // printing MB
        PageReference ppage1 = mbc.printDetail();
        System.assert(ppage1.getParameters().get('idsToPrint').indexOf(mb.Id) >= 0);
        System.assert(ppage1.getParameters().get('idsToPrint').indexOf(mbf.Id) == -1);
        
        // selective printing member benefits (printing all pages now)
        for(MemberBenefitWrapper mbw : mbc.memberBenefitWrappers) {
            mbw.checked = true;
        }
        PageReference ppage2 = mbc.printDetails();
        ppage2.getParameters().put('idsToPrint', '-'+mb.Id+'-');
        //System.assert(ppage2.getParameters().get('idsToPrint').indexOf(mb.Id) >= 0);
        //System.assert(ppage2.getParameters().get('idsToPrint').indexOf(mbf.Id) >= 0);
        
        
        // selective printing featured benefits
        for(MemberBenefitWrapper mbw : mbc.topTwofeaturedMemberBenefitWrappers) {
            if(mbw.memberBenefit.Id == mbf.Id) {
                mbw.checked = true;
            }
        }
        //PageReference ppage3 = mbc.printFeaturedDetails();
        //System.assert(ppage3.getParameters().get('idsToPrint').indexOf(mb.Id) == -1);
        //System.assert(ppage3.getParameters().get('idsToPrint').indexOf(mbf.Id) >= 0);
        
        
        // printing all benefits
        Test.setCurrentPageReference(ppage2);
        mbc.print();
        MemberBenefitWrapper mbToPrint = null;
        MemberBenefitWrapper mbfToPrint = null;
        for(MemberBenefitWrapper mbw : mbc.memberBenefitsToPrint) {
            if(mbw.memberBenefit.Id == mb.Id) {
                mbToPrint = mbw;
            }
            if(mbw.memberBenefit.Id == mbf.Id) {
                mbfToPrint = mbw;
            }
        }
        if(mbToPrint == null) mbToPrint = new MemberBenefitWrapper(new Member_Benefit__c(),new  List<Member_benefit_Location__c>());
        if(mbfToPrint == null) mbfToPrint = new MemberBenefitWrapper(new Member_Benefit__c(),new  List<Member_benefit_Location__c>());
        
        System.assertEquals(mbToPrint.memberBenefit.Id, mb.Id);
        //System.assertEquals(mbfToPrint.memberBenefit.Id, mbf.Id);
        
        MemberBenefitWs.isTest = true;
        MemberBenefitWs.MemberBenefitWs_Result result = MemberBenefitWs.getMemberBenfits();
        //System.assert(result.status=='Success');
        //XMLDom dom = new XMLDom(result.xml);
        //XMLDom.Element root = dom.root;
        //System.assert(root.nodeName == 'underwriters');           
    }   
}