kqed/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <label>Organization</label>
    </recordTypes>
</CustomObject>

kqed/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>People__c</fullName>
        <label>People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Rel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reciprocal_Relationship__c</fullName>
        <label>Reciprocal Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Acquaintance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Aunt/Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (former)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To_People__c</fullName>
        <label>Related To People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related To People)</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Primary Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Acquaintance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Aunt/Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a duplicate account!</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (current)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strength__c</fullName>
        <label>Strength</label>
        <picklist>
            <picklistValues>
                <fullName>Undefined</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Strong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weak</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isReciprocal__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If you check this box upon entering that a husband is related to a wife the reciprocal relationship will show on the wife (this is on the contact level only)</inlineHelpText>
        <label>Is Reciprocal</label>
        <type>Checkbox</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/TestRelationshipTriggers.cls
@isTest
private class TestRelationshipTriggers {
    // Test method for RelationshipAfterUpdate Trigger
    public static testMethod void testRelationshipAfterUpdateTrigger1(){
    
        // Inserting an Organization record
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
        
        // Create a relationship between the above two contacts
        Relationships__c relation1 = new Relationships__c();
        relation1.People__c = con1.Id;
        relation1.Related_To_People__c = con2.Id;
        relation1.Primary_Rel__c = true;
        relation1.Strength__c = 'Strong';
        relation1.Type__c = 'People';
        relation1.Relationship__c = 'Advisor';
        relation1.Reciprocal_Relationship__c = 'Advisee';
        insert relation1;
        
        Relationships__c relation2 = new Relationships__c();
        relation2.People__c = con2.Id;
        relation2.Related_To_People__c = con2.Id;
        relation2.Primary_Rel__c = true;
        relation2.Strength__c = 'Strong';
        relation2.Type__c = 'People';
        relation2.isReciprocal__c = true;
        relation2.Relationship__c = 'Advisee';
        relation2.Reciprocal_Relationship__c = 'Advisor';
        relation2.Parent__c = relation1.Id;
        insert relation2;
        
        Test.startTest();
        relation1.Strength__c = 'Moderate';
        relation1.Relationship__c = 'Board Member';
        update relation1;
        Test.stopTest();
             
    
    }    
    
    
    public static testMethod void testRelationshipAfterUpdateTrigger2(){
    
        // Inserting an Organization record
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
        
        // Create a relationship between the above two contacts
        Relationships__c relation1 = new Relationships__c();
        relation1.People__c = con1.Id;
        relation1.Related_To_People__c = con2.Id;
        relation1.Primary_Rel__c = true;
        relation1.Strength__c = 'Strong';
        relation1.Type__c = 'People';
        relation1.Relationship__c = 'Advisor';
        relation1.Reciprocal_Relationship__c = 'Advisee';
        insert relation1;
        
        Relationships__c relation2 = new Relationships__c();
        relation2.People__c = con2.Id;
        relation2.Related_To_People__c = con2.Id;
        relation2.Primary_Rel__c = true;
        relation2.Strength__c = 'Strong';
        relation2.Type__c = 'People';
        relation2.isReciprocal__c = true;
        relation2.Relationship__c = 'Advisee';
        relation2.Reciprocal_Relationship__c = 'Advisor';
        relation2.Parent__c = relation1.Id;
        insert relation2;
    
        
        Test.startTest();
        relation2.Strength__c = 'Strong';
        update relation2;
        Test.stopTest();        
    
    }    
    // Test method for RelationshipAfterDelete Trigger    
    public static testMethod void testRelationshipAfterDeleteTrigger(){
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
        
        // Create a relationship between the above two contacts
        Relationships__c relation1 = new Relationships__c();
        relation1.People__c = con1.Id;
        relation1.Related_To_People__c = con2.Id;
        relation1.Primary_Rel__c = true;
        relation1.Strength__c = 'Strong';
        relation1.Type__c = 'People';
        relation1.Relationship__c = 'Advisor';
        relation1.Reciprocal_Relationship__c = 'Advisee';
        insert relation1;
        
        Relationships__c relation2 = new Relationships__c();
        relation2.People__c = con2.Id;
        relation2.Related_To_People__c = con2.Id;
        relation2.Primary_Rel__c = true;
        relation2.Strength__c = 'Strong';
        relation2.Type__c = 'People';
        relation2.isReciprocal__c = true;
        relation2.Relationship__c = 'Advisee';
        relation2.Reciprocal_Relationship__c = 'Advisor';
        relation2.Parent__c = relation1.Id;
        insert relation2;   
        
        delete relation1;    
      
    }
}