kqed/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_Category__c</fullName>
        <label>Industry Category</label>
        <picklist>
            <controllingField>Industry</controllingField>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agencies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antiques/Collectibles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art/Galleries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bar/Recreational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cafe/Eaterie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carribean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering/Event Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Childcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children/Maternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College/University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Classes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Unions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culinary/Kitchen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Culinary Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultural Institutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink/Water/Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics/Computers/Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_ID__c</fullName>
        <description>Created for excuting FringeBenefitsController ...Earlier Field was Missing</description>
        <label>Location ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Telephone Number</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>Zip Code</description>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State or Province</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street Address</description>
        <label>Street</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Member_Benefit__c.object
<CustomObject>
    <description>Member Discount Partners offer discounts to the members, you can view which Organizations offer discounts by searching on an Organization name.</description>
    <fields>
        <fullName>Benefit_Link__c</fullName>
        <description>This can be a link to the Business Member Partner page or a link to a benefit page.</description>
        <label>Benefit Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Business_Member_Partner__c</fullName>
        <description>Business Member Partner associated with offer benefit</description>
        <inlineHelpText>Business Member Partner associated with offer benefit</inlineHelpText>
        <label>Business Member Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category&apos;s associated with member benefit</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Up-to-the-minute Additions</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Education &amp; Family Fun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Drink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Performances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museums</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Blank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abbot Kinney Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure, Recreation &amp; Attractions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts &amp; Crafts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstores / Magazines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s Corner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classes &amp; Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concerts, Clubs &amp; Performing Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion, Clothing &amp; Beauty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Foods &amp; Gourmet Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furnishings &amp; Decor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts, Galleries &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Street Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana Avenue Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music Stores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Care &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Coast Plaza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spas &amp; Salons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theatre &amp; Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Ending date of member benefit</description>
        <inlineHelpText>Ending date of member benefit</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <description>Earlier not exist ...</description>
        <label>Item ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Copy__c</fullName>
        <label>Marketing Copy</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting date of member benefit</description>
        <inlineHelpText>Starting date of member benefit</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Member Discount Organization</label>
    <nameField>
        <label>Member Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Discount Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Member_benefit_Location__c.object
<CustomObject>
    <description>Junction Table for relating Member Benefits to Location</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Member_Benefit_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Benefit__c</fullName>
        <label>Member Benefit</label>
        <referenceTo>Member_Benefit__c</referenceTo>
        <relationshipName>Member_Benefit_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Partner Location</label>
    <nameField>
        <label>Member Discount Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Partner Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/FringeBenefitsController.cls
public with sharing class FringeBenefitsController {

    public String benefits {get; private set;}
    public FringeBenefitsController() {
        String timeInMillis = ApexPages.currentPage().getParameters().get('timestamp');
        
        Date validDate;
        boolean flag;
        if(timeInMillis != null && timeInMillis != ''){
            try {
                validDate = DateTime.newInstance(Long.valueOf(timeInMillis)).date();
               // validDate = DateTime.newInstance(Integer.valueOf(year),Integer.valueOf(month),Integer.valueOf(day)).date();
                system.debug('validDate is '+validDate );
                flag = true;
            } catch(Exception ex) {
                validDate = System.today();
            }
        } else {
            validDate = System.today();
        }
        List<Member_Benefit_Location__c> benefitLocations = new List<Member_Benefit_Location__c>();
        system.debug('validDate is '+validDate);
        if(flag == true){
        benefitLocations =
            [select Location__r.Location_ID__c, Location__r.Name, Location__r.Street__c, Location__r.City__c,Member_Benefit__r.Start_Date__c,    
                Location__r.State__c, Location__r.PostalCode__c, Location__r.Phone__c, 
                Member_Benefit__r.Item_ID__c, Member_Benefit__r.Name, Member_Benefit__r.Offer__c,  
                Member_Benefit__r.Marketing_Copy__c, Member_Benefit__r.Category__c, Member_Benefit__r.Benefit_Link__c,
                Member_Benefit__r.Business_Member_Partner__r.Name, 
                Member_Benefit__r.Business_Member_Partner__r.Industry,
                Member_Benefit__r.Business_Member_Partner__r.Industry_Category__c
                from Member_benefit_Location__c where Member_Benefit__r.LastModifiedDate >= :validDate ];
                
               // Member_Benefit__r.Start_Date__c <= :validDate 
               // and (Member_Benefit__r.End_Date__c = null or Member_Benefit__r.End_Date__c >= :validDate)];
        }
        else {
        benefitLocations = 
            [select Location__r.Location_ID__c, Location__r.Name, Location__r.Street__c, Location__r.City__c,Member_Benefit__r.Start_Date__c,    
                Location__r.State__c, Location__r.PostalCode__c, Location__r.Phone__c, 
                Member_Benefit__r.Item_ID__c, Member_Benefit__r.Name, Member_Benefit__r.Offer__c,  
                Member_Benefit__r.Marketing_Copy__c, Member_Benefit__r.Category__c, Member_Benefit__r.Benefit_Link__c,
                Member_Benefit__r.Business_Member_Partner__r.Name, 
                Member_Benefit__r.Business_Member_Partner__r.Industry,
                Member_Benefit__r.Business_Member_Partner__r.Industry_Category__c
                from Member_benefit_Location__c];
        }
        System.debug('benefitLocations: ' + benefitLocations);
        //benefits = '{"benefits": [';
        benefits = '';
        if ( benefitLocations.size() > 0 ) {
            for ( Member_Benefit_Location__c bl : benefitLocations ) {
            system.debug('start date '+bl.Member_Benefit__r.Start_Date__c );
            System.debug('ItemID: ' + bl.Member_Benefit__r.Item_ID__c != null ? bl.Member_Benefit__r.Item_ID__c : bl.Member_Benefit__c);
            System.debug('LocationID: ' + formatJSONString(bl.Location__r.Location_ID__c != null ? bl.Location__r.Location_ID__c: bl.Location__r.Name));
                benefits += 
                    '\n    {"ItemID": "' + (bl.Member_Benefit__r.Item_ID__c != null ? bl.Member_Benefit__r.Item_ID__c : bl.Member_Benefit__c) + '", ' +
                    '"LocationID": "' + formatJSONString(bl.Location__r.Location_ID__c != null ? bl.Location__r.Location_ID__c: bl.Location__c) + '", ' +
                    '"Name_Display": "' + formatJSONString(bl.Member_Benefit__r.Name) + '", ' +
                    '"Name_Sort": "' + formatJSONString(bl.Member_Benefit__r.Business_Member_Partner__r.Name) + '", ' +
                    '"Address": "' + formatJSONString(bl.Location__r.Street__c) + '", ' +
                    '"City": "' + formatJSONString(bl.Location__r.City__c) + '", ' +
                    '"Country": "' + formatJSONString(bl.Location__r.State__c) + '", ' +
                    '"Zip": "' + formatJSONString(bl.Location__r.PostalCode__c) + '", ' +
                    '"Phone": "' + formatJSONString(bl.Location__r.Phone__c) + '", ' +
                    '"Website_URL": "' + formatJSONString(bl.Member_Benefit__r.Benefit_Link__c) + '", ' +
                    '"Description": "' + formatJSONString(bl.Member_Benefit__r.Marketing_Copy__c) + '", ' +
                    '"Discount_Info": "' + formatJSONString(bl.Member_Benefit__r.Offer__c) + '", ';

                if (bl.Member_Benefit__r.Business_Member_Partner__r.Industry != null && 
                    bl.Member_Benefit__r.Business_Member_Partner__r.Industry.startsWith('Food')) {
                    benefits += 
                        '"Cuisine": "' + formatJSONString(bl.Member_Benefit__r.Business_Member_Partner__r.Industry_Category__c) + '", ';
                }

                String categories = '[';
                if ( bl.Member_Benefit__r.Category__c != null ) {
                    String[] cats = bl.Member_Benefit__r.Category__c.split(';');
                    for (String cat : cats) {
                        categories += '"' + cat + '", ';
                    }
                    categories = categories.substring(0, categories.length() - 2);
                }
                categories += ']';
                benefits += '"Categories": ' + formatJSONString(categories) + '}, ';
            }
            benefits = benefits.substring(0, benefits.length() - 2);
        }
        System.debug('benefits: ' + benefits);
        //benefits = ']';
    }
    private String formatJSONString(String value) {
        return value != null ? value.replaceAll('\n', '\\\\n') : '';
    }
}