kqed/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <inlineHelpText>By checking this box you activate the Member Discount Offer on the KCRW Web Site</inlineHelpText>
        <label>Active Offer on Website</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Code_Value__c</fullName>
        <label>Classification Code Value</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Classification</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>TA Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_tabname__c</fullName>
        <description>delete when you can untangle the visual force page</description>
        <label>Classification Tab Name X</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>TA Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <recordTypes>
        <fullName>appeal</fullName>
        <active>true</active>
        <description>Preference by Station regarding appeals</description>
        <label>Appeal Preferences</label>
    </recordTypes>
    <recordTypes>
        <fullName>benefit</fullName>
        <active>true</active>
        <description>Preference by Station regarding membership benefits &amp; premiums</description>
        <label>Benefit Preferences</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Classification_Code__c.object
<CustomObject>
    <description>This values is used to match the PB5 input on a new contact giving a donation to match their preferences.  Do not delete.</description>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>code_description__c</fullName>
        <label>Classification Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value_description__c</fullName>
        <label>Classification Value Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Classification Code/Value</label>
    <nameField>
        <label>Classification Code/Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Code/Value</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>comments__c</fullName>
        <description>Comments</description>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/Prospect_Research_Reports__c.object
<CustomObject>
    <description>Prospect Research Reports are utilized for profiling of members, prospective members and constituents by the Prospect Research Team.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prospect Research Report</label>
    <nameField>
        <label>PRR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Research Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/PRRWGBHBoards.cls
public class PRRWGBHBoards {
    public PRRWGBHBoards(ApexPages.StandardController controller) {
        PageLoad();
    }
    public PRRWGBHBoards() {
        PageLoad();
    }    
    public List<Classification__c> classifications {
        get {
             return this.getAllClassifications();
        }
        set;
    }
    public void PageLoad() {
        //id=ApexPages.CurrentPage().getParameters().get('id');
        List<Prospect_Research_Reports__c> lstPRR = new List<Prospect_Research_Reports__c>();
        
        lstPRR = [SELECT id, Contact__c FROM Prospect_Research_Reports__c WHERE ID=:ApexPages.CurrentPage().getParameters().get('id')];
        sObjectType='Contact';
        recordId=lstPRR[0].Contact__c;
        Delid='aaa';
        system.debug('------------------------------------->' + id);
    }
    public TabData[] tabs {get; set;}
    
    public class TabData {
        public String tabName {
            get {
                return (this.classifications != null && this.classifications.size() > 0 ? this.tabName + ' [' + this.classifications.size() + ']' : this.tabName);
            }
            set;
        }
        public List<Classification__c> classifications {get; set;}
        
        public TabData(String tabName, List<Classification__c> classifications) {
            this.tabName = tabName;
            this.classifications = classifications;
            System.debug('creating '+tabName+' tab with '+classifications.size()+' classifications.');
        }
    }
    
    public TabData dataTagging {get; set;}
    public TabData bbaScores {get; set;}
    public TabData email {get; set;}
    public TabData misc {get; set;}
    public TabData nationalProgramming {get; set;}
    public TabData benefit {get; set;}
    public TabData appeal {get; set;}
    public TabData discount {get; set;}
    public TabData clubs {get; set;}
    public TabData autoRenew {get; set;}
    public TabData membershipType {get; set;}
    public TabData mgProspects {get; set;}
    public TabData board {get; set;}
    public TabData committee {get; set;}
    
    
    public String Delid{get;set;} 
    public string id{get;set;}
    
    public String recordId {get; set;}
    public String sObjectType {get; set;}
    

    
    public Classification__c[] getAllClassifications() {
        List<Classification__c> classifications = null;
        
        if(sObjectType == 'Contact') {
            classifications = [Select c.start_date__c, c.end_date__c, c.comments__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Contact__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Contact__c = :recordId];
        }
        else if(sObjectType == 'Account') {
            classifications = [Select c.start_date__c, c.end_date__c, c.comments__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId];
        }
        else if(sObjectType == 'Household__c') {
            classifications = [Select c.start_date__c, c.end_date__c, c.comments__c, c.classification_value__c, c.classification_tabname__c, c.classification_code__c, c.active__c, c.Account__c, c.Classification_Code_Value__r.value_description__c, c.Classification_Code_Value__r.code_description__c, c.Classification_Code_Value__c From Classification__c c Where c.Account__c = :recordId];
        } 
        
        if(classifications != null) {// && classifications.size() > 0) {
            System.debug('found '+classifications.size()+' classifications');
            this.tabs = new TabData[] {
                this.createTab(classifications, 'Board', 'WGBH Boards'), 
                this.createTab(classifications, 'Committee')
            };
            System.debug('created '+this.tabs.size()+' tabs');
            
            Integer tabIndex = 0;
            board = this.tabs[tabIndex ++];
            committee = this.tabs[tabIndex ++];
        }
        else {
            System.debug('found no classifications');
        }
        
        return classifications;
    }
    
    public List<Classification__c> getClassifications(List<Classification__c> classifications, String tabName) {
        List<Classification__c> cList = new List<Classification__c>();
        for(Classification__c c : classifications) {
            if(c.classification_tabname__c == tabName) {
                cList.add(c);
            }
        }
        return cList;
    }
    
    public TabData createTab(List<Classification__c> classifications, String tabName) {
        System.debug('in ct 1');
        return this.createTab(classifications, tabName, null);
    }
    
    public TabData createTab(List<Classification__c> classifications, String tabName, String tabLabel) {
        System.debug('in ct 2');
        return new TabData(tabLabel == null ? tabName : tabLabel, this.getClassifications(classifications, tabName));
    }



    public PageReference Delmet() {
        System.debug('Deleteing classification: '+Delid);
        try {
            Classification__c c= [SELECT Id from Classification__c where id=:DelId];
            delete c;
        }
        catch(Exception e) {
            System.debug('Unable to delete classification: '+Delid+', ex: '+e);
        }
        pagereference pg = ApexPages.currentPage();
        return pg;
    }
    
}