kqed/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

kqed/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <inlineHelpText>This would be additional mailing information for delivery for ex. C/O or 3rd floor Suite 107</inlineHelpText>
        <label>Address Additional Line</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>The radio/tv station call letters that the campaign is representing.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>KCRW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KQED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>KQED+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Charge Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Charge_Card_Type__c</fullName>
        <label>Charge Card Type</label>
        <picklist>
            <controllingField>payment_method__c</controllingField>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VISA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Giving_Amount__c</fullName>
        <label>Giving Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Oppty_Related_Contact__c</fullName>
        <description>The contact associated to the opportunity/ask</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposal/Pledge</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Description__c</fullName>
        <label>Payment Method Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Refused_Reason__c</fullName>
        <label>Refused Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Cannot Afford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hung up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Commitment Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supports Other non-profits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WBUR 90.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t get premium/response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel 11 or Channel 36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unemployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refuses all telesales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moving out of area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>can&apos;t receive signal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supports Auction Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Add gift to Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave Already</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped from Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refused to give a Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>KQED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>KQED+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>installment_amount__c</fullName>
        <description>Installment Amount</description>
        <inlineHelpText>Installment Amount</inlineHelpText>
        <label>Installment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carte Blanche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diner&apos;s Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic Charge Card - No CC# Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Dated Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>schedule_start_date__c</fullName>
        <description>Schedule Start Date</description>
        <inlineHelpText>Schedule Start Date</inlineHelpText>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations</description>
        <label>Annual</label>
    </recordTypes>
</CustomObject>

kqed/src/classes/GivingEditController.cls
public class GivingEditController {
    
    Public Opportunity objGiving {get; set;}
    public Contact objContact {get; set;}
    public Account objHousehold {get; set;}    
    String Id;
    
    
    public GivingEditController (ApexPages.StandardController controller) {
        Id = ApexPages.CurrentPage().getParameters().get('id');
        objGiving = [Select AccountId,Oppty_Related_Contact__c,StageName, Refused_Reason__c 
           ,Schedule_Start_Date__c,Payment_Date__c,Payment_Method__c,payment_amount__c,RecordTypeId
           ,Payment_method_description__c,Charge_Card_Type__c    ,Giving_Amount__c,Station__c , installment_amount__c
            From Opportunity Where Id=:Id]; 
                        
            setContactDetail();
            setHouseholdDetail();
    }   
    
    public PageReference GivingSave()
    {

        GivingSaveMe();
        
        String retURL;
        retURL = ApexPages.CurrentPage().getParameters().get('Id');
        return RedirectPage('/'+retURL);

    }
    
    Private Boolean GivingSaveMe()
    {
        Update objGiving;
        Set<ID> setGivingIDs = new Set<ID>();
        if(objGiving.Id != null){
            setGivingIds.add(objGiving.Id);
            ProcessGivingSummary.UpdateSummary(setGivingIds,true);
        }
        return true;
    }
     void setContactDetail(){ 
       
        objContact = new Contact();
    
        if(objGiving.Oppty_Related_Contact__c != null){
            
            //Ketan Benegal - 05/16/2011 - added MailingCountry, MailingStreet, Fax to the following query for Sage Integration.
            objContact = [Select Id, Name, Salutation, FirstName, LastName, Email, MobilePhone,
            Birthdate, Phone, MailingCity, MailingState, MailingPostalCode, MailingCountry, MailingStreet, Fax,
            Preferred_Address__r.Street_2__c, Preferred_Address__r.Street_1__c, Preferred_Address__r.State__c, Preferred_Address__r.Postal_Code__c, Preferred_Address__r.Country__c, Preferred_Address__r.City__c
            From Contact 
            Where Id =: objGiving.Oppty_Related_Contact__c];
        }
       
    }
    void setHouseholdDetail(){
        objHousehold = new Account();
        if(objGiving.AccountId != null){
            objHousehold = [Select Id, Name, AccountNumber, Phone, AccountType__c
            From Account
            Where Id =: objGiving.AccountId];
        }
    }
    
    PageReference RedirectPage(String URL){   
              
        PageReference P = new PageReference(URL);
        P.SetRedirect(true);        
        return P;
    }
    
    Public PageReference ChoosePaymentMode(){
        return null;
    }
    
    Public List<CC_Alias__c> getExistingChargeCard(){
       
        List<CC_Alias__c> lstChargeCard = new List<CC_Alias__c>();
        
        lstChargeCard = [Select Id, Name, Card_Type__c, Expire_Date__c, Last_Four_Digits__c from CC_Alias__c where Account__c =: objGiving.AccountId and Contact__c =: objGiving.Oppty_Related_Contact__c];
        
        List<CC_Alias__c> lstReturn = new List<CC_Alias__c>();
        
        CC_Alias__c temp = new CC_Alias__c();
        //temp.Card_Type__c = 'New';
        lstReturn.add(temp);
        
        for(CC_Alias__c e: lstChargeCard) {
            lstReturn.add(e);
        }

        return lstReturn;
    }
    
    Public PageReference NewChargeCode(){
        if(GivingSaveMe()==true){
            PageReference P = New PageReference('/apex/SageHtml');
            P.SetRedirect(true);
            return P;            
        }
        else
            return null;
    }
    static testMethod void GivingEditController(){
           Account a = new Account(Name = 'Test');
        insert a;
        
        Campaign c = new Campaign();
        c.Name = 'Test';
        c.Channel_Technique__c = 'TELESALES';
        c.Sub_Channel__c = 'INBOUND';
        c.campaign_name__c = 'Annual';
        c.station__c = 'WGBH';
        c.response_mechanism__c = 'Mail';
        Insert c;
        
        Opportunity opp = New Opportunity();
        opp.AccountID = a.Id;
        opp.Name = 'Test';
        opp.gift_kind__c = 'One Payment';
        opp.CloseDate = system.Today().AddDays(15);
        opp.Gift_Date_Time__c = system.now();
        opp.StageName = 'Pledged';
        opp.CampaignID = c.Id;
        opp.campaign_name__c = 'Annual';
        opp.station__c = 'WGBH';
        RecordType rc = [select id from recordtype where developername = 'Annual'];
        opp.recordtypeid = rc.id;
        opp.Gift_Type__c = 'New';
        
        insert opp;
        
         ApexPages.currentPage().getParameters().put('id', opp.Id);
        SObject o = new Account();
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
             
        //EditGiving clsTest = new EditGiving(sc);
        GivingEditController clsTest = new GivingEditController(sc);
        clsTest.GivingSave();
        clsTest.GivingSaveMe();
        clsTest.setContactDetail();
        clsTest.setHouseholdDetail();
        clsTest.RedirectPage('https://cs3.salesforce.com/006/o');
        clsTest.ChoosePaymentMode();
        clsTest.getExistingChargeCard();
        clsTest.NewChargeCode();
        
    }
    
 }