kqed/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>alt_account_id__c</fullName>
        <label>Alt Account Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>alt_account_id__c</fullName>
        <description>Alt Account Id</description>
        <label>Alt Account Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>alt_transaction_id__c</fullName>
        <description>Convio Transaction ID</description>
        <externalId>true</externalId>
        <label>Convio Transaction ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_frequency__c</fullName>
        <label>Payment Frequency DELETE</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irregular Schedule</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>source__c</fullName>
        <label>TA Source Code</label>
        <length>14</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/classes/ConvioServiceTest.cls
@isTest
private class ConvioServiceTest {

    static testMethod void myConvioService() {
    	
    	Account acc = new Account(Name = 'Test', alt_account_id__c = '1');
    	insert acc;
    	
    	Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;
		
		Opportunity rd = 
							new Opportunity(
								alt_transaction_id__c = '1',
								//gift_date__c = ????????,
								source__c = 'INTERNET', 
								payment_frequency__c = '1',
								pledge_number__c = '80000000',
								Amount = 1,
								RecordTypeId = ConvioService.DONATION_REC_TYPE_ID,
								CloseDate = date.today(),
								StageName = 'Partial Close',
								AccountId = acc.Id,
								Name = acc.Name);
		insert rd;
		
        ConvioService cs = new ConvioService();
        System.debug(cs.dummyCont);
        cs.dummyCont.Birthdate = Date.today();
        cs.testRunConvio();
        
        ConvioService.processTodaysConvioProductOrdersAsynch();
        ConvioService.processTodaysConvioDonationsAsynch();
    }
}