kqed/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <inlineHelpText>This would be additional mailing information for delivery for ex. C/O or 3rd floor Suite 107</inlineHelpText>
        <label>Address Additional Line</label>
        <type>TextArea</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>Flag_Review_Reason__c</fullName>
        <label>Flag Review Reason</label>
        <picklist>
            <picklistValues>
                <fullName>MORE THAN 1 MATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC PLEDGE ID or PLEDGE NUMBER EXIST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS AMT equal to PAYMENT AMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT DATE ON PLEDGE WITH PREMIUMS &lt; 1 YEAR FROM CURRENT DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; SUM OF PRODUCTS MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; PRODUCT MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT TYPE IS NULL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_for_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag for Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_ADDRESS_TYPE__c</fullName>
        <description>Address type: (H)ome, (W)ork, (S)easonal, (V)acation, (O)ld</description>
        <label>PB5_ADDRESS_TYPE</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_CITY__c</fullName>
        <description>City of preferred address. Maps to UL_ADDRESSES.CITY</description>
        <label>PB5_CITY</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_COUNTRY__c</fullName>
        <description>country of preferred address: maps to: UL_ADDRESSES.COUNTRY</description>
        <label>PB5_COUNTRY</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_EMAIL_ADDRESS_1__c</fullName>
        <description>PREFERRED EMAIL ADDRESS. MAPS TO: UL_EMAILS.EMAIL_ADDRESS</description>
        <label>PB5_EMAIL_ADDRESS_1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PB5_EMAIL_ADDRESS_2__c</fullName>
        <description>The email address of the second name on the account</description>
        <label>PB5_EMAIL_ADDRESS_2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PB5_EXTRA_LINE_1__c</fullName>
        <description>from preferred address. Maps To: UL_ADDRESSES.EXTRA_LINE_1</description>
        <label>PB5_EXTRA_LINE_1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME_2__c</fullName>
        <description>The first name of the second named account in the file</description>
        <label>PB5_FIRST_NAME_2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME__c</fullName>
        <description>First name of household or contact or organziation. Maps to: UL_NAMES.FIRST_NAME</description>
        <label>PB5_FIRST_NAME</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_IS_NEW__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this a new record for Salesforce.</description>
        <label>PB5_IS_NEW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_IS_PROCESSED__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has this record been processed successfully?</description>
        <label>PB5_IS_PROCESSED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME_2__c</fullName>
        <description>The last name of the second person in the file</description>
        <label>PB5_LAST_NAME_2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME__c</fullName>
        <description>Last name of household, contact, organizaiton. Maps to: UL_NAMES.LAST_NAME</description>
        <label>PB5_LAST_NAME</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_MIDDLE_NAME__c</fullName>
        <description>Middle name of household, contact, organizaiton. Maps to: UL_NAMES.MIDDLE_NAME</description>
        <label>PB5_MIDDLE_NAME</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_NO_PHONE_PREFERRED__c</fullName>
        <label>PB5_NO_PHONE_PREFERRED</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_CITY__c</fullName>
        <label>PB5_SHIP_TO_CITY</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_EXTRA_LINE_1__c</fullName>
        <label>PB5_SHIP_TO_EXTRA_LINE_1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STATE__c</fullName>
        <label>PB5_SHIP_TO_STATE</label>
        <picklist>
            <picklistValues>
                <fullName>GET PICK LIST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STREET_1__c</fullName>
        <label>PB5_SHIP_TO_STREET_1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_ZIP_CODE__c</fullName>
        <label>PB5_SHIP_TO_ZIP_CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_STATE__c</fullName>
        <description>State of preferred Address</description>
        <label>PB5_STATE</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_STREET_1__c</fullName>
        <description>Name of street in preferred address. Maps to: UL_ADDRESSES.STEET_NAME</description>
        <label>PB5_STREET_1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_Stage__c</fullName>
        <label>PB5 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_ZIP_CODE__c</fullName>
        <description>zip code of preferred address. Maps to: UL_ADDRESSES.ZIP_CODE</description>
        <label>PB5_ZIP_CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Duplicate_ID__c</fullName>
        <label>SF Duplicate ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/UploadRecordMatchingContact.cls
public class UploadRecordMatchingContact{
    public static void ProcessContact(WGBH_PB5_UPLOAD__c PB5, String HouseholdId){
        List<sObject> lstTarget;
        UploadRecordMatchingProcess__c csMatchingFields = UploadRecordMatchingProcess__c.getOrgDefaults();
        system.debug('########################' + csMatchingFields);
        String MatchingCriteria;
        //if(csMatchingFields != null)
        //    MatchingCriteria = csMatchingFields.Matching_Criteria__c;
        //else
        //    MatchingCriteria = 'LastName=PB5_LAST_NAME__c,Email=PB5_EMAIL_ADDRESS_1__c;FirstName=PB5_FIRST_NAME__c,LastName=PB5_LAST_NAME__c,MailingStreet=PB5_SHIP_TO_STREET_1__c,MailingCity=PB5_SHIP_TO_CITY__c,MailingState=PB5_SHIP_TO_STATE__c,MailingPostalCode=PB5_SHIP_TO_ZIP_CODE__c';
        //lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        //ProcessContact(PB5, lstTarget, '1');
        /*
        if(csMatchingFields != null)
            MatchingCriteria = csMatchingFields.Contact_Matching_Criteria_2__c;
        else
            MatchingCriteria = 'LastName=PB5_LAST_NAME_2__c,Email=PB5_EMAIL_ADDRESS_2__c;FirstName=PB5_FIRST_NAME_2__c,LastName=PB5_LAST_NAME_2__c,MailingStreet=PB5_STREET_1__c,MailingCity=PB5_CITY__c,MailingState=PB5_STATE__c,MailingPostalCode=PB5_ZIP_CODE__c';
        */  
        MatchingCriteria = 'LastName=PB5_LAST_NAME__c,Email=PB5_EMAIL_ADDRESS_1__c;LastName=PB5_LAST_NAME_2__c,Email=PB5_EMAIL_ADDRESS_2__c;FirstName=PB5_FIRST_NAME__c,LastName=PB5_LAST_NAME__c,MailingStreet=PB5_STREET_1__c,MailingCity=PB5_CITY__c,MailingState=PB5_STATE__c,MailingPostalCode=PB5_ZIP_CODE__c;FirstName=PB5_FIRST_NAME_2__c,LastName=PB5_LAST_NAME_2__c,MailingStreet=PB5_STREET_1__c,MailingCity=PB5_CITY__c,MailingState=PB5_STATE__c,MailingPostalCode=PB5_ZIP_CODE__c';            
        system.debug('################ MatchingCriteria ' + MatchingCriteria);
        lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        ProcessContact(PB5, lstTarget,HouseholdId, '2');
    }
    public static void ProcessContact(WGBH_PB5_UPLOAD__c PB5,List<sObject> lstTarget, String HouseholdId, String flag){
        //List<sObject> lstTarget = getMatchingRows(PB5,'Contact');
        if(lstTarget.size()==0){//Contact Info not exist -> Create new contact
            //insert Contact
            if(InsertContact(PB5, flag, HouseholdId)==true){
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'B';
                PB5.PB5_IS_PROCESSED__c = true;
                PB5.PB5_IS_NEW__c = false;
            }
            else{
                PB5.Flag_for_Review__c = true;
                PB5.PB5_Stage__c = 'A';
                PB5.PB5_IS_PROCESSED__c = false;
                PB5.PB5_IS_NEW__c = true;
            }
        }
        else if(lstTarget.size()==1){//Contact Info Exists -> Apend data to existing contact
            //update Contact
            if(UpdateContact((Contact) lstTarget[0], PB5, flag,HouseholdId)==true){
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'B';
                PB5.PB5_IS_PROCESSED__c = true;
                PB5.PB5_IS_NEW__c = false;
            }
            else{
                PB5.Flag_for_Review__c = true;
                PB5.PB5_Stage__c = 'A';
                PB5.PB5_IS_PROCESSED__c = false;
                PB5.PB5_IS_NEW__c = true;
            }
        }
        else if(lstTarget.size()>1){//Multiple Contact found
            //multiple matches found
            String duplicateId='';
            for(sObject t:lstTarget){
                if(duplicateId.length()==0)
                    duplicateId = String.valueOf(t.get('Id'));// + '#' + String.valueOf(t.get('name'));
                else
                    duplicateId += +', ' + String.valueOf(t.get('Id'));// + '#' + String.valueOf(t.get('name'));                        
            }
            //PB5.SF_Duplicate_ID__c = duplicateId;
            PB5.Flag_for_Review__c = true;
            PB5.PB5_IS_PROCESSED__c = false;
            PB5.PB5_IS_NEW__c = true;
            PB5.Flag_Review_Reason__c = 'MORE THAN 1 MATCH';
        }
        Update PB5;    
    }
    
    public static boolean InsertContact(WGBH_PB5_UPLOAD__c pb, String flag, String HouseholdId){
        boolean blnSuccess=false;
        Contact objContact = new Contact();
        objContact = mapContactField(pb, flag);
        try{
            system.debug('########## Contact to Insert : ' + objContact);
            objContact.AccountId = HouseholdId;
            insert objContact;
            if(objContact.Id != null && String.valueOf(objContact.Id).length()>0){
                blnSuccess = true;
                Address__c objAdd = new Address__c();
                objAdd.Address_Type__c = NVL(pb.PB5_ADDRESS_TYPE__c);
                objAdd.Street_1__c = getValues(pb.PB5_SHIP_TO_STREET_1__c, pb.PB5_STREET_1__c);
                objAdd.Street_2__c = getValues(pb.PB5_EXTRA_LINE_1__c, pb.PB5_SHIP_TO_EXTRA_LINE_1__c);
                objAdd.City__c = getValues(pb.PB5_CITY__c, pb.PB5_SHIP_TO_CITY__c);
                objAdd.State__c = getValues(pb.PB5_STATE__c, pb.PB5_SHIP_TO_STATE__c);
                objAdd.Postal_Code__c = getValues(pb.PB5_ZIP_CODE__c, pb.PB5_SHIP_TO_ZIP_CODE__c);
                objAdd.Country__c = NVL(pb.PB5_COUNTRY__c);    
                objAdd.Contact__c = objContact.Id;
                objAdd.Account_Household__c = HouseholdId;   
                Insert objAdd;      
                //processClassification(pb, objContact.Id, householdId);   
            }
            else{
                blnSuccess = false;
            }
            UploadRecordMatchingGiving.processGiving(pb, objContact.Id, householdId);
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    public static boolean UpdateContact(Contact objContact, WGBH_PB5_UPLOAD__c pb, String flag, string householdid){
        boolean blnSuccess=false;        
        //objContact = mapContactField(pb, flag);
        objContact.FirstName = getValues(pb.PB5_FIRST_NAME__c, pb.PB5_FIRST_NAME_2__c);
        objContact.LastName = getValues(pb.PB5_LAST_NAME__c, pb.PB5_LAST_NAME_2__c);
        //objContact.MiddleName = getValues(pb.PB5_MIDDLE_NAME__c, pb.PB5_MIDDLE_NAME__c);
        
        //objContact.DoNotCall = getValues(pb.PB5_NO_PHONE_PREFERRED__c, pb.PB5_NO_PHONE_PREFERRED__c);
        //objContact.WorkEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_2__c, pb.PB5_EMAIL_ADDRESS_2__c);
        objContact.Salutation = getValues(pb.PB5_SUFFIX__c, pb.PB5_SUFFIX_2__c);
        objContact.PreferredPhone__c = getValues(pb.PB5_TELEPHONE_TYPE_1__c, pb.PB5_TELEPHONE_TYPE_2__c);
        if(NVL(objContact.PreferredPhone__c) == 'H' || NVL(objContact.PreferredPhone__c) == 'Home'){
            objContact.HomePhone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        }
        if(NVL(objContact.PreferredPhone__c) == 'W' || NVL(objContact.PreferredPhone__c) == 'Work'){
            objContact.HomePhone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        }
        objContact.Preferred_Email__c = NVL(pb.PB5_EMAIL_TYPE_2__c);
        if(NVL(objContact.Preferred_Email__c) == 'Work'){
            objContact.WorkEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Home'){
            objContact.HomeEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Assistant'){
            objContact.Assistant_Email__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Default Email'){
            objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else{
            objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        objContact.Phone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        //objContact.OtherPhone = getValues(pb.PB5_TELEPHONE_NUMBER_2__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        objContact.MailingStreet = getValues(pb.PB5_SHIP_TO_STREET_1__c, pb.PB5_STREET_1__c);
        objContact.MailingCity = getValues(pb.PB5_SHIP_TO_CITY__c, pb.PB5_CITY__c);
        objContact.MailingState = getValues(pb.PB5_SHIP_TO_STATE__c, pb.PB5_STATE__c);
        objContact.MailingPostalCode = getValues(pb.PB5_SHIP_TO_ZIP_CODE__c, pb.PB5_ZIP_CODE__c);        
        try{
            update objContact;
            if(objContact.Id != null && String.valueOf(objContact.Id).length()>0){
                blnSuccess = true;
                if(objContact.Id != null && String.valueOf(objContact.Id).length()>0){
                    blnSuccess = true;
                    Address__c objAdd;
                    List<Address__c> lstAdd = [Select Id, Address_Type__c, Street_1__c, Street_2__c, City__c, State__c,
                    Postal_Code__c, Country__c, Contact__c, Account_Household__c From Address__c
                    Where Contact__c =: objContact.Id];
                    if(lstAdd != null && lstAdd.size()>0){
                        objAdd = lstAdd[0];
                    }else{
                         objAdd = new Address__c();
                    }
                    objAdd.Address_Type__c = NVL(pb.PB5_ADDRESS_TYPE__c);
                    objAdd.Street_1__c = getValues(pb.PB5_SHIP_TO_STREET_1__c, pb.PB5_STREET_1__c);
                    objAdd.Street_2__c = getValues(pb.PB5_EXTRA_LINE_1__c, pb.PB5_SHIP_TO_EXTRA_LINE_1__c);
                    objAdd.City__c = getValues(pb.PB5_CITY__c, pb.PB5_SHIP_TO_CITY__c);
                    objAdd.State__c = getValues(pb.PB5_STATE__c, pb.PB5_SHIP_TO_STATE__c);
                    objAdd.Postal_Code__c = getValues(pb.PB5_ZIP_CODE__c, pb.PB5_SHIP_TO_ZIP_CODE__c);
                    objAdd.Country__c = NVL(pb.PB5_COUNTRY__c);    
                    //objAdd.Account_Household__c = HouseholdId;   
                    if(objAdd.Id == null){
                        objAdd.Contact__c = objContact.Id;
                        Insert objAdd;      
                    }
                    else{
                        Update objAdd;
                    }
                    //processClassification(pb, objContact.Id, householdId);   
                }
                else{
                    blnSuccess = false;
                }
                UploadRecordMatchingGiving.processGiving(pb, objContact.Id, objContact.AccountId);
            }
            else
                blnSuccess = false;
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    static string getValues(string val1, string val2){
        if(NVL(val1)=='')
            return NVL(val2);
        else
            return NVL(val1);
    }
    static string NVL(string val){
        if(val == null)
            return '';
        else
            return val.trim();
    }
    public static Contact mapContactField(WGBH_PB5_UPLOAD__c pb, String flag){
        Contact objContact = new Contact();
        objContact.FirstName = getValues(pb.PB5_FIRST_NAME__c, pb.PB5_FIRST_NAME_2__c);
        objContact.LastName = getValues(pb.PB5_LAST_NAME__c, pb.PB5_LAST_NAME_2__c);
        //objContact.MiddleName = getValues(pb.PB5_MIDDLE_NAME__c, pb.PB5_MIDDLE_NAME__c);
        
        //objContact.DoNotCall = getValues(pb.PB5_NO_PHONE_PREFERRED__c, pb.PB5_NO_PHONE_PREFERRED__c);
        //objContact.WorkEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_2__c, pb.PB5_EMAIL_ADDRESS_2__c);
        objContact.Salutation = getValues(pb.PB5_SUFFIX__c, pb.PB5_SUFFIX_2__c);
        objContact.PreferredPhone__c = getValues(pb.PB5_TELEPHONE_TYPE_1__c, pb.PB5_TELEPHONE_TYPE_2__c);
        if(NVL(objContact.PreferredPhone__c) == 'H' || NVL(objContact.PreferredPhone__c) == 'Home'){
            objContact.HomePhone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        }
        if(NVL(objContact.PreferredPhone__c) == 'W' || NVL(objContact.PreferredPhone__c) == 'Work'){
            objContact.HomePhone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        }
        objContact.Preferred_Email__c = NVL(pb.PB5_EMAIL_TYPE_2__c);
        if(NVL(objContact.Preferred_Email__c) == 'Work'){
            objContact.WorkEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Home'){
            objContact.HomeEmail__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Assistant'){
            objContact.Assistant_Email__c = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else if(NVL(objContact.Preferred_Email__c) == 'Default Email'){
            objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        else{
            objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        }
        objContact.Email = getValues(pb.PB5_EMAIL_ADDRESS_1__c, pb.PB5_EMAIL_ADDRESS_2__c);
        objContact.Phone = getValues(pb.PB5_TELEPHONE_NUMBER_1__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        //objContact.OtherPhone = getValues(pb.PB5_TELEPHONE_NUMBER_2__c, pb.PB5_TELEPHONE_NUMBER_2__c);
        objContact.MailingStreet = getValues(pb.PB5_SHIP_TO_STREET_1__c, pb.PB5_STREET_1__c);
        objContact.MailingCity = getValues(pb.PB5_SHIP_TO_CITY__c, pb.PB5_CITY__c);
        objContact.MailingState = getValues(pb.PB5_SHIP_TO_STATE__c, pb.PB5_STATE__c);
        objContact.MailingPostalCode = getValues(pb.PB5_SHIP_TO_ZIP_CODE__c, pb.PB5_ZIP_CODE__c);
        /*
        if(flag == '1'){
            objContact.FirstName = pb.PB5_FIRST_NAME__c;//PB5_FIRST_NAME_2__c
            objContact.LastName = pb.PB5_LAST_NAME__c;//PB5_LAST_NAME_2__c
            //objContact.MiddleName = pb.PB5_MIDDLE_NAME__c;//PB5_MIDDLE_NAME_2__c
            objContact.Email = pb.PB5_EMAIL_ADDRESS_1__c;//PB5_EMAIL_ADDRESS_2__c
            //objContact.DoNotCall = pb.PB5_NO_PHONE_PREFERRED__c;
            //objContact.WorkEmail__c = pb.PB5_EMAIL_ADDRESS_2__c;
            objContact.Salutation = pb.PB5_SUFFIX__c;//PB5_SUFFIX_2__c
            objContact.PreferredPhone__c = pb.PB5_TELEPHONE_TYPE_1__c;//PB5_TELEPHONE_TYPE_2__c
            objContact.Phone = pb.PB5_TELEPHONE_NUMBER_1__c;//PB5_TELEPHONE_NUMBER_2__c
            //objContact.OtherPhone = pb.PB5_TELEPHONE_NUMBER_2__c;
            objContact.MailingStreet = pb.PB5_SHIP_TO_STREET_1__c;//PB5_STREET_1__c
            objContact.MailingCity = pb.PB5_SHIP_TO_CITY__c;//PB5_CITY__c
            objContact.MailingState = pb.PB5_SHIP_TO_STATE__c;//PB5_STATE__c
            objContact.MailingPostalCode = pb.PB5_SHIP_TO_ZIP_CODE__c;//PB5_ZIP_CODE__c
        }else{
            objContact.FirstName = pb.PB5_FIRST_NAME_2__c;
            objContact.LastName = pb.PB5_LAST_NAME_2__c;
            //objContact.MiddleName = pb.PB5_MIDDLE_NAME__c;//PB5_MIDDLE_NAME_2__c;
            objContact.Email = pb.PB5_EMAIL_ADDRESS_2__c;
            //objContact.DoNotCall = pb.PB5_NO_PHONE_PREFERRED__c;
            //objContact.WorkEmail__c = pb.PB5_EMAIL_ADDRESS_2__c;
            objContact.Salutation = pb.PB5_SUFFIX_2__c;
            objContact.PreferredPhone__c = pb.PB5_TELEPHONE_TYPE_2__c;
            objContact.Phone = pb.PB5_TELEPHONE_NUMBER_2__c;
            //objContact.OtherPhone = pb.PB5_TELEPHONE_NUMBER_2__c;
            objContact.MailingStreet = pb.PB5_STREET_1__c;
            objContact.MailingCity = pb.PB5_CITY__c;
            objContact.MailingState = pb.PB5_STATE__c;
            objContact.MailingPostalCode = pb.PB5_ZIP_CODE__c;        
        }            
        */
        return objContact;
    }

    static testMethod void myTest() {
        WGBH_PB5_UPLOAD__c objPB5 = New WGBH_PB5_UPLOAD__c();
        insert objPB5;
        
/*
        UploadRecordMatchingContact.ProcessContact(objPB5);
        UploadRecordMatchingContact.ProcessContact(objPB5,new List<sObject>(),'true');
        UploadRecordMatchingContact.InsertContact(objPB5,'true');
        UploadRecordMatchingContact.UpdateContact(new Contact(),objPB5,'true');
        UploadRecordMatchingContact.mapContactField(objPB5,'true');
  */            
    }    
    
}