kqed/src/objects/Bios__c.object
<CustomObject>
    <description>Object utilized for listing the various ways in which a Contact is related to the Organization and/or personal highlights that are important for profiling a person.  This object will has multiple record types and field dependencies to represent the different types of records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <picklist>
            <picklistValues>
                <fullName>321</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21CENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3TENORS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTAMIND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTASIAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTBLACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTBLIND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTCATH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTCHILD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTDEAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTDIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTEDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTELDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTENV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTGAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTHANDI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTHEALT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTJEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTLATIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTLIFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTMENTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTPROCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTREL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTREPRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTSPIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTURBAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTWOMEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERMAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date Term Completes (or is expected to complete)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Description__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Arts &amp; Culture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; How-to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News &amp; Public Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science &amp; Nature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Usage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAL ACADEMY SCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAL PERFORMANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EARTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPLOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIDDENVILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIDDENVLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLANPARENTGG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAN JOSE MUSEUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAN JOSE REP THEATRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF BALLET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF ED FUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF MOMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF OPERA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF SYMPHONY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TECH MUSEUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THEATREWORKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YERBA BUENA CTR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date Term Initiates</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Of_Degree__c</fullName>
        <formula>MID(degree_year__c , 0, 4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year of Degree</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>degree_code__c</fullName>
        <description>Degree Code</description>
        <inlineHelpText>Degree Code</inlineHelpText>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PhD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>degree_major__c</fullName>
        <description>Degree Major</description>
        <inlineHelpText>Enter the field for the major i.e. Accounting, Science, Engineering</inlineHelpText>
        <label>Major</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>degree_year__c</fullName>
        <description>Degree Year</description>
        <inlineHelpText>Degree Year</inlineHelpText>
        <label>Degree Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>education_begin_date__c</fullName>
        <description>Education Begin Date</description>
        <inlineHelpText>Education Begin Date</inlineHelpText>
        <label>Education Begin Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>education_end_date__c</fullName>
        <description>Education End Date</description>
        <inlineHelpText>Education End Date</inlineHelpText>
        <label>Education End Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>first_interest_source_value__c</fullName>
        <description>First Interest Source</description>
        <inlineHelpText>First Interest Source</inlineHelpText>
        <label>First Interest Source Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>first_program__c</fullName>
        <label>First Program</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interest_code__c</fullName>
        <description>Interest Code</description>
        <inlineHelpText>Interest Code</inlineHelpText>
        <label>Interest</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interest_code_value__c</fullName>
        <description>Interest Code</description>
        <inlineHelpText>Interest Code</inlineHelpText>
        <label>Interest Code Value</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_interest_source_value__c</fullName>
        <description>Last Interest Source</description>
        <inlineHelpText>Last Interest Source</inlineHelpText>
        <label>Last Interest Source Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_program__c</fullName>
        <label>Last Program</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>school_code__c</fullName>
        <description>School Name</description>
        <inlineHelpText>Name of school, university, college, community college, continuing education</inlineHelpText>
        <label>School Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bio</label>
    <nameField>
        <displayFormat>Bio-{00000000}</displayFormat>
        <label>Bio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bios</pluralLabel>
    <recordTypes>
        <fullName>Affiliation</fullName>
        <active>true</active>
        <label>Affiliation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Award</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s awards from the university or external organization(s)</description>
        <label>Award</label>
    </recordTypes>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s employment history</description>
        <label>Employment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Financial</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s financial information and/or history</description>
        <label>Financial</label>
    </recordTypes>
    <recordTypes>
        <fullName>Interest</fullName>
        <active>true</active>
        <label>Interest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s membership in internal and/or external organization(s)</description>
        <label>Membership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rating</fullName>
        <active>true</active>
        <label>Rating/Closeness</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volunteering</fullName>
        <active>true</active>
        <description>Profile representing Contact&apos;s past, present and/or future volunteering activities</description>
        <label>Volunteering</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account additional locations</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Requisition</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/HouseholdstabController.cls
public class HouseholdstabController {
    public List<Bios__c> EduBios{get;set;}
    public List<Bios__c> IntBios{get;set;}
    public List<Bios__c> AwaBios{get;set;}
    public List<Bios__c> EmpBios{get;set;}
    public List<Bios__c> FinBios{get;set;}
    public List<Bios__c> MemBios{get;set;}
    public List<Bios__c> VolBios{get;set;}
    public List<Bios__c> AffBios{get;set;}
    public List<Bios__c> RatBios{get;set;}
    public list<Bios__c> TruBios{get;set;}
    public String Delid{get;set;}
    public string id{get;set;}
    
    Public String EduRTid{get; set;}
    Public String IntRTid{get; set;}
    public string AwaRTid{get; set;}
    public string EmpRTid{get; set;}
    public string FinRTid{get; set;}
    public string MemRTid{get; set;}
    public string VolRTid{get; set;}
    public string AffRTid{get; set;}
    public string RatRTid{get; set;}
    public string TruRTid{get; set;}
    
    public String Edusize{get; set;}
    public string Intsize{get; set;}
    public string Awasize{get; set;}
    public string Empsize{get; set;}
    public string Finsize{get; set;}
    public string Memsize{get; set;}
    public string Volsize{get; set;}
    public string Affsize{get; set;}
    public string Ratsize{get; set;}
    public string Trusize{get; set;}
    

    public String Activetab{get; set;}    
    public householdsTabController(ApexPages.StandardController Controller) {
    try{
    EduRTid=[Select id from recordtype where name = 'Education'][0].id;
    IntRTid=[Select id from recordtype where name = 'Interest'][0].id;
    AwaRTid=[Select id from recordtype where name = 'Award'][0].id;
    EmpRTid=[Select id from recordtype where name = 'Employment'][0].id;
    FinRTid=[Select id from recordtype where name = 'Financial'][0].id;
    MemRTid=[Select id from recordtype where name = 'Membership'][0].id;
    VolRTid=[Select id from recordtype where name = 'Volunteering'][0].id;
    AffRTid=[Select id from recordtype where name = 'Affiliation'][0].id;
    RatRTid=[Select id from recordtype where name = 'Rating/Closeness'][0].id;
    TruRTid=[Select id from recordtype where name = 'Board/Trustee'][0].id;
    }
    catch(Exception ex)
    {
        System.debug('Exception in catch'+ex.getmessage());
    }
    
    id=ApexPages.CurrentPage().getParameters().get('id');
    Delid='aaa';
    List<Recordtype> rt = [Select r.Name, r.Id From RecordType r where name ='Education'];

    Edusize='';
    Intsize='';
    Awasize='';
    Empsize='';
    Finsize='';
    memsize='';
    Volsize='';
    Affsize='';
    Ratsize='';
    Trusize='';

    Activetab=rt[0].id;
    met();
    }
    
    public void Met(){
    
    EduBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c,
             Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c  from Bios__c 
             where Account__c=:id and recordtype.name='Education' and (school_code__c!='' OR degree_code__c!='' OR Year_Of_Degree__c!='' OR degree_major__c!=''
             OR Start_Date__c!=null OR End_Date__c!=null)];
             
             if(Edubios!=null)
             Edusize='Education' +' '+'['+String.valueof(Edubios.size()) +']';
             if(Edubios.size()==0)
             Edusize='Education';
            
    IntBios=[SELECT Id, Name,name__C, Interest_Code__c,recordtypeid, Interest_Description__c,Interest_Description_Type__c, Code__c, Year_Of_Degree__c,
             Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c from Bios__c 
             where Account__c=:id and recordtype.name='Interest' and (Interest_Description__c!='' OR Interest_Description_Type__c!='' OR Code__c!='') ];
             
             if(Intbios!=null)
             Intsize='interest' +' '+'['+String.valueof(Intbios.size()) +']';
             if(Intbios.size()==0)
             Intsize='Interest';
             
    AwaBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c, Account__c,
             Date_Awarded__c, Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c from Bios__c
             where Account__c=:id and recordtype.name='Award' and (Name__c!='' OR Account__c!='' OR Date_Awarded__c!=null)];
             
             if(Awabios!=null)
             Awasize='Award' +' '+'['+String.valueof(Awabios.size()) +']';
             if(Awabios.size()==0)
             Awasize='Award';
             
    EmpBios=[SELECT Id, Name,name__C, Interest_Code__c, Account__c, Title_Role__c, Department__c, Foundation_Name__c, Location__c,recordtypeid,
             Foundation_Assets__c, Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c from Bios__c
             where Account__c=:id and recordtype.name='Employment' and (Account__c!='' OR Title_Role__c!='' OR Department__c!='' OR Start_Date__c!=null
             OR End_Date__c!=null OR Foundation_Name__c!='' OR Location__c!='' OR Foundation_Assets__c!='')];
             
             if(Empbios!=null)
             Empsize='Employment' +' '+'['+String.valueof(Empbios.size()) +']';
             if(Empbios.size()==0)
             Empsize='Employment';
             
    FinBios=[SELECT Id, Name,name__C, Interest_Code__c, Real_Estate_Location__c, Real_Estate_Value__c, Boat_Location__c, Boat_Value__c,
             Car_Location__c, Car_Value__c, Banking_Location__c, Banking_Value__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c from Bios__c
             where Account__c=:id and recordtype.name='Financial' and (Real_Estate_Location__c!='' OR Real_Estate_Value__c!=null OR Boat_Location__c!='' OR Boat_Value__c!=null
             OR Car_Location__c!='' OR Car_Value__c!=null OR Banking_Location__c!='' OR Banking_Value__c!=null)];
             
             if(Finbios!=null)
             Finsize='Financial' +' '+'['+String.valueof(Finbios.size()) +']';
             if(Finbios.size()==0)
             Finsize='Financial';
             
    MemBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c, Account__c,
             Description__c, Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, last_Interest_Source_Value__c, Start_Date__c, End_Date__c, Board_Level__c,
             Position__c, Nominated_by__c from Bios__c where Account__c=:id and recordtype.name='Membership' and (Account__c!='' OR Board_Level__c!='' OR Position__c!=''
             OR Nominated_By__c!='' OR Start_Date__c!=null OR End_Date__c!=null)];
             
             if(Membios!=null)
             Memsize='Membership' +' '+'['+String.valueof(Membios.size()) +']';
             if(Membios.size()==0)
             Memsize='Membership';
             
    VolBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c, Account__c,
             Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c, Description__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c, Position__c
             from Bios__c where Account__c=:id and recordtype.name='Volunteering' and (Account__c!='' OR Position__c!='' OR Start_Date__c!=null OR End_Date__c!=null)];
             
             if(Volbios!=null)
             Volsize='Volunteering' +' '+'['+String.valueof(Volbios.size()) +']';
             if(Volbios.size()==0)
             Volsize='Volunteering';
             
    AffBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c, Gift_Amount__c,
             Location__c, Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_value__c, Start_Date__c, End_Date__c from Bios__c
             where Account__c=:id and recordtype.name='Affiliation' and (Name__c!='' OR Gift_Amount__c!=null OR Location__c!='' OR Start_Date__c!=null OR End_Date__c!=null)];
             
             if(Affbios!=null)
             Affsize='Affiliation' +' '+'['+String.valueof(Affbios.size()) +']';
             if(Affbios.size()==0)
             Affsize='Affiliation';
                          
    RatBios=[SELECT Id, Name,name__C, Rating_closeness__c, rating_type__c, Start_Date__c,recordtypeid, End_Date__c from Bios__c where Account__c=:id and 
             recordtypeid=:ratrtid and (Rating_Closeness__c!='' OR Rating_Type__c!='')]; 
             
             if(Ratbios!=null)
             Ratsize='Rating/Closeness' +' '+'['+String.valueof(Ratbios.size()) +']';
             if(Ratbios.size()==0)
             Ratsize='Rating/Closeness';
             
    TruBios=[SELECT Id, Name,name__C, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c,
             Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
             Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c  from Bios__c 
             where Account__c=:id and recordtypeid=:trurtid];
             
             if(Trubios!=null)
             Trusize='Other Board' +' '+'['+String.valueof(Trubios.size()) +']';
             if(Trubios.size()==0)
             Trusize='Other Board';
             
             System.debug('Activetab:'+activetab);
             }

    public PageReference Delmet() {
    System.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'+''+Delid);
    try{
    Bios__c b= [SELECT Id, Name from Bios__c where id=:DelId];
    delete b;
    }
    catch(Exception e)
    {
    System.debug('Delid not available');
    System.debug(e);
    }
    pagereference pg = new pagereference('/apex/Household_tabpanel?id='+id);
    // pg.setredirect(true);
    return pg;
    }
    
    public pagereference Bio() {
    System.debug('##################################################################################'+Activetab);
    if(activetab!=null && activetab!=''){
    pagereference pg = new pagereference('/a0C/e?RecordType='+Activetab+'&retURL=/'+id);
    return pg;
    }
    else
    return null;
    }
    
    public pagereference Newfun()
    {
    // System.debug(Sobject.get(Schema.Bios__c.related_to__c));
    Account h = [Select id, name from Account where id=:id];
    String householdname = h.name;
    if(householdname.contains('&'))
    {
    householdname = householdname.replaceall('&','%26');
    }
    String lookupid = 'CF00NA0000005bd7L';
    system.debug(activetab);
    pagereference pg = new pagereference('/a0C/e?RecordType='+activetab+'&CF00NA0000005bd7L_lkid='+id+'&'+lookupid+'='+householdname);
    system.debug('infun'+pg.geturl());
    pg.setredirect(true);
    return pg;
    }

    public static testmethod void tes(){
    contact c = new contact();
    c.Lastname='test';
    insert c;
    Account hh = new Account();
    hh.name=' hhhh';
    insert hh;
    List<Bios__c> bb = [Select id, name from Bios__c limit 1]; //RK - removed the where clause

    Apexpages.CurrentPage().getParameters().put('id', hh.id);
    householdstabcontroller tc = new householdstabcontroller(new ApexPages.StandardController(hh));
    //Pagereference pg = tc.bio();
    tc.met();
    Pagereference pgg = tc.newfun();
    System.debug(pgg.geturl());
    //List<Bios__c> b = new List<bios__c>([SELECT id, name from Bios__c where id=:bb[0].id limit 1]); // removed redundant soql
    //tc.delId=b[0].id;
    tc.delId=bb[0].id;
    pagereference pg = tc.delmet(); 
    }
 
}