kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>This campaign name is used for the Campaign Program Reporting Tool and is not to be confused with the Campaign Name used for the out of the box Salesforce text campaign name.</inlineHelpText>
        <label>Campaign Name CPRT</label>
        <picklist>
            <controllingField>Product_Program__c</controllingField>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Technique__c</fullName>
        <description>Technique</description>
        <inlineHelpText>Channel is the mechanism regarding how we touch the donor or potential donor</inlineHelpText>
        <label>Channel (Technique)</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchandise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Giving_Segment__c</fullName>
        <description>These are the segments that define the giving level from a donor</description>
        <label>Giving Segment</label>
        <picklist>
            <controllingField>Financial_segment_Level1__c</controllingField>
            <picklistValues>
                <fullName>Basic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hundred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archangel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Contributions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Air Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unrestricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Murrow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Murrow Society</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ralph Lowell Society</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <inlineHelpText>Product/Program is the larger program of the campaign.  Membership;Survey;Stewardship;Capital;Auction;Cultivation</inlineHelpText>
        <label>Product/Program</label>
        <picklist>
            <picklistValues>
                <fullName>Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Solicitation_Type__c</fullName>
        <label>Solicitation Type</label>
        <picklist>
            <controllingField>Giving_Segment__c</controllingField>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejoin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time_Date__c</fullName>
        <inlineHelpText>Start Date and Time of the Overall Program</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>The radio/tv station call letters that the campaign is representing.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>KCRW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KQED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>KQED+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Channel__c</fullName>
        <inlineHelpText>Sub Channel is a descriptor of the Channel</inlineHelpText>
        <label>Sub Channel</label>
        <picklist>
            <controllingField>Channel_Technique__c</controllingField>
            <picklistValues>
                <fullName>.org</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>44</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>57</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCTV Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KIDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Tour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Micro-Sites (Landing Pages)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay Per Click</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streaming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/classes/CampaignSourceCode.cls
Public Class CampaignSourceCode {
    Public string Char1_2_3(Campaign c) {
        String strReturn = '---';
        
        if (c.Station__c == 'WGBH') strReturn = 'GBH';
        if (c.Station__c == 'WGBY') strReturn = 'GBY';
        if (c.Station__c == 'WCAI') strReturn = 'CAI';
        if (c.Station__c == 'KCRW') strReturn = 'CRW';
        if (c.Station__c == 'ACADEMY OF MUSIC') strReturn = 'AOM';
        if (c.Station__c == 'CLASSICAL RADIO') strReturn = 'GBH';
        
        return strReturn;
    }
    
    Public string Char4(Campaign c) {
        String strReturn = '-';
        if(c.Product_Program__c == 'MEMBERSHIP') {
            if(c.Campaign_Name__c == 'ANNUAL') strReturn = 'A';
            if(c.Campaign_Name__c == 'EVENTS') strReturn = 'E';
            if(c.Campaign_Name__c == 'MATCHING GIFT') strReturn = 'G';
            if(c.Campaign_Name__c == 'IN KIND') strReturn = 'K';
            if(c.Campaign_Name__c == 'SALES') strReturn = 'S';
            if(c.Campaign_Name__c == 'VOLUNTEER') strReturn = 'V';
        }
        else {
            if(c.Product_Program__c == 'MAJOR GIFT') strReturn = 'M';
            if(c.Product_Program__c == 'AUCTION') strReturn = 'D';
            if(c.Product_Program__c == 'CULTIVATION') strReturn = 'C';
            if(c.Product_Program__c == 'STEWARDSHIP') strReturn = 'C';
            if(c.Product_Program__c == 'ONLINE') strReturn = 'O';
            if(c.Product_Program__c == 'UNDERWRITING') strReturn = 'U';
            if(c.Product_Program__c == 'SURVEY') strReturn = 'P';
        }
        
        return strReturn;
    }

    Public string Char5(Campaign c) {
        String strReturn = '-';
        
        if(c.Product_Program__c == 'MAJOR GIFT') {
            if(c.Campaign_Name__c == 'BUILDING') strReturn = 'B';
            if(c.Campaign_Name__c == 'CAPITAL') strReturn = 'C';
            if(c.Campaign_Name__c == 'EVENTS') strReturn = 'E';
            if(c.Campaign_Name__c == 'FOUNDATION DEVELOPMENT') strReturn = 'F';
            if(c.Campaign_Name__c == 'PLANNED GIVING') strReturn = 'P';
            if(c.Campaign_Name__c == 'RESTRICTED GIVING') strReturn = 'R';
            
        }
        else if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c=='ANNUAL' && !(c.Channel_Technique__c =='WEB' && c.Channel_Technique__c =='TELESALES')) {
            if(c.Giving_Segment__c == 'RALPH LOWELL SOCIETY') strReturn = 'D';
            if(c.Giving_Segment__c == 'MURROW SOCIETY') strReturn = 'D';
            if(c.Giving_Segment__c == 'LEADERSHIP') strReturn = 'Q';
            if(c.Giving_Segment__c == 'MID LEVEL') strReturn = 'I';
            if(c.Giving_Segment__c == 'MEMBERSHIP') strReturn = 'M';
            if(c.Giving_Segment__c == 'ON-AIR PLEDGE') strReturn = 'O';
            if(c.Giving_Segment__c == 'SUSTAINER') strReturn = 'S';
            if(c.Giving_Segment__c == 'VEHICLE DONATION') strReturn = 'V';
        }
        
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c == 'IN KIND') strReturn = 'B';
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c == 'MATCHING') strReturn = 'G';
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c == 'EVENTS') strReturn = 'E';
        if(c.Product_Program__c == 'AUCTION' && c.Campaign_Name__c == 'SALES') strReturn = 'S';
        
        
        if(c.Product_Program__c == 'AUCTION' && c.Campaign_Name__c == 'INKIND') strReturn = 'D';
        if(c.Product_Program__c == 'AUCTION' && c.Campaign_Name__c == 'AUCTION') strReturn = 'B';
        if(c.Product_Program__c == 'AUCTION' && c.Campaign_Name__c == 'VOLUNTEER') strReturn = 'V';
        
        
        
        
        if(c.Product_Program__c == 'UNDERWRITING' && c.Campaign_Name__c == 'SALES') strReturn = 'S';
        
        
        
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c == 'ANNUAL' && c.Channel_Technique__c == 'WEB') strReturn = 'W';
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c == 'ANNUAL' && c.Channel_Technique__c == 'TELESALES' && c.Sub_Channel__c == 'INBOUND') strReturn = 'C';        
        
        if(strReturn=='-') strReturn = 'U';
        return strReturn;
    }
    
    Public string Char6(Campaign c) {
        String strReturn = '-';
        
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c=='ANNUAL' && c.Giving_Segment__c <> 'ON-AIR PLEDGE') {
            if(c.Solicitation_Type__c == 'ACQUISITION') strReturn = 'Q';
            if(c.Solicitation_Type__c == 'ADD GIFT') strReturn = 'A';
            if(c.Solicitation_Type__c == 'LAPSED') strReturn = 'L';
            if(c.Solicitation_Type__c == 'REJOIN') strReturn = 'L';
            if(c.Solicitation_Type__c == 'RENEWAL') strReturn = 'R';
            if(c.Solicitation_Type__c == 'UPGRADE') strReturn = 'U';
        }
        
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c=='ANNUAL' && c.Giving_Segment__c == 'ON-AIR PLEDGE') {
            if(c.Channel_Technique__c == 'TV') {
                if(c.Sub_Channel__c == '2') strReturn = '2';
                if(c.Sub_Channel__c == '44') strReturn = '4';
                if(c.Sub_Channel__c == 'KIDS') strReturn = 'K';
                if(c.Sub_Channel__c == 'WORLD') strReturn = 'W';
                if(c.Sub_Channel__c == 'CREATE') strReturn = 'D';
                if(c.Sub_Channel__c == '57') strReturn = 'P';
            
            }
            if(c.Channel_Technique__c == 'RADIO') {
                if(c.Sub_Channel__c == 'WCAI') strReturn = '9';
                if(c.Sub_Channel__c == '89.7') strReturn = 'F';
                if(c.Sub_Channel__c == '99.5') strReturn = 'C';            
            }            
        }
        if(c.Product_Program__c == 'AUCTION') strReturn = 'A';

        if(c.Product_Program__c == 'UNDERWRITING' && c.Giving_Segment__c == 'LOCAL') strReturn = 'L';
        if(c.Product_Program__c == 'UNDERWRITING' && c.Giving_Segment__c == 'NATIONAL') strReturn = 'N';


        if(strReturn == '-') strReturn = 'G';
        
        return strReturn;
    }
    
    Public string Char7_8_9_10(Campaign c) {
        String strReturn = '----';
        if(c.Start_Time_Date__c!=null) {
            string strYY = string.valueOf(c.Start_Time_Date__c.Year());
            strYY = strYY.substring(strYY.length()-2,strYY.length());
    
            string strMM = string.valueOf(c.Start_Time_Date__c.Month());
            
            if(strMM.length()==1) strMM = '0' + strMM;
            
            strReturn = strYY + strMM;           
            
        }
        return strReturn;
    }
    Public string Char11_12(Campaign c) {
        String strReturn = '--';
        
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c=='ANNUAL' && c.Giving_Segment__c <> 'ON-AIR PLEDGE' && c.Effort_for_Project__c!=null) {
            if (c.Effort_for_Project__c.length()==1 && c.Effort_for_Project__c!='0') {
                strReturn = '0' + c.Effort_for_Project__c;
            }
            else {
                strReturn = c.Effort_for_Project__c;
            }
        }
        if(c.Product_Program__c == 'MEMBERSHIP' && c.Campaign_Name__c=='ANNUAL' && c.Giving_Segment__c == 'ON-AIR PLEDGE') {
            strReturn = string.ValueOf(c.Start_Time_Date__c.Day());
            if(strReturn.length()==1) strReturn = '0' + strReturn;
        }
        
        if(strReturn=='--' || strReturn=='') strReturn = '01';
        
        return strReturn;
    }
    Public string Char13_14_15(Campaign c) {
        String strReturn = '---';
 
        if(c.ParentID==null) {
            strReturn = '000';
        }
        else {
            strReturn = c.Program_Count__c;
        }
        if(strReturn == null || strReturn == '' || strReturn == '---'){
            strReturn = '000';
        }
        return strReturn;    
    }

    static testMethod void myTest() {
        CampaignSourceCode clsTest = new CampaignSourceCode();
        Campaign c = new Campaign(name='test');
        c.Station__c = 'WGBH';
        c.Product_Program__c = 'MEMBERSHIP';
        c.Campaign_Name__c = 'ANNUAL';
        c.Solicitation_Type__c = 'ACQUISITION';
        c.Start_Time_Date__c = system.Now();
        c.Effort_for_Project__c = '1';
        clsTest.Char1_2_3(c);
        clsTest.Char4(c);
        clsTest.Char5(c);
        clsTest.Char6(c);
        clsTest.Char13_14_15(c);
        clsTest.Char11_12(c);
        clsTest.Char7_8_9_10(c);
        
    }    
    
}