kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>Campaign Type; Annual, Capital, Auction, Event (this is the 2nd value in the source code i.e. HAM = WGBH, Annual, Major Gift</description>
        <inlineHelpText>Campaign is a marketing campaign that refers to a general theme that runs through every touch.</inlineHelpText>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Annual Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Kind Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Annual Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Kind Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gifts Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realty Perks Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation Giving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_Opportunity_ID__c</fullName>
        <description>Unique Opportunity ID to pass as an Alt ID to Team Approach, will allow us to map the Opportunity to the payment from TA</description>
        <inlineHelpText>Unique Salesforce ID which allows us to match the opportunity record on the contact or household to the payment</inlineHelpText>
        <label>SFDC Opportunity ID DELETE</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>installment_amount__c</fullName>
        <description>Installment Amount</description>
        <inlineHelpText>Installment Amount</inlineHelpText>
        <label>Installment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pledge_amount__c</fullName>
        <description>Pledge Amount</description>
        <inlineHelpText>Pledge Amount</inlineHelpText>
        <label>Pledge Amt Delete</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations</description>
        <label>Annual</label>
    </recordTypes>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation Process</businessProcess>
        <description>Donation to non-Annual programs (Capital Campaign, Restricted Giving, Planned Giving, Foundation Giving, Matching Gifts, Underwriting, etc.)</description>
        <label>Donation</label>
    </recordTypes>
</CustomObject>

kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>Flag_Review_Reason__c</fullName>
        <label>Flag Review Reason</label>
        <picklist>
            <picklistValues>
                <fullName>MORE THAN 1 MATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC PLEDGE ID or PLEDGE NUMBER EXIST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS AMT equal to PAYMENT AMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT DATE ON PLEDGE WITH PREMIUMS &lt; 1 YEAR FROM CURRENT DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; SUM OF PRODUCTS MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; PRODUCT MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT TYPE IS NULL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_for_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag for Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_GIFT_TYPE__c</fullName>
        <description>The gift type</description>
        <label>PB5_GIFT_TYPE</label>
        <picklist>
            <picklistValues>
                <fullName>NW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_INSTALLMENT_AMOUNT__c</fullName>
        <description>THE AMOUNT OF THE SCHEDULED INSTALLEMENT. MAPS TO: UL_BATCH_DETAIL.INSTALLMENT_AMOUNT</description>
        <label>PB5_INSTALLMENT_AMOUNT</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PB5_IS_NEW__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this a new record for Salesforce.</description>
        <label>PB5_IS_NEW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_IS_PROCESSED__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has this record been processed successfully?</description>
        <label>PB5_IS_PROCESSED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_PAYMENT_AMOUNT__c</fullName>
        <description>THE AMOUNT OF THE PARTICULAR PAYMENT. MAPS TO: UL_BATCH_DETAIL.PAYMENT_AMOUNT</description>
        <label>PB5_PAYMENT_AMOUNT</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PB5_PAYMENT_METHOD__c</fullName>
        <description>METHOD OF PAYMENT.  Kimbia: (KA, KD, KM, KV) Convio (WA, WD, WM, WV) maps to: UL_BATCH_DETAIL.PAYMENT_METHOD</description>
        <label>PB5_PAYMENT_METHOD</label>
        <picklist>
            <picklistValues>
                <fullName>Cybersource American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cybersource Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cybersource Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cybersource Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage Unknown Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Fund Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Donation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kimbia Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_PLEDGE_AMOUNT__c</fullName>
        <description>THE AMOUNT OF THE PLEDGE/OPPORTUNITY. MAPS TO: UL_BATCH_DETAIL.PLEDGE_AMOUNT</description>
        <label>PB5_PLEDGE_AMOUNT</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PB5_PLEDGE_NUMBER__c</fullName>
        <description>THE SFDC OPPORTUNITY ID</description>
        <label>PB5_PLEDGE_NUMBER</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SFDC_ID__c</fullName>
        <description>Salesforce ID of household, contact or organization maps to: UL_ACCOUNTS.ACCOUNT_ID</description>
        <label>PB5_SFDC_ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PB5_Stage__c</fullName>
        <label>PB5 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_TRANSACTION_TYPE__c</fullName>
        <label>PB5_TRANSACTION_TYPE</label>
        <picklist>
            <picklistValues>
                <fullName>PLEDGE WITH PAYMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE NO PAYMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLKIMBIA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/UploadRecordMatchingOpportunity.cls
public class UploadRecordMatchingOpportunity{

    Public static List<Opportunity> lstOppt = new List<Opportunity>();
    public static void processOpportunity(WGBH_PB5_UPLOAD__c PB5){
        if(IsTransactionPayment(PB5)==true){//transation type = payment? ; If true then check SFDC Opp Id or Pledge no exist?
            getOpportunity(PB5);
            if(IsSFDCOppIdOrPledgenoExist(PB5)==true){
                if(PB5.PB5_GIFT_TYPE__c == 'NW'){//Gift type new?
                    GTR(PB5);
                    ApplyPaymentToOpenOpportunitySubProcess3(PB5);
                    //Go to 1
                    //OVER
                }
                else{
                    ApplyPaymentToOpenOpportunitySubProcess3(PB5);
                    //Go to 1
                    //OVER
                }
            }
            else{
                //Other unfulfilled Partially fulfilled pladge of same station product and campaign
                List<sObject> lst = PledgeOfSameStation(PB5);
                if(lst.size()>0){
                    if(lst.size()>1){//More than 1?
                        //Flag review         
                        PB5.Flag_for_Review__c = true;
                        PB5.Flag_Review_Reason__c = 'MORE THAN 1 MATCH';
                        PB5.PB5_IS_PROCESSED__c = false;
                        PB5.PB5_IS_NEW__c = true;
                        //OVER
                    }
                    else{
                        if(PB5.PB5_GIFT_TYPE__c == 'NW'){//Gift type new?
                            GTR(PB5);
                            ApplyPaymentToPladgeSubProcess3(PB5);
                            //Goto 1
                            //OVER
                        }
                        else{
                            if(Installment_SustainingGift(PB5)==true){
                                //PB5_INSTALLMENT_AMOUNT__c
                                //PB5_PAYMENT_AMOUNT__c
                                if(PB5.PB5_INSTALLMENT_AMOUNT__c == PB5.PB5_PAYMENT_AMOUNT__c){
                                    ApplyPaymentToPladgeSubProcess3(PB5);
                                    //OVER
                                }
                                else{//Flag for review
                                    //INS AMT equal to PAYMENT AMT    
                                    PB5.Flag_for_Review__c = true;
                                    PB5.PB5_IS_PROCESSED__c = false;
                                    PB5.PB5_IS_NEW__c = true;
                                    //PB5.Flag_Review_Reason__c = 'INS AMT equal to PAYMENT AMT ';(actually it should be: INS AMT not equal to PAYMENT AMT)
                                    //OVER
                                }
                            }
                            else{
                                Opportunity opp = (Opportunity)lst[0];
                                if(PB5.PB5_PAYMENT_AMOUNT__c == opp.installment_amount__c){//Opp amt = payment amount?
                                    ApplyPaymentToPladgeSubProcess3(PB5);
                                    //Go to 1
                                    //OVER
                                }
                                else if(PB5.PB5_PAYMENT_AMOUNT__c < opp.installment_amount__c){//Opp amt < payment amount?
                                    //Apply Payment: Change stage to Partially fulfilled
                                    //Go to 1
                                    //OVER
                                }
                                else if(PB5.PB5_PAYMENT_AMOUNT__c > opp.installment_amount__c){//Opp amt < payment amount?
                                    //Update Opp amount = payment amount; Change stage Fulfilled
                                    //Go to 1
                                    //OVER
                                }
                            }
                        }
                    }
                }
                else{//
                    CreatePledgeSubProcess3(PB5);
                    GTR(PB5);
                    //PB5.PB5_Stage__c = 'D';
                    //OVER
                }
            }
        }
        else{//If false then check SFDC pledge Id or Pledge number exist?
            if(IsSFDCPledgeIdOrPledgenoExist(PB5)==true){                
                PB5.Flag_for_Review__c = true;
                PB5.Flag_Review_Reason__c = 'SFDC PLEDGE ID or PLEDGE NUMBER EXIST';
                PB5.PB5_IS_PROCESSED__c = false;
                PB5.PB5_IS_NEW__c = true;
                //OVER
            }
            else{
                //Create Pledge(Apply subprogramming subprocess3)
                CreatePledgeSubProcess3(PB5);
                GTR(PB5);
                //PB5.PB5_Stage__c = 'D';
                //OVER
            }
        }
    }
    public static boolean IsTransactionPayment(WGBH_PB5_UPLOAD__c PB5){

        if(PB5.PB5_TRANSACTION_TYPE__c == 'PLEDGE WITH PAYMENT' || PB5.PB5_TRANSACTION_TYPE__c == 'PLEDGE NO PAYMENT' || PB5.PB5_TRANSACTION_TYPE__c == 'PAYMENT' )
            return true;
        else
            return false;
    }
    public static void getOpportunity(WGBH_PB5_UPLOAD__c PB5){
        String pb5SFDCId = String.ValueOf(PB5.PB5_SFDC_ID__c);
        String pb5PledgeNo = String.ValueOf(PB5.PB5_PLEDGE_NUMBER__c);
        //SFDC_Opportunity_ID__c
        lstOppt = [Select Id From Opportunity Where (pledge_number__c =: pb5PledgeNo and Pledge_number__c!='') OR (SFDC_Opportunity_ID__c =: pb5SFDCId and SFDC_Opportunity_ID__c!='')];
        return;
    }
    public static boolean IsSFDCOppIdOrPledgenoExist(WGBH_PB5_UPLOAD__c PB5){
        if(lstOppt.size()>0)
            return true;
        else            
            return false;
    }
    public static boolean IsSFDCPledgeIdOrPledgenoExist(WGBH_PB5_UPLOAD__c PB5){
        List<Opportunity> lstOpp = new List<Opportunity>();
        String pb5SFDCId = String.ValueOf(PB5.PB5_SFDC_ID__c);
        String pb5PledgeNo = String.ValueOf(PB5.PB5_PLEDGE_NUMBER__c);
        //SFDC_Opportunity_ID__c
        lstOpp = [Select Id From Opportunity Where pledge_number__c =: pb5PledgeNo and Pledge_Number__c!=''];
        if(lstOpp.size()>0)
            return true;
        else            
            return false;
    }
    public static List<sObject> PledgeOfSameStation(WGBH_PB5_UPLOAD__c PB5){
        List<sObject> lst;
        //Other unfulfilled Partially fulfilled pladge of same station product and campaign
        return lst;
    }
    public static void ApplyPaymentToOpenOpportunitySubProcess3(WGBH_PB5_UPLOAD__c PB5){
        //pledge_amount__c; payment_Amount__c; installment_amount__c
        //PB5_INSTALLMENT_AMOUNT__c; PB5_PAYMENT_AMOUNT__c; PB5_PLEDGE_AMOUNT__c
        for(Opportunity opp:lstOppt){
            opp.pledge_amount__c = PB5.PB5_PLEDGE_AMOUNT__c;
            opp.payment_Amount__c = PB5.PB5_PAYMENT_AMOUNT__c;
            opp.installment_amount__c = PB5.PB5_INSTALLMENT_AMOUNT__c;
            if(opp.payment_Amount__c == null || opp.payment_Amount__c == 0)
                opp.StageName = 'Pledged';
            else if(opp.payment_Amount__c == opp.pledge_amount__c)
                opp.StageName = 'Closed Won';
            else if(opp.payment_Amount__c < opp.pledge_amount__c)
                opp.StageName = 'Partial Close';
        }
    }
    public static void GTR(WGBH_PB5_UPLOAD__c PB5){
        for(Opportunity opp:lstOppt){
            if(opp.Campaign_Type__c == 'Annual Giving')
                GiftTypeRule.GTR(PB5,lstOppt,GiftTypeRule.gtrType.ANNUALGTR);
            else if(opp.Campaign_Type__c == 'In-Kind Gifts')
                GiftTypeRule.GTR(PB5,lstOppt,GiftTypeRule.gtrType.INKINDGTR);
            else
                GiftTypeRule.GTR(PB5,lstOppt,GiftTypeRule.gtrType.DONATIONPURCHASEGTR);
        }
    }
    public static void CreatePledgeSubProcess3(WGBH_PB5_UPLOAD__c PB5){
        ApplyPaymentToOpenOpportunitySubProcess3(PB5);
    }
    public static boolean Installment_SustainingGift(WGBH_PB5_UPLOAD__c PB5){
        return false;
    }
    public static void ApplyPaymentToPladgeSubProcess3(WGBH_PB5_UPLOAD__c PB5){
        if(PB5.PB5_TRANSACTION_TYPE__c == 'PLEDGE WITH PAYMENT'){//TRANSACTION TYPE = PLEDGE WITH PAYMENT?: YES
            if(PB5.PB5_PAYMENT_METHOD__c == 'Stock'){//PAYMENT METHOD = STOCK: YES
                //lstOppt[0].gift_date__c = DELIVERY DATE FROM RLS   
                //lstOppt[0].last_payment_date__c = lstOppt[0].gift_date__c          
                //REVENUE DATE = lstOppt[0].gift_date__c
            }
            else{//PAYMENT METHOD = STOCK: NO
                //lstOppt[0].gift_date__c = DATE RECEIVED
                //lstOppt[0].last_payment_date__c = DATE RECEIVED
                //REVENUE DATE = PAYMENT DATE
            }
        }else{//TRANSACTION TYPE = PLEDGE WITH PAYMENT?: NO
            if(PB5.PB5_TRANSACTION_TYPE__c == 'PLEDGE NO PAYMENT'){//TRANSACTION TYPE = PLEDGE NO PAYMENT?: YES
                if(PB5.PB5_PAYMENT_METHOD__c == 'Vehicle Giving'){//PAYMENT METHOD = VEHICLE DONATION : YES
                    //lstOppt[0].gift_date__c = VEHICLE SELL DATE
                    //lstOppt[0].last_payment_date__c = PAYMENT RECEIVED       
                    //REVENUE DATE = PAYMENT DATE
                }
                else{//PAYMENT METHOD = VEHICLE DONATION : NO
                    //lstOppt[0].gift_date__c = PLEDGE DATE
                    //lstOppt[0].last_payment_date__c = NULL
                    //REVENUE DATE = NULL
                }
            }
            else{//TRANSACTION TYPE = PLEDGE NO PAYMENT?: NO
                if(PB5.PB5_PAYMENT_METHOD__c == 'Check'){//PAYMENT METHOD = CHECK : YES
                    //lstOppt[0].gift_date__c = NULL
                    //lstOppt[0].last_payment_date__c = DATE RECEIVED
                    //REVENUE DATE = PAYMENT DATE
                }
                else{//PAYMENT METHOD = CHECK : NO
                    if(PB5.PB5_PAYMENT_METHOD__c == 'Electronic Fund Transfer'){//PAYMENT METHOD = EFT : YES
                        if(PB5.PB5_GIFT_KIND__c == 'OP'){//GIFT KIND = ONE PAYMENT : YES
                            //lstOppt[0].gift_date__c = NULL
                            //lstOppt[0].last_payment_date__c = DATE RECEIVED
                            //REVENUE DATE = PAYMENT DATE
                        }
                        else{//GIFT KIND = ONE PAYMENT : NO
                            //lstOppt[0].gift_date__c = NULL
                            //lstOppt[0].last_payment_date__c = DATE RECEIVED
                            //REVENUE DATE = PAYMENT DATE
                        }
                    }
                    else{//PAYMENT METHOD = EFT : NO
                        if(PB5.PB5_GIFT_KIND__c == 'OP'){//GIFT KIND = ONE PAYMENT : YES
                            //GIFT DATE = NULL
                            //PAYMENT DATE = DATE RECEIVED
                            //REVENUE DATE = IF PLEDGE IN PREVIOUS MONTH AND CHARGE PAYMENT IN 1st 2 BUSINESS DAY OF CURRENT MONTH, SET TO GIFT DATE OF PLEDGE ELSE PAYMENT DATE
                        }
                        else{//GIFT KIND = ONE PAYMENT : NO
                            //IF 1st INSTALL PAYMENT(PAYMENT AMOUNT = PAID AMOUNT ON PARENT PLEDGE)
                                //GIFT DATE = NULL
                                //PAYMENT DATE = DATE RECEIVED
                                //REVENUE DATE = IF PLEDGE IN PREVIOUS MONTH AND CHARGE PAYMENT IN 1st 2 BUSINESS DAY OF CURRENT MONTH, SET TO GIFT DATE OF PLEDGE ELSE PAYMENT DATE
                            //ELSE
                                //GIFT DATE = NULL
                                //PAYMENT DATE = DATE RECEIVED
                                //REVENUE DATE = PAYMENT DATE                            
                        }
                    }
                }
            }
        }
    }
    
    static testmethod void myTest() {
        WGBH_PB5_UPLOAD__c PB5 = new WGBH_PB5_UPLOAD__c();
        insert PB5;
        UploadRecordMatchingOpportunity.IsTransactionPayment(PB5);
        UploadRecordMatchingOpportunity.getOpportunity(PB5);
        UploadRecordMatchingOpportunity.IsSFDCOppIdOrPledgenoExist(PB5);
        UploadRecordMatchingOpportunity.IsSFDCPledgeIdOrPledgenoExist(PB5);
        UploadRecordMatchingOpportunity.PledgeOfSameStation(PB5);
        UploadRecordMatchingOpportunity.ApplyPaymentToOpenOpportunitySubProcess3(PB5);
        UploadRecordMatchingOpportunity.GTR(PB5);
        UploadRecordMatchingOpportunity.CreatePledgeSubProcess3(PB5);
        UploadRecordMatchingOpportunity.Installment_SustainingGift(PB5);
        UploadRecordMatchingOpportunity.processOpportunity(PB5);
        UploadRecordMatchingOpportunity.ApplyPaymentToPladgeSubProcess3(PB5);

        
    }  
}