kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>This campaign name is used for the Campaign Program Reporting Tool and is not to be confused with the Campaign Name used for the out of the box Salesforce text campaign name.</inlineHelpText>
        <label>Campaign Name CPRT</label>
        <picklist>
            <controllingField>Product_Program__c</controllingField>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Technique__c</fullName>
        <description>Technique</description>
        <inlineHelpText>Channel is the mechanism regarding how we touch the donor or potential donor</inlineHelpText>
        <label>Channel (Technique)</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchandise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Mechanism__c</fullName>
        <description>How we expect the response to come in.</description>
        <inlineHelpText>How we expect the response to come in.</inlineHelpText>
        <label>Response Mechanism</label>
        <picklist>
            <picklistValues>
                <fullName>Call Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Coupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QC Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesale Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tickets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <inlineHelpText>The radio/tv station call letters that the campaign is representing.</inlineHelpText>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>KCRW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KQED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>KQED+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Channel__c</fullName>
        <inlineHelpText>Sub Channel is a descriptor of the Channel</inlineHelpText>
        <label>Sub Channel</label>
        <picklist>
            <controllingField>Channel_Technique__c</controllingField>
            <picklistValues>
                <fullName>.org</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>44</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>57</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCTV Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KIDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Tour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Micro-Sites (Landing Pages)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Movie Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay Per Click</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streaming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underwriting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Mechanism__c</fullName>
        <label>Response Mechanism</label>
        <picklist>
            <picklistValues>
                <fullName>Call Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Coupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QC Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telesale Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tickets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Renew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call from account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call to account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email from account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email to account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax from account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax to account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Retail PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand-Delivered to Station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet message from account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet message to account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation sent to account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Station__c</fullName>
        <label>Station</label>
        <picklist>
            <picklistValues>
                <fullName>KQED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>KQED+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gift_kind__c</fullName>
        <label>Gift Kind</label>
        <picklist>
            <picklistValues>
                <fullName>One Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustaining Gift</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Annual</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations</description>
        <label>Annual</label>
    </recordTypes>
    <recordTypes>
        <fullName>Annual_Installment</fullName>
        <active>true</active>
        <businessProcess>Annual Process</businessProcess>
        <description>Annual Membership donations - installments</description>
        <label>Annual - Installment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation Process</businessProcess>
        <description>Donation to non-Annual programs (Capital Campaign, Restricted Giving, Planned Giving, Foundation Giving, Matching Gifts, Underwriting, etc.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Donation_Installment</fullName>
        <active>true</active>
        <businessProcess>Donation Process</businessProcess>
        <description>Donation to non-Annual programs (Capital Campaign, Restricted Giving, Planned Giving, Foundation Giving, Matching Gifts, Underwriting, etc.) - Installments</description>
        <label>Donation - Installment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Inkind</fullName>
        <active>true</active>
        <businessProcess>Inkind Process</businessProcess>
        <description>Business Member Partners, Auction Donations</description>
        <label>Inkind</label>
    </recordTypes>
    <recordTypes>
        <fullName>Inkind_Installment</fullName>
        <active>true</active>
        <businessProcess>Inkind Process</businessProcess>
        <description>Business Member Partners, Auction Donations - Installments</description>
        <label>Inkind - Installment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Purchase</fullName>
        <active>true</active>
        <businessProcess>Purchase Process</businessProcess>
        <description>Purchase of goods (tickets, merchandise) that does not result in an Annual Membership</description>
        <label>Purchase</label>
    </recordTypes>
    <recordTypes>
        <fullName>Purchase_Installment</fullName>
        <active>true</active>
        <businessProcess>Purchase Process</businessProcess>
        <description>Purchase of goods (tickets, merchandise) that does not result in an Annual Membership - Installments</description>
        <label>Purchase - Installment</label>
    </recordTypes>
</CustomObject>

kqed/src/classes/EditGiving.cls
public class EditGiving {

    public EditGiving(ApexPages.StandardController controller) {
        
    }
    
    Public String retURL{get;set;}
    public String currentURL{get;set;}
    Public PageReference chooseDestination(){
        //https://cs3.salesforce.com/006Q0000007vZU0/e?nooverride=1&retURL=%2F006Q0000007vZU0
        String URL = '';
        currentURL = ApexPages.currentPage().getHeaders().get('Host');
        retURL = ApexPages.CurrentPage().getParameters().get('retURL');
        String Id = ApexPages.CurrentPage().getParameters().get('id');
        //string RecordType = ApexPages.CurrentPage().getParameters().get('RecordType');
        string ent = ApexPages.CurrentPage().getParameters().get('ent');
        string save_new = ApexPages.CurrentPage().getParameters().get('save_new');
        string lkid = ApexPages.CurrentPage().getParameters().get('_lkid');
        string objType = '';
        Opportunity objGiving = [Select RecordType.DeveloperName, RecordTypeId From Opportunity Where Id=:Id];
        String DeveloperName = objGiving.RecordType.DeveloperName;
        String RecordType = objGiving.RecordTypeId;
        //https://cs3.salesforce.com/006Q0000007vZU0/e?retURL=%2F006Q0000007vZU0
        if(DeveloperName == 'Annual' || DeveloperName == 'Donation' || DeveloperName == 'Inkind' || DeveloperName == 'Purchase'){
            URL += '/apex/PledgesNewStep1?Id=' + Id + '&RecordType=' + RecordType +'&retURL='+ retURL + '&edit=1';
        }else if(DeveloperName == 'Annual_Installment' || DeveloperName == 'Donation_Installment' || DeveloperName == 'Inkind_Installment' || DeveloperName == 'Purchase_Installment'){
            URL += '/apex/GivingEditInstallment?Id=' + Id +'&retURL='+ retURL;
        }else{
            URL += '/' + Id + '/e?retURL=' + retURL;
        }   
        URL += '&nooverride=1';
        return RedirectPage(URL);
    }
    
    PageReference RedirectPage(String URL){         
        PageReference P = new PageReference(URL);
        P.SetRedirect(true);        
        return P;
    }
     static testMethod void EditGiving(){
     
        Account a = new Account(Name = 'Test');
        insert a;
        
        Campaign c = new Campaign();
        c.Name = 'Test';
        c.Channel_Technique__c = 'TELESALES';
        c.Sub_Channel__c = 'INBOUND';
        c.campaign_name__c = 'Annual';
        c.station__c = 'WGBH';
        c.response_mechanism__c = 'Mail';
        Insert c;
        
        Opportunity opp = New Opportunity();
        opp.AccountID = a.Id;
        opp.Name = 'Test';
        opp.gift_kind__c = 'One Payment';
        opp.CloseDate = system.Today().AddDays(15);
        opp.Gift_Date_Time__c = system.now();
        opp.StageName = 'Pledged';
        opp.CampaignID = c.Id;
        opp.campaign_name__c = 'Annual';
        opp.station__c = 'WGBH';
        RecordType rc = [select id from recordtype where developername = 'Annual'];
        opp.recordtypeid = rc.id;
        opp.Gift_Type__c = 'New';
        
        insert opp;
        
              
         ApexPages.currentPage().getParameters().put('id', opp.Id);
          
         SObject o = new Opportunity();
         ApexPages.StandardController sc = new ApexPages.StandardController(o);
         
         EditGiving clsTest = new EditGiving(sc);
         clsTest.RedirectPage('https://cs3.salesforce.com/001/o');               
         clsTest.chooseDestination();         
         

     }

}