kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Time_Date__c</fullName>
        <inlineHelpText>End date and time of the campaign</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Logo__c</fullName>
        <inlineHelpText>Insert the image or the event url by clicking into the image</inlineHelpText>
        <label>Event Image</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Url__c</fullName>
        <label>Event Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Maximum_Capacity__c</fullName>
        <label>Maximum Capacity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Benefit_Discount_Logo__c</fullName>
        <label>Member Benefit Discount Logo</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Start_Time_Date__c</fullName>
        <inlineHelpText>Start Date and Time of the Overall Program</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject_Title__c</fullName>
        <label>Subject/Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_Information__c</fullName>
        <label>Ticket Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ticket_Url__c</fullName>
        <label>Ticket Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Venue_Name__c</fullName>
        <label>Venue Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postalcode__c</fullName>
        <label>Zip/Postalcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/classes/OnlineEventDetail.cls
public class OnlineEventDetail
    {
        public  ID campid = ApexPages.currentPage().getParameters().get('id'); 
        public Campaign  ca{set; get;}
        public List<Attachment> at{get; set;}
        public id attid{get; set;}
        public boolean image{get; set;}
        
        public void EventDetail()
            {
                ca= [SELECT id,description, Event_logo__c, Subject_title__c, Event_Url__c, Start_time_date__c, End_time_date__c,
                     Ticket_Url__c, Ticket_information__c, Venue_name__c, street_address__c, city__c,Maximum_Capacity__c,  
                     State_province__c, Zip_postalcode__c, Phone__c, Email__c, name__c, Member_Benefit_Discount_Logo__c from Campaign where id=:campid ];
    try{
    at=[Select id, name from attachment where parentid=:campid limit 1];
    attid=at[0].id;
    image=true;
    }
    catch(Exception e)
    {
    image=false;
    }
    System.Debug(ca);
    }        
 
    public pagereference print(){           
    PageReference printPage = Page.PrintEvents;
    printPage.getParameters().put('idsToPrint', campid);
    printPage.setRedirect(true);
    return printPage;
    }     
      
          public static testmethod void te()
            {
                List<Campaign> c = [SELECT id, name from Campaign limit 1];
                PageReference pg = Page.OnlineEventDetailPage; 
                Test.setCurrentPage(pg); ApexPages.currentPage().getParameters().put('id', c[0].id);
                OnlineEventDetail d = new OnlineEventDetail();
                d.EventDetail();
                Pagereference p = d.print();
            }
        }