kqed/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Time_Date__c</fullName>
        <inlineHelpText>End date and time of the campaign</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Logo__c</fullName>
        <inlineHelpText>Insert the image or the event url by clicking into the image</inlineHelpText>
        <label>Event Image</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Maximum_Capacity__c</fullName>
        <label>Maximum Capacity</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Start_Time_Date__c</fullName>
        <inlineHelpText>Start Date and Time of the Overall Program</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject_Title__c</fullName>
        <label>Subject/Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Name__c</fullName>
        <label>Venue Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postalcode__c</fullName>
        <label>Zip/Postalcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed_dev4/src/classes/PrintEvents.cls
public class PrintEvents {

public List<Campaign> lc{get; set;}
public String idsToPrint {get; set;}
public List<Attachment> at{get; set;}
    public id attid{get; set;}
    public boolean image{get; set;}
        

public void Print(){
        this.idsToPrint = ApexPages.currentPage().getParameters().get('idsToPrint');
        
        if(this.idsToPrint !=null && this.idsToPrint.length() > 0) {
        List<String> s = idsToPrint.split(':');
        
        for(integer i=0;i<=s.size();i++)
        {
            System.debug(s);
        }
        for(String st : s){
        lc = [SELECT id, Name__c, Subject_Title__c, Venue_Name__c, Street_Address__c, City__c, State_Province__c, Zip_Postalcode__c, Event_Logo__c, 
             Maximum_Capacity__c, Start_time_date__c, End_time_date__c, Phone__c, Email__c from Campaign where id =:st];
try{

    at=[Select id, name from attachment where parentid=:st limit 1];
attid=at[0].id;
image=true;
}catch(Exception e){
image=false;
}


}
        }     
    }
    
public static testmethod void te(){

    List<Campaign> lc = [SELECT id, name from Campaign limit 5];
    List<String> tempSelectedIds = new List<String>();
    
    String idToPrint ;
    for(Campaign c:lc){
    tempSelectedIds.add(c.Id);
    }
    
    for(Integer mbIndex = 0; mbIndex < tempSelectedIds.size(); mbIndex ++) {
    idToPrint =idToPrint+':'+ tempSelectedIds[mbIndex] ;
    }
    
    PageReference pg = Page.PrintEvents;
    Test.setCurrentPage(pg);
    ApexPages.currentPage().getParameters().put('idsToPrint', idToPrint);
    PrintEvents p = new PrintEvents();
    p.print();
    }
}