kqed/src/objects/candidate__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desired_Salary__c</fullName>
        <label>Desired Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Recent_Salary__c</fullName>
        <label>Recent Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Street_Address1__c</fullName>
        <label>Street Address1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Job_Application__c.object
<CustomObject>
    <description>This includes the Job Application details such as resume, application information and review status etc.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <inlineHelpText>HR and Sys Admin view of Candidate.</inlineHelpText>
        <label>Candidate</label>
        <referenceTo>candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>R00ND0000001pXIZMA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/classes/extCandidate.cls
public without sharing class extCandidate 
{
    public candidate__c c {get;set;}
    public Integer intApps {get;set;}
    
    
    public extCandidate(ApexPages.StandardController controller) 
    {
        
        String idCand = Apexpages.currentpage().getParameters().get('cand');
        Map<String, Schema.SObjectField> FieldMap = Schema.SObjectType.candidate__c.fields.getMap();
        Set<String> setFields = FieldMap.keySet();
            
        String strSoQL = 'Select Id';
        for (String fname : setFields) 
        {
            if (fname != 'Id')
            {
                strSoQL += ', ' +fname;
            }
        }
        
        if (idCand != null &&idCand != '')
        {
            //Get all of the Candidate fields and types
            
            strSoQL += ' from candidate__c where Id = \'' +idCand +'\'';
            System.debug('ABOUT TO QUERY ' +strSoQL);
            c = Database.query(strSoQL);
            
            intApps = [Select count() from Job_Application__c where Candidate__c =: idCand];
        } 
        else 
        {
            c = new candidate__c();
        }
        
    }
    
    public static testMethod void testExtCandidateWithCandidate()
    {
        
        Test.startTest();
        Candidate__c testCan       = new Candidate__c();
        //initialize testCan
        testCan.First_Name__c      = 'William';
        testCan.Last_Name__c       = 'Shakespeare';
        testCan.Street_Address1__c = '55 Riverside Drive';
        testCan.City__c            = 'Stratford on Avon';
        testCan.Email__c           = 'WillieShakes521@gmail.com';
        testCan.Zip_Postal_Code__c = '12345';
        testCan.Phone__c           = '6173003434';
        testCan.Recent_Salary__c   = 34000.0;
        testCan.Desired_Salary__c  = 1000.0;
        //insert
        insert testCan;
        extCandidate ext = new extCandidate(new ApexPages.StandardController(testCan));
        
        Test.stopTest();
    }
    
    public static testMethod void testExtCandidateWithoutCandidate()
    {
        Test.startTest();
        Candidate__c testCan       = new Candidate__c();
        extCandidate ext = new extCandidate(new ApexPages.StandardController(testCan));
        Test.stopTest();
    }
    

}