kqed/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <label>Merchant ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <externalId>true</externalId>
        <label>Merchant ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <externalId>true</externalId>
        <label>Merchant Key</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <label>SFDC GIVING NUMBER</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>CC_Alias__c</fullName>
        <label>CC Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Giving__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RFP_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RFP Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Refund_Date__c</fullName>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Refund_Method__c</fullName>
        <label>Refund Method</label>
        <picklist>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_Status_Formula__c</fullName>
        <formula>TEXT(Refund_Status__c)</formula>
        <label>Refund Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_Status__c</fullName>
        <label>Refund Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent To Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Refund #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/classes/Batch_Transactions.cls
// Insert refund item to transaction batch from refund__c object

global class Batch_Transactions {
    Public Static void Batch_Transactions() {
       BatchExecBatch_Transactions reassign = new BatchExecBatch_Transactions ('select CC_Alias__c,Giving__c,Refund_Amount__c,Refund_Date__c,Refund_Method__c,Refund_Status__c,Refund_Status_Formula__c,RFP_Submitted__c,Giving__r.SFDC_GIVING_NUMBER__c,CC_Alias__r.GUID__c,CC_Alias__r.Merchant_Account__r.Merchant_ID__c,CC_Alias__r.Merchant_Account__r.Merchant_Key__c from Refund__c where Status__c = \'PROCESS\' And Refund_Method__c= \'Charge Card\'');
       //BatchExecRefund_Batch reassign = new BatchExecRefund_Batch ('select CC_Alias__c,Giving__c,Refund_Amount__c,Refund_Date__c,Refund_Method__c,Refund_Status__c,Refund_Status_Formula__c,RFP_Submitted__c,Giving__r.SFDC_GIVING_NUMBER__c,CC_Alias__r.GUID__c,CC_Alias__r.Merchant_Account__r.Merchant_ID__c,CC_Alias__r.Merchant_Account__r.Merchant_Key__c from Refund__c where ID=\'a15Q0000000aizP\'');
        
        ID batchprocessid = Database.executeBatch(reassign,200);
    }
}