kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <inlineHelpText>See Contact Status with real values that are mapped from these TA values</inlineHelpText>
        <label>TA Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/classes/BatchExecUpdateContactStatus.cls
global class BatchExecUpdateContactStatus implements Database.Batchable<sObject> {
    global final String Query;
    global BatchExecUpdateContactStatus (String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchUpdateContactStatus(scope);
    }    
    void DoBatchUpdateContactStatus(List<sObject> scope) {
        List<Contact> lstContact = (List<Contact>) scope;
        
        for(Contact c: lstContact) {
            if(c.STS__c == 'A'){
                c.Contact_Status__c = 'Active';
            }
        }
        Update lstContact;
    }    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }        
}