kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PreferredPhone__c</fullName>
        <label>Preferred Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WorkEmail__c</fullName>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>Flag_Review_Reason__c</fullName>
        <label>Flag Review Reason</label>
        <picklist>
            <picklistValues>
                <fullName>MORE THAN 1 MATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC PLEDGE ID or PLEDGE NUMBER EXIST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS AMT equal to PAYMENT AMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT DATE ON PLEDGE WITH PREMIUMS &lt; 1 YEAR FROM CURRENT DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; SUM OF PRODUCTS MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; PRODUCT MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT TYPE IS NULL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_for_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag for Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_CITY__c</fullName>
        <description>City of preferred address. Maps to UL_ADDRESSES.CITY</description>
        <label>PB5_CITY</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_EMAIL_ADDRESS_1__c</fullName>
        <description>PREFERRED EMAIL ADDRESS. MAPS TO: UL_EMAILS.EMAIL_ADDRESS</description>
        <label>PB5_EMAIL_ADDRESS_1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PB5_EMAIL_ADDRESS_2__c</fullName>
        <description>The email address of the second name on the account</description>
        <label>PB5_EMAIL_ADDRESS_2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME_2__c</fullName>
        <description>The first name of the second named account in the file</description>
        <label>PB5_FIRST_NAME_2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME__c</fullName>
        <description>First name of household or contact or organziation. Maps to: UL_NAMES.FIRST_NAME</description>
        <label>PB5_FIRST_NAME</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME_2__c</fullName>
        <description>The last name of the second person in the file</description>
        <label>PB5_LAST_NAME_2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME__c</fullName>
        <description>Last name of household, contact, organizaiton. Maps to: UL_NAMES.LAST_NAME</description>
        <label>PB5_LAST_NAME</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_MIDDLE_NAME_2__c</fullName>
        <description>The middle name of the second named person in the file</description>
        <label>PB5_MIDDLE_NAME_2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_MIDDLE_NAME__c</fullName>
        <description>Middle name of household, contact, organizaiton. Maps to: UL_NAMES.MIDDLE_NAME</description>
        <label>PB5_MIDDLE_NAME</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_NO_PHONE_PREFERRED__c</fullName>
        <label>PB5_NO_PHONE_PREFERRED</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_CITY__c</fullName>
        <label>PB5_SHIP_TO_CITY</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STATE__c</fullName>
        <label>PB5_SHIP_TO_STATE</label>
        <picklist>
            <picklistValues>
                <fullName>GET PICK LIST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STREET_1__c</fullName>
        <label>PB5_SHIP_TO_STREET_1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_ZIP_CODE__c</fullName>
        <label>PB5_SHIP_TO_ZIP_CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_STATE__c</fullName>
        <description>State of preferred Address</description>
        <label>PB5_STATE</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_STREET_1__c</fullName>
        <description>Name of street in preferred address. Maps to: UL_ADDRESSES.STEET_NAME</description>
        <label>PB5_STREET_1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SUFFIX_2__c</fullName>
        <label>PB5_SUFFIX_2</label>
        <picklist>
            <picklistValues>
                <fullName>Jr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ph.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Esq.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D.M.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D.D.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R.N.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_SUFFIX__c</fullName>
        <description>Suffix of name on household, contact, org. Maps to UL_NAMES.SUFFIX</description>
        <label>PB5_SUFFIX</label>
        <picklist>
            <picklistValues>
                <fullName>Jr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ph.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Esq.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D.M.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D.D.S.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R.N.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_Stage__c</fullName>
        <label>PB5 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_TELEPHONE_TYPE_1__c</fullName>
        <description>PREFERRED PHONE TYPE. MAPS TO: UL_TELEPHONE.TELEPHONE_TYPE</description>
        <label>PB5_TELEPHONE_TYPE_1</label>
        <picklist>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_ZIP_CODE__c</fullName>
        <description>zip code of preferred address. Maps to: UL_ADDRESSES.ZIP_CODE</description>
        <label>PB5_ZIP_CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Duplicate_ID__c</fullName>
        <label>SF Duplicate ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/UploadRecordMatchingContact_Old.cls
public class UploadRecordMatchingContact_Old{
    public static void ProcessContact(WGBH_PB5_UPLOAD__c PB5){
        List<sObject> lstTarget;
        UploadRecordMatchingProcess__c csMatchingFields = UploadRecordMatchingProcess__c.getOrgDefaults();
        system.debug('########################' + csMatchingFields);
        String MatchingCriteria;
        if(csMatchingFields != null)
            MatchingCriteria = csMatchingFields.Matching_Criteria__c;
        else
            MatchingCriteria = 'LastName=PB5_LAST_NAME__c,Email=PB5_EMAIL_ADDRESS_1__c;FirstName=PB5_FIRST_NAME__c,LastName=PB5_LAST_NAME__c,MailingStreet=PB5_SHIP_TO_STREET_1__c,MailingCity=PB5_SHIP_TO_CITY__c,MailingState=PB5_SHIP_TO_STATE__c,MailingPostalCode=PB5_SHIP_TO_ZIP_CODE__c';
        lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        ProcessContact(PB5, lstTarget, '1');
        if(csMatchingFields != null)
            MatchingCriteria = csMatchingFields.Contact_Matching_Criteria_2__c;
        else
            MatchingCriteria = 'LastName=PB5_LAST_NAME_2__c,Email=PB5_EMAIL_ADDRESS_2__c;FirstName=PB5_FIRST_NAME_2__c,LastName=PB5_LAST_NAME_2__c,MailingStreet=PB5_STREET_1__c,MailingCity=PB5_CITY__c,MailingState=PB5_STATE__c,MailingPostalCode=PB5_ZIP_CODE__c';
        lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        ProcessContact(PB5, lstTarget, '1');
    }
    public static void ProcessContact(WGBH_PB5_UPLOAD__c PB5,List<sObject> lstTarget, String flag){
        //List<sObject> lstTarget = getMatchingRows(PB5,'Contact');
        if(lstTarget.size()==0){//Contact Info not exist -> Create new contact
            //insert Contact
            if(InsertContact(PB5, flag)==true){
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'B';
            }
            else{
                PB5.Flag_for_Review__c = true;
                PB5.PB5_Stage__c = 'A';
            }
        }
        else if(lstTarget.size()==1){//Contact Info Exists -> Apend data to existing contact
            //update Contact
            if(UpdateContact((Contact) lstTarget[0], PB5, flag)==true){
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'B';
            }
            else{
                PB5.Flag_for_Review__c = true;
                PB5.PB5_Stage__c = 'A';
            }
        }
        else if(lstTarget.size()>1){//Multiple Contact found
            //multiple matches found
            String duplicateId='';
            for(sObject t:lstTarget){
                if(duplicateId.length()==0)
                    duplicateId = String.valueOf(t.get('Id'));// + '#' + String.valueOf(t.get('name'));
                else
                    duplicateId += +', ' + String.valueOf(t.get('Id'));// + '#' + String.valueOf(t.get('name'));                        
            }
            PB5.SF_Duplicate_ID__c = duplicateId;
            PB5.Flag_for_Review__c = true;
            PB5.Flag_Review_Reason__c = 'MORE THAN 1 MATCH';
        }
        Update PB5;    
    }
    
    public static boolean InsertContact(WGBH_PB5_UPLOAD__c pb, String flag){
        boolean blnSuccess=false;
        Contact objContact = new Contact();
        objContact = mapContactField(pb, flag);
        try{
            insert objContact;
            if(objContact.Id != null && String.valueOf(objContact.Id).length()>0)
                blnSuccess = true;
            else
                blnSuccess = false;
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    public static boolean UpdateContact(Contact objContact, WGBH_PB5_UPLOAD__c pb, String flag){
        boolean blnSuccess=false;        
        objContact = mapContactField(pb, flag);
        try{
            update objContact;
            if(objContact.Id != null && String.valueOf(objContact.Id).length()>0)
                blnSuccess = true;
            else
                blnSuccess = false;
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    
    public static Contact mapContactField(WGBH_PB5_UPLOAD__c pb, String flag){
        Contact objContact = new Contact();
        if(flag == '1'){
            objContact.FirstName = pb.PB5_FIRST_NAME__c;//PB5_FIRST_NAME_2__c
            objContact.LastName = pb.PB5_LAST_NAME__c;//PB5_LAST_NAME_2__c
            //objContact.MiddleName = pb.PB5_MIDDLE_NAME__c;//PB5_MIDDLE_NAME_2__c
            objContact.Email = pb.PB5_EMAIL_ADDRESS_1__c;//PB5_EMAIL_ADDRESS_2__c
            //objContact.DoNotCall = pb.PB5_NO_PHONE_PREFERRED__c;
            //objContact.WorkEmail__c = pb.PB5_EMAIL_ADDRESS_2__c;
            objContact.Salutation = pb.PB5_SUFFIX__c;//PB5_SUFFIX_2__c
            objContact.PreferredPhone__c = pb.PB5_TELEPHONE_TYPE_1__c;//PB5_TELEPHONE_TYPE_2__c
            objContact.Phone = pb.PB5_TELEPHONE_NUMBER_1__c;//PB5_TELEPHONE_NUMBER_2__c
            //objContact.OtherPhone = pb.PB5_TELEPHONE_NUMBER_2__c;
            objContact.MailingStreet = pb.PB5_SHIP_TO_STREET_1__c;//PB5_STREET_1__c
            objContact.MailingCity = pb.PB5_SHIP_TO_CITY__c;//PB5_CITY__c
            objContact.MailingState = pb.PB5_SHIP_TO_STATE__c;//PB5_STATE__c
            objContact.MailingPostalCode = pb.PB5_SHIP_TO_ZIP_CODE__c;//PB5_ZIP_CODE__c
        }else{
            objContact.FirstName = pb.PB5_FIRST_NAME_2__c;
            objContact.LastName = pb.PB5_LAST_NAME_2__c;
            //objContact.MiddleName = pb.PB5_MIDDLE_NAME__c;//PB5_MIDDLE_NAME_2__c;
            objContact.Email = pb.PB5_EMAIL_ADDRESS_2__c;
            //objContact.DoNotCall = pb.PB5_NO_PHONE_PREFERRED__c;
            //objContact.WorkEmail__c = pb.PB5_EMAIL_ADDRESS_2__c;
            objContact.Salutation = pb.PB5_SUFFIX_2__c;
            objContact.PreferredPhone__c = pb.PB5_TELEPHONE_TYPE_2__c;
            objContact.Phone = pb.PB5_TELEPHONE_NUMBER_2__c;
            //objContact.OtherPhone = pb.PB5_TELEPHONE_NUMBER_2__c;
            objContact.MailingStreet = pb.PB5_STREET_1__c;
            objContact.MailingCity = pb.PB5_CITY__c;
            objContact.MailingState = pb.PB5_STATE__c;
            objContact.MailingPostalCode = pb.PB5_ZIP_CODE__c;        
        }            
        return objContact;
    }
}