kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STS__c</fullName>
        <description>TA Status</description>
        <inlineHelpText>See Contact Status with real values that are mapped from these TA values</inlineHelpText>
        <label>TA Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <externalId>true</externalId>
        <label>TA Contact Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

kqed/src/classes/BatchExecUpdateContactStatusCall.cls
global class BatchExecUpdateContactStatusCall {
    Public static void BatchExecUpdateContactStatusCall () {
        ID batchprocessid;
        BatchExecUpdateContactStatus status;
        
        status = new BatchExecUpdateContactStatus('Select ID,STS__c,Contact_Status__c from Contact where TaContactId__c != null && TaContactId__c != \'\'');
        batchprocessid = Database.executeBatch(status,200);
    }
}