kqed/src/objects/Country__c.object
<CustomObject>
    <description>Country objects</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gift_Date_Time__c</fullName>
        <inlineHelpText>To be populated by vendor file procesing. this field will not be available for users to populate information.</inlineHelpText>
        <label>Gift Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Oppty_Related_Contact__c</fullName>
        <description>The contact associated to the opportunity/ask</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposal/Pledge</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

KQED -/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Status__c</fullName>
        <label>Fulfillment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superceded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity__c</fullName>
        <label>Shipped Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unshipped_Quantity__c</fullName>
        <formula>IF( ISPICKVAL( PricebookEntry.Product2.Inventory_Type__c, &quot;Standard Inventory&quot;), 
  Quantity -  Shipped_Quantity__c,
  0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unshipped Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

kqed/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Units_Available__c</fullName>
        <formula>Units_Ordered__c  -  Units_Sold_calc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Units available to sell. # Ordered - # Sold</inlineHelpText>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_On_Hand__c</fullName>
        <formula>Units_Received_calc__c  -  Units_Shipped_calc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Units physically present in inventory. # Received – # Shipped</inlineHelpText>
        <label>Units On Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

kqed/src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <picklist>
            <picklistValues>
                <fullName>FedEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Shipment_Line__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Premium/Benefit</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Shipment Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/CreateShipmentController.cls
public with sharing class CreateShipmentController {
    
    private final Id oppid;
    private set<id> setOppIds = new set<id>();
    public String selected_ShipIds				{get;set;}
    
    public Integer queryRowLimit				{get;set;}
    public Shipment__c dummyShipment			{get;set;}
    public list<ShipmentWrapper> shipmentWPs 	{get;set;}        	
            
    public CreateShipmentController() {
    	system.debug('\n ### in CreateShipmentController constructor ');    	
    	if (Apexpages.currentPage().getParameters().containsKey('oppId')) {
    		oppid = Apexpages.currentPage().getParameters().get('oppId');
    		setOppIds.add(oppid);
    	} else if (Apexpages.currentPage().getParameters().containsKey('oppIds')) {
    		String selected_OppIds = Apexpages.currentPage().getParameters().get('oppIds');
    		system.debug('\n ### selected_OppIds ' + selected_OppIds);
    		for (String oppId : selected_OppIds.split(',')) {
    			setOppIds.add(oppId);
    		}
    	}
        init();
    }
    
    public void init() {
    	queryRowLimit = 200;
		shipmentWPs = new list<ShipmentWrapper>();
    	dummyShipment = new Shipment__c(Shipping_Date__c=Date.today());    	    	
    }
    
    public void initShipment() {
		try {
			shipmentWPs = new list<ShipmentWrapper>();
	        createShipmentWPs();
			
			if (shipmentWPs.size() == queryRowLimit)
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Only the first ' + queryRowLimit + ' Shipments are displayed.'));
			
        } catch (Exception ex) {
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
    	}
    	
    	return ;
    }
    
    private void createShipmentWPs() {
    	
    	list<OpportunityLineItem> oppLineItems = GetOppLineItems();
        if(oppLineItems == null || oppLineItems.isEmpty()) {
           	//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'No unshipped Giving Premiums/Benefits found for the selected Orders.'));	           	
           	return;
        }
    	
    	map<String, ShipmentWrapper> mapShipmentWP = new map<String, ShipmentWrapper>();
    	ShipmentWrapper shipWP;
    	String shipmentKey;
    	
    	for(OpportunityLineItem oli : oppLineItems) {
			shipmentKey = getShipmentKey(oli);
    		    		
    		if(!mapShipmentWP.containsKey(shipmentKey))
    			shipWP = new ShipmentWrapper(oli.Opportunity);
    		else
    			shipWP = mapShipmentWP.get(shipmentKey);
    		
    		shipWP.ShipmentLineWPs.add(new ShipmentLineWrapper(oli));
    		mapShipmentWP.put(shipmentKey, shipWP);
    	}
    	
    	shipmentWPs = mapShipmentWP.values();
    	system.debug('\n ### shipmentWPs.size ' + shipmentWPs.size() + ' => ' + shipmentWPs);
	}
	
	private String getShipmentKey(OpportunityLineItem oli) {
		String shipmentKey = util.assignIfNotEmpty(oli.OpportunityId,'') + util.assignIfNotEmpty(oli.Street__c,'') + util.assignIfNotEmpty(oli.City__c,'') + util.assignIfNotEmpty(oli.State__c,'') + util.assignIfNotEmpty(oli.Country__c,'');
		system.debug('\n ### shipmentKey ' + shipmentKey); 
		return shipmentKey;
	}
    
 	private list<OpportunityLineItem> GetOppLineItems() {
     	
     	//TO DO - remove unused fields from the Select stmt.
     	
    	system.debug('\n ### oppId: '+ oppid);
    	system.debug('\n ### setOppIds ' + setOppIds); 
     	
 	    list<OpportunityLineItem> oppLineItems = [Select oli.Unshipped_Quantity__c, oli.Shipped_Quantity__c, oli.Quantity,													  
													oli.OpportunityId, oli.Id, oli.Fulfillment_Status__c,  													
													oli.Street__c, oli.City__c, oli.State__c, oli.Postal_Code__c, oli.Country__c,
													oli.PricebookEntryId, oli.PricebookEntry.Product2Id, oli.PricebookEntry.Product2.Name, 
													PricebookEntry.Product2.Units_Available__c, PricebookEntry.Product2.Units_On_Hand__c,
													Opportunity.Id, Opportunity.Name, Opportunity.Gift_Date_Time__c, Opportunity.Oppty_Related_Contact__c, 
													Opportunity.AccountID, Opportunity.Account.Name
												  From  OpportunityLineItem oli
												  where Quantity > 0
												  and   PricebookEntry.Product2.Units_Available__c > 0
												  and   (Unshipped_Quantity__c > 0)		//Unshipped_Quantity__c = null OR 
												  //and   (oli.OpportunityId = : oppId OR oli.PricebookEntry.Product2Id in : setProductIds)
												  and   (oli.OpportunityId in : setOppIds)
												  order by CreatedDate
												  limit 200];
		
		system.debug('\n ### oppLineItems.size ' + oppLineItems.size() + ' => ' + oppLineItems);
		
		return oppLineItems;
 	}
    
    public PageReference CreateShipment() {
    	try {
	    	
    		boolean atLeastOneSelected = false;
    		decimal productsToShip;
    		decimal unitsAvail;
    		decimal unshippedQty;
    		map<Id, decimal> mapProductsToShip = new map<Id, decimal>();    		
    		list<Shipment__c> shipments_To_Upsert = new list<Shipment__c>();
    		list<Shipment_Line__c> shipmentLines_To_Upsert = new list<Shipment_Line__c>();
    		list<OpportunityLineItem> olis_To_Update = new list<OpportunityLineItem>();
    		
    		if (dummyShipment.Shipping_Date__c == null) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Shipping Date must be entered.'));
				return null;
    		}
    		
    		if (dummyShipment.Carrier__c == null) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Carrier must be selected.'));
				return null;
    		}

	    	for(ShipmentWrapper sp : shipmentWPs) {
    			
    			sp.shipment.Shipping_Date__c = dummyShipment.Shipping_Date__c;
    			sp.shipment.Carrier__c = dummyShipment.Carrier__c;
	    			    		
	    		for (ShipmentLineWrapper spl : sp.shipmentLineWPs) {
		    		if (spl.checked == true) {
		    			atLeastOneSelected = true;		    			
		    			
		    			// optionally these can be set when creating the shipment object but don't have time to change the Shipment Wrapper constructor to accept oli instead of opp.
		    			sp.checked = true;

		    			sp.shipment.Street_Address__c = spl.oli.Street__c;
		    			sp.shipment.City__c = spl.oli.City__c;
		    			sp.shipment.State__c = spl.oli.State__c;
		    			sp.shipment.Postal_Code__c = spl.oli.Postal_Code__c;
		    			sp.shipment.Country__c = spl.oli.Country__c;	    		
		    					    					    					    			
			    		if (spl.shipmentLine.Quantity__c > 0) {
			    			productsToShip = spl.shipmentLine.Quantity__c;
			    			if (mapProductsToShip.containsKey(spl.shipmentLine.Product__c)) {
								productsToShip = productsToShip + mapProductsToShip.get(spl.shipmentLine.Product__c);
			    			}
			    			mapProductsToShip.put(spl.shipmentLine.Product__c, productsToShip);
			    			
			    			unitsAvail = Util.assignIfNotNull(spl.oli.PricebookEntry.Product2.Units_Available__c, 0);
			    			system.debug('\n ### units available ' + unitsAvail + ' for product ' + spl.oli.PricebookEntry.Product2.Name + ' productsToShip ' + productsToShip);
			    			if (productsToShip > unitsAvail) {
				    			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'The shipments below include ' + productsToShip + ' units of the \'' + spl.oli.PricebookEntry.Product2.Name + ' \' and only ' + unitsAvail + ' is available.'));
				    			return null;
			    			}
			    			
			    			unshippedQty = Util.assignIfNotNull(spl.oli.Unshipped_Quantity__c, 0);
			    			system.debug('\n ### unshipped quantity ' + unshippedQty + ' for product ' + spl.oli.PricebookEntry.Product2.Name + ' shipment quantity ' + spl.shipmentLine.Quantity__c);
			    			if (spl.shipmentLine.Quantity__c > unshippedQty) {
				    			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Ship Qty must be less than or equal to unshipped quantity for Premium/Benefit \'' + spl.oli.PricebookEntry.Product2.Name + '\'.'));
				    			return null;			    				
			    			}
							
			    		} else {
			    			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Ship Qty must be greater than zero for selected Premium/Benefit.'));
			    			return null;
			    		}			    		
		    		}
	    		}
	    		
	    		// if necessary, allow upserts by removing IF condition below.
	    		if (sp.shipment.Id == null && sp.checked) shipments_To_Upsert.add(sp.shipment);
	    	}
	    		    	
	    	system.debug('\n ### shipments_To_Upsert.size ' + shipments_To_Upsert.size() + ' => ' + shipments_To_Upsert);
	    	if(!shipments_To_Upsert.isEmpty()) {
	    		upsert shipments_To_Upsert;
	    		
	    		//set<Id> shipmentIds = new set<Id>();
	    		selected_ShipIds = '';
		    	for(ShipmentWrapper sp : shipmentWPs) {
		    		for (ShipmentLineWrapper spl : sp.shipmentLineWPs) {
		    			if (spl.checked == true) {		    				
		    				system.debug('\n ### sp.shipment.Id ' + sp.shipment.Id);
		    				//shipmentIds.add(sp.shipment.Id);
		    				if (selected_ShipIds.indexOf(sp.shipment.Id) == -1) {
								if (selected_ShipIds != '') selected_ShipIds += ',';						    					
		    					selected_ShipIds += sp.shipment.Id;
		    				}
		    				if (spl.shipmentLine.Shipment__c == null) spl.shipmentLine.Shipment__c = sp.shipment.Id;
		    				shipmentLines_To_Upsert.add(spl.shipmentLine);
		    				
		    				//spl.oli.Unshipped_Quantity__c = Util.assignIfNotNull(spl.oli.Unshipped_Quantity__c, 0) - spl.shipmentLine.Quantity__c;
		    				//spl.oli.Shipped_Quantity__c = Util.assignIfNotNull(spl.oli.Shipped_Quantity__c, 0) + spl.shipmentLine.Quantity__c;
		    				olis_To_Update.add(spl.oli);
		    			}
		    		}
		    	}
	    		
	    		system.debug('\n ### shipmentLines_To_Upsert.size ' + shipmentLines_To_Upsert.size() + ' => ' + shipmentLines_To_Upsert);
	    		if (!shipmentLines_To_Upsert.isEmpty()) {
	    			upsert shipmentLines_To_Upsert;
	    		}

	    		system.debug('\n ### olis_To_Update.size ' + olis_To_Update.size() + ' => ' + olis_To_Update);
	    		if (!olis_To_Update.isEmpty()) {
	    			update olis_To_Update;
	    		}
	    		
	    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, 'Shipment(s) created.'));
	    		
	    		//shipments = [select Id, Name, Carrier__c, Opportunity__c, Organization__c, Shipping_Contact__c, City__c, State__c from Shipment__c where id in :shipmentIds];
	    		
	    		return displayShipment();
	    		
	        } else if (atLeastOneSelected == true) {
	        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Shipment(s) have been recently created for the selected Premiums/Benefits.'));
	        } else {
	        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'At least one Premium/Benefit must be selected for shipment.'));
	        }
    	} catch (Exception ex) {
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
    	}
        
    	return null;
    }
    
    public PageReference displayShipment() {

    	PageReference pg = new PageReference('/apex/DisplayShipment?shipIds='+selected_ShipIds);
		pg.setRedirect(true);
    	System.debug('\n ### pg '+ pg);	
    	return pg;
    }
    
    public PageReference Cancel() {
        init();
        return null;
    }
    
    public PageReference cancelShipment() {
    	init();
    	    	
    	PageReference pg;
	    
    	if (oppId != null)
    		pg = new PageReference('/'+oppId);
    	else
    		pg = new PageReference('/apex/CreateShipmentOrder');

		pg.setRedirect(true);
    	System.debug('\n ### pg '+ pg);	
    	return pg;
    }	    
}