kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <label>SFDC GIVING NUMBER</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>The id of the pledge</description>
        <label>Opportunity_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pledge_Number__c</fullName>
        <description>The pledge number from the pledge</description>
        <label>Pledge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <label>TRANSACTION_BATCH</label>
    <nameField>
        <label>TRANSACTION_BATCH Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TRANSACTION_BATCHS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/BatchExecTransactionInsert.cls
global class BatchExecTransactionInsert implements Database.Batchable<sObject> {
    global final String Query;
 
    global BatchExecTransactionInsert(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchTransactionbatchInsert(scope);
    }
    
    void DoBatchTransactionbatchInsert(List<sObject> scope) {
        List<Transaction_Batch__c> lstbatch = new List<Transaction_Batch__c>();
        
        Transaction_Batch__c TB;
        
        for(sObject s : scope) {
            Opportunity ObjPledge = (Opportunity)s;
            TB = new Transaction_Batch__c();
            
            TB.Process_date__c = ObjPledge.Payment_Date__c;
            TB.Payment_Amount__c = ObjPledge.Payment_Amount__c;
            TB.Pledge_Number__c = ObjPledge.SFDC_GIVING_NUMBER__c;
            TB.Opportunity_Id__c = ObjPledge.Id;
            
            lstbatch.add(TB);
        }
        
        if(lstbatch != null && lstbatch.size()>0) 
        {
            Insert lstbatch;
        }

    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

    /*static testMethod void TestBatchExecTransactionInsert() {
       Test.startTest();
        Lead l = new Lead();
        l.FirstName = 'TestFirstName';
        l.LastName = 'TestLastName';
        l.Line_of_Business__c = 'Life';
        l.Company = 'Test';
        l.Email = 'test@test.com';
        insert l;
        
        Lead l1 = new Lead();
        l1.FirstName = 'TestFirstName';
        l1.LastName = 'TestLastName';
        l1.Line_of_Business__c = 'Life';
        l1.Company = 'Test';
        l1.Email = 'test@test.com';
        insert l1;
        
        ID batchprocessid;
        BatchExecLeadConvertDistribute reassign;
        reassign = new BatchExecLeadConvertDistribute ('Select ID from Lead limit 200',false);
        batchprocessid = Database.executeBatch(reassign);   
        Test.StopTest();     
        
    }     */
}