kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Oppty_Related_Contact__c</fullName>
        <description>The contact associated to the opportunity/ask</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposal/Pledge</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

kqed/src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <picklist>
            <picklistValues>
                <fullName>FedEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/classes/ShipmentWrapper.cls
public with sharing class ShipmentWrapper {
		
	public Boolean checked 		{ get; set; }
	public Integer selectedItemsCount { get; set; }
	public Opportunity opp 		{ get; set; }
	public Shipment__c shipment { get; set; }		
	public list<ShipmentLineWrapper> shipmentLineWPs { get; set; }
	
	public ShipmentWrapper(shipment__c sp) {
		init();
		shipment = sp;
		opp = new Opportunity();
	}
	
	public ShipmentWrapper(Opportunity op) {
		init();					
		this.opp = op;
    	shipment = new Shipment__c(Opportunity__c=opp.Id, Shipping_Contact__c=opp.Oppty_Related_Contact__c, Organization__c=opp.AccountID, Shipping_Date__c=null, Carrier__c=null);	//Date.Today()		
		//shipment.Carrier__c = 'FedEx';
	}
	
    private void init() {
    	selectedItemsCount = 0;
		checked = false;
		shipmentLineWPs = new list<ShipmentLineWrapper>();
    }
}