kqed/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Code__c</fullName>
        <label>Activity Code</label>
        <referenceTo>WGBH_AUAC__c</referenceTo>
        <relationshipLabel>Job Requisitions (Activity Code)</relationshipLabel>
        <relationshipName>Job_Requisitions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>AEEF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NABET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billing_Accounting_Unit__c</fullName>
        <label>Accounting Unit</label>
        <referenceTo>WGBH_AUAC__c</referenceTo>
        <relationshipLabel>Job Requisitions (Billing Accounting Unit)</relationshipLabel>
        <relationshipName>Job_Requisitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Activity_Code__c</fullName>
        <label>Activity Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Email__c</fullName>
        <defaultValue>$User.Email</defaultValue>
        <label>Created By Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Job_Level__c</fullName>
        <label>Job Level</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <description>Max. pay allowed for the position.</description>
        <inlineHelpText>Max. pay allowed for the position.</inlineHelpText>
        <label>Maximum Budgeted Salary</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <description>Min. Pay for the position.</description>
        <inlineHelpText>Min. Pay for the position.</inlineHelpText>
        <label>Minimum Budgeted Salary</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <label>Position Title</label>
        <referenceTo>WGBH_Job_Titles__c</referenceTo>
        <relationshipLabel>Job Requisitions</relationshipLabel>
        <relationshipName>Job_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job Requisition</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/WGBH_AUAC__c.object
<CustomObject>
    <description>List of accounting units with activity codes (General Ledge codes)</description>
    <fields>
        <fullName>AUAC__c</fullName>
        <description>Combination of the accounting unit and activity which makes the record unique</description>
        <externalId>true</externalId>
        <label>AUAC</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of AU AC Combo</description>
        <label>Description</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Teh date the AU AC Combo ceases to be active</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the AU AC Combo becomes active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>AUAC</label>
    <nameField>
        <label>AUAC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AUAC&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/WGBH_Job_Titles__c.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>The Union Affiliation for the position</description>
        <label>Affiliation</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>The JOB CODE</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The Job Title</description>
        <label>Description</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEO_Category__c</fullName>
        <description>The Decoded EEO Category fo the position</description>
        <label>EEO Category</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the job title active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Exempt__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the position is exempt from overtime</description>
        <label>Is Exempt</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Title</label>
    <nameField>
        <label>Job Titles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/classes/update_job_level.cls
public class update_job_level{
@future

    public static void met_new(List<String> pos) //added by LRT
    {
        List<Position__c> lstPos = [Select id, position_title__c, job_level__c,billing_activity_code__c, billing_accounting_unit__c  from Position__c where id in:pos];
        List<ID> lstWGBHid = new List<ID>(); 
        List<ID> lstPositionTitleId = new List<ID>();
        Map<ID,WGBH_AUAC__c> MapW_auac = new Map<ID,WGBH_AUAC__c>();
        Map<ID,wgbh_job_titles__c> Mapwht = new Map<ID,wgbh_job_titles__c>();
        
        if(lstPos <> null && lstPos.size()>0){
            for(Position__c p:lstPos){
                if(p.billing_accounting_unit__c!=null){
                    lstWGBHid.add(p.billing_accounting_unit__c);
                }
                if(p.position_title__c!=null){
                    lstPositionTitleId.add(p.position_title__c);
                }
            }        
            if(lstWGBHid <> null && lstWGBHid.size()>0){
                MapW_auac = new Map<Id,WGBH_AUAC__c>([Select id, activity__c from WGBH_AUAC__c where id in:lstWGBHid]);
            }
            if(lstPositionTitleId <> null && lstPositionTitleId.size()>0){
                Mapwht = new Map<Id, wgbh_job_titles__c>([select id,name,code__c  from wgbh_job_titles__c where id in:lstPositionTitleId]);
            }
            List<Position__c> lstUpdatePos = new List<Position__c>();
            boolean addtolist = false;
            for(Position__c p: lstPos) {
                if(MapW_auac.containsKey(p.billing_accounting_unit__c)) {
                    WGBH_AUAC__c w = MapW_auac.get(p.billing_accounting_unit__c);
                    p.billing_activity_code__c = w.activity__c;
                    //lstUpdatePos.add(p);
                    addtolist = true;
                }
                if(Mapwht.containsKey(p.position_title__c)){
                    wgbh_job_titles__c job = Mapwht.get(p.position_title__c);
                    p.job_level__c = job.code__c;
                    //lstUpdatePos.add(p);
                    addtolist = true;
                }
                if(addtolist==true) lstUpdatePos.add(p);
                addtolist = false;
            }            
            try{
                if(lstUpdatePos.size()>0) Update lstUpdatePos;
            }
            catch(Exception e)
            {
                System.debug(e.getmessage());
            }            
        }
    }

    public static void met(List<String> pos)
    {
        for(String s:pos)
        {
            Position__c p = [Select id, position_title__c, job_level__c,billing_activity_code__c, billing_accounting_unit__c  from Position__c where id=:s];
            
                 if(p.billing_accounting_unit__c!=null)
                 {
                     // get the  WGBH_AUAC__c lookup record and update the billing activity field accordingly
                     WGBH_AUAC__c W_auac = [Select id, activity__c from WGBH_AUAC__c where id=:p.billing_accounting_unit__c];
                     p.billing_activity_code__c = w_auac.activity__c;
                  }
                  if(p.position_title__c!=null)
                  {
                      // get the  wgbh_job_titles__c lookup record and update the job_level field in position accordingly.
                     wgbh_job_titles__c wht = [select id,name,code__c  from wgbh_job_titles__c where id=:p.position_title__c]; 
                     p.job_level__c = wht.code__c;
                  
                  }
                  try{
                     
                     update p;
                  }
                  catch(Exception e)
                  {
                        System.debug(e.getmessage());
                  }
         
        }
    }
    public static testMethod void testUpdateposition_openapproved() {
        WGBH_Job_Titles__c jobTitle = new WGBH_Job_Titles__c(
            name = 'Apex code hacker',
            is_exempt__c = true,
            is_active__c = true,
            EEO_Category__c = 'Professionals',
            Description__c = 'SalesForce VisualForce Apex hacker',
            code__c = 'X123',
            affiliation__c = 'SAG'
        );
        insert jobTitle;        
        WGBH_AUAC__c auac = new WGBH_AUAC__c(
            Name = 'Fred AUAC',
            Activity__c = 'Activity',
            start_date__c=system.today(),
            end_date__c=system.today() + 1,
            description__c = 'new job',
            auac__c = 'clown'
        );
        insert auac;
        Position__c pos = new Position__c(
            created_by_email__c = 'steven.lemmo@roundcorner.com',
            max_pay__c = 30000.0,
            min_pay__c = 25000.0,
            position_title__c = jobTitle.Id,
            activity_code__c = auac.id,
            billing_accounting_unit__c = auac.id
        ); 
        insert pos; 
        
        //Test.StartTest();
        List<String> positions = new List<String>();
        positions.add(pos.id);          
        update_job_level.met(positions);
        //Test.StopTest(); 
            
        Position__c thispos = [Select id, billing_activity_code__c, job_level__c  from position__c where id=:pos.id];       
        System.assertEquals(thispos.billing_activity_code__c,auac.activity__c);
        System.assertEquals(thispos.job_level__c,jobTitle.code__c);                         
    }     

}