kqed/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Units_Available__c</fullName>
        <formula>Units_Ordered__c  -  Units_Sold_calc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Units available to sell. # Ordered - # Sold</inlineHelpText>
        <label>Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

kqed/src/objects/Shipment__c.object
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Shipment_Line__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item_ID__c</fullName>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Premium/Benefit</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Shipment Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/classes/ShipmentLineWrapper.cls
public with sharing class ShipmentLineWrapper {

	public Boolean checked 					{ get; set; }
	//public decimal availableQty 		 	{ get; set; }
	
	public Shipment_Line__c shipmentLine 	{ get; set; }
	public OpportunityLineItem oli 			{ get; set; }	
	
	public ShipmentLineWrapper(OpportunityLineItem li) {
		checked = false;
		//availableQty = li.PricebookEntry.Product2.Units_Available__c;
		this.oli = li;
		this.shipmentLine = new Shipment_Line__c(Opportunity_Line_Item_ID__c=oli.Id, Product__c=oli.PricebookEntry.Product2Id, Quantity__c=null, Shipment__c=null);
	}
}