kqed/src/objects/Relationship_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Relationships and their reverse relationships</description>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reverse_Relationship_Type__c</fullName>
        <label>Reverse Relationship Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Relationship Type</label>
</CustomObject>

kqed/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Account Relationship includes relationship with an individual(Person Account) or the Organization(Business Account)</description>
        <label>Account Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>People__c</fullName>
        <label>People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Rel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_To_AccHousehold__c</fullName>
        <label>Related To Account for the Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To Household)</relationshipLabel>
        <relationshipName>Relationships3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_Organization__c</fullName>
        <label>Related To Account for the Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To Organization)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_People__c</fullName>
        <label>Related To People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related To People)</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TA_relationship_id__c</fullName>
        <description>TA Relationship Id</description>
        <externalId>true</externalId>
        <inlineHelpText>TA Relationship Id</inlineHelpText>
        <label>TA Relationship Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isReciprocal__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If you check this box upon entering that a husband is related to a wife the reciprocal relationship will show on the wife (this is on the contact level only)</inlineHelpText>
        <label>Is Reciprocal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>relationship_type__c</fullName>
        <label>Relationship Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor to Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant to Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aunt to Nephew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aunt to Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boss to Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker to Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother-in-Law to Brother-in-Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother to Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother to Sister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairperson to Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child to Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate to Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client to Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client to Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club to Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague to Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee Member to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee to Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization to Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cousin to Cousin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter to Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter to Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donor to Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donor to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed. Institution to Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Alumni to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee to Boss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee to Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>reverse_relationship_type__c</fullName>
        <label>Reverse Relationship Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor to Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliated Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency to Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant to Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Company to Individual with Same Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aunt to Nephew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aunt to Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boss to Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker to Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother-in-Law to Brother-in-Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother to Brother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brother to Sister</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairperson to Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child to Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate to Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client to Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client to Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client to Lobbyist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club to Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague to Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee Member to Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committee to Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company to Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation to President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation to Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cousin to Cousin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter to Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter to Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate to Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/BatchRelationshipPairing.cls
global class BatchRelationshipPairing implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchRelationshipPairing(){
        this.query = 'Select r.TA_relationship_id__c, r.Related_To_People__c, r.Related_To_Organization__c, r.Related_To_accHousehold__c, r.People__c, r.Organization__c, r.Id, r.Account_Household__c,'+ 
        'r.relationship_type__c, r.reverse_relationship_type__c, r.Primary_Rel__c, r.isReciprocal__c, r.Parent__c From Relationships__c r';
    }
    
    global BatchRelationshipPairing(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Map<String, Relationships__c> relMap = new Map<String, Relationships__c>();
        Map<String, String> taIdMap1 = new Map<String, String>(); 
        Map<String, String> taIdMap2 = new Map<String, String>();
        
        // 0   1 2    3    4  5  6   7
        //xxx_00_C_Type1_yyy_00_I_Type2
        //Orphan__c[] orphans = new List<Orphan__c>();          
        for(Sobject s : scope){
            Relationships__c rel = (Relationships__c) s;
            try {
                relMap.put(rel.TA_relationship_id__c, rel);
                
                String[] relData = rel.TA_relationship_id__c.split('_');
                String reverseTaId = relData[4] + '_' +  relData[5] + '_' + relData[6] + '_' + relData[7] + '_' + relData[0] + '_' + relData[1] + '_' + relData[2] + '_' + relData[3];
                taIdMap1.put(rel.TA_relationship_id__c, reverseTaId);
                taIdMap2.put(reverseTaId, rel.TA_relationship_id__c);
                
                System.debug('relId: '+rel.TA_relationship_id__c+', revRelId:'+reverseTaId);
            }
            catch (Exception ex) {
                /*orphans.add( new Orphan__c(
                    orphan_type__c='Object',
                    classname__c='Relationships__c',
                    exception_message__c=ex.getMessage(),
                    batchname__c='BatchRelationshipPairing',
                    ta_id__c=rel.TA_relationship_id__c,
                    object_id__c=s.id)
                );*/
            }               
        }
        
        System.debug('size before: '+taIdMap1.size());
        for(Integer relIndex = 0; relIndex < taIdMap1.size(); relIndex ++) {
            String relValue = taIdMap1.values()[relIndex];
            for(String revRelValue : taIdMap2.values()) {
                if(relValue == revRelValue) {
                    relMap.remove(relValue);
                    taIdMap1.remove(relValue);
                }
            }
        }
        System.debug('size after: '+taIdMap1.size());
        List<Relationships__c> reverseRels = [Select r.TA_relationship_id__c,r.Related_To_accHousehold__c, r.Related_To_People__c, r.Related_To_Organization__c,  r.People__c, r.Organization__c, r.Id, r.Account_Household__c, 
        r.relationship_type__c, r.reverse_relationship_type__c, r.Primary_Rel__c, r.isReciprocal__c, r.Parent__c From Relationships__c r WHERE r.TA_relationship_id__c IN :taIdMap1.values()];
        
        for(Relationships__c revRel : reverseRels) {
            Relationships__c rel = relMap.get(taIdMap2.get(revRel.TA_relationship_id__c));
            
            rel.Primary_Rel__c = true;
            revRel.Primary_Rel__c = false;
            
            rel.isReciprocal__c = false;
            revRel.isReciprocal__c = true;
            
            rel.Parent__c = null;
            revRel.Parent__c = rel.Id;
        }
        
        update relMap.values();
        update reverseRels;
        //if(orphans.size()>0) insert orphans;        
    }

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchRelationshipPairing', chainFlag);
    }
    
    public static testMethod void testBatch() {
        Relationships__c r1 = new Relationships__c(
            TA_relationship_id__c = '12345_00_C_Type1_54321_00_I_Type2'
        );
        insert r1;
        
        Relationships__c r2 = new Relationships__c(
            TA_relationship_id__c = '54321_00_I_Type2_12345_00_C_Type1'
        );
        insert r2;
        
        Test.StartTest();
        BatchRelationshipPairing batch = new BatchRelationshipPairing();
        batch.query += ' WHERE r.TA_relationship_id__c IN (\'12345_00_C_Type1_54321_00_I_Type2\', \'54321_00_I_Type2_12345_00_C_Type1\')';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();
        
        Relationships__c tr1 = [SELECT Parent__c FROM Relationships__c WHERE TA_relationship_id__c = :r1.TA_relationship_id__c][0];
        Relationships__c tr2 = [SELECT Parent__c FROM Relationships__c WHERE TA_relationship_id__c = :r2.TA_relationship_id__c][0];
        System.debug('tr1: '+tr1.Parent__c+', tr2:'+tr2.Parent__c);
        //System.Assert(tr1.parent__c == tr2.id || tr1.id == tr2.parent__c);
    }
}