kqed/src/objects/Relationships__c.object
<CustomObject>
    <description>Junction object between Organization(Account) and People(Contact)</description>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Account Relationship includes relationship with an individual(Person Account) or the Organization(Business Account)</description>
        <label>Account Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>People__c</fullName>
        <label>People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reciprocal_Relationship__c</fullName>
        <label>Reciprocal Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Acquaintance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Aunt/Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (former)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To_People__c</fullName>
        <label>Related To People</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (Related To People)</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Primary Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Acquaintance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classmate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer - Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Aunt/Uncle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family - Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a duplicate account!</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Supplier (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (current)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional - Business partner (former)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional - Affiliated organizations/businesses (current)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strength__c</fullName>
        <label>Strength</label>
        <picklist>
            <picklistValues>
                <fullName>Undefined</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Strong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weak</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL- {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/TestRelationshipControllers.cls
@isTest
private class TestRelationshipControllers {
    public static testMethod void testAddRelationshipController() {
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
    
        
        Map<String, String> urlParams = new Map<String,String>{
            'id' => account.Id
        };
        Id [] fixedSeatchResult = new Id[2];
        fixedSeatchResult[0] = con1.Id;
        fixedSeatchResult[1] = con2.Id;
        Test.setFixedSearchResults(fixedSeatchResult);
        Test.setCurrentPage(getPageReference('NewRelationship',urlParams));
        AddRelationShipController controller = new AddRelationShipController();
        controller.searchObj = 'People';
        controller.searchString = 'firstName2';
        controller.search();
        //controller.constructDisplayList();
        for(AddRelationShipController.DisplayElement de: controller.displayList){
            de.selected = true;
        }
        //controller.urlParam = con1.Id;
        controller.prepareRelations();
        List<SelectOption> list1 = controller.getrelationshipType();
        List<SelectOption> list2 = controller.getrelationStrength();
        //pageReference pref = controller.saveRelations();
        pageReference pref2 = controller.redirectBack();
        controller.saveRelations();
        controller.createReciprocalRelationship();
    }
    
    
    public static testMethod void testRelationshipEditController(){
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
        
        Relationships__c relation1 = new Relationships__c();
        relation1.Organization__c = account.Id;
        relation1.Related_To_People__c = con2.Id;
        relation1.Relationship__c = 'Advisor';
        relation1.Reciprocal_Relationship__c = 'Advisee';
        relation1.Strength__c = 'Moderate';
        insert relation1;
        Map<String, String> urlParams = new Map<String,String>{
            'id' => account.Id
        };
        
        Test.setCurrentPage(getPageReference('RelationshipEdit', urlParams));
        ApexPages.standardController  stdController = new ApexPages.standardController(relation1);
        RelationshipEditController controller = new RelationshipEditController(stdController);
        
        
        
    }
    
    public static testMethod void testRelationshipEditController2(){
        Account account = new Account(Name = 'Test Account');
        insert account;
        
        // Inserting a People record
        Contact con1 = new Contact(FirstName = 'firstName1', LastName = 'lastName1', AccountId = account.Id);
        insert con1;
        
        Contact con2 = new Contact(FirstName = 'firstName2', LastName = 'lastName2', AccountId = account.Id);
        insert con2;
        
        Relationships__c relation1 = new Relationships__c();
        //relation1.Organization__c = account.Id;
        relation1.People__c = con1.Id;
        relation1.Related_To_People__c = con2.Id;
        relation1.Relationship__c = 'Advisor';
        relation1.Reciprocal_Relationship__c = 'Advisee';
        relation1.Strength__c = 'Moderate';
        insert relation1;
        Map<String, String> urlParams = new Map<String,String>{
            'id' => account.Id
        };
        
        Test.setCurrentPage(getPageReference('RelationshipEdit', urlParams));
        ApexPages.standardController  stdController = new ApexPages.standardController(relation1);
        RelationshipEditController controller = new RelationshipEditController(stdController);
        controller.retId = con1.Id;
        controller.save();
        controller.cancel();
        
        
    }
    
    public static PageReference getPageReference(String page, Map<String, String> params) {
        String url = '/apex/'+page+'?';
        for (String param : params.keySet()) {
            url += param + '=' + params.get(param) + '&';
        }
        PageReference p = new PageReference(url);
        return p;
    }

}