kqed/src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <picklist>
            <picklistValues>
                <fullName>FedEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Giving</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Number_Name__c</fullName>
        <formula>VALUE(SUBSTITUTE(Name, &apos;Ship-&apos;, &apos;&apos;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shipment Number (Name)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <label>Shipping Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/classes/DisplayShipmentController.cls
public with sharing class DisplayShipmentController {
        
        private set<id> setShipIds = new set<id>();
        public list<Shipment__c> shipments                        {get;set;}      
        
    public DisplayShipmentController() {
        system.debug('\n ### in DisplayShipmentController constructor ');
            
        String selected_ShipIds;        
        if (Apexpages.currentPage().getParameters().containsKey('shipIds')) {
                selected_ShipIds = Apexpages.currentPage().getParameters().get('shipIds');
                system.debug('\n ### selected_ShipIds ' + selected_ShipIds);
                for (String shipId : selected_ShipIds.split(',')) {
                        setShipIds.add(shipId);
                }
        }
        system.debug('\n ### selected_ShipIds ' + selected_ShipIds);            
        getShipments();
    }
    
    public PageReference createMore() {
        return Page.CreateShipmentOrder;
    }
    
    public void getShipments() {
        system.debug('\n ### setShipIds ' + setShipIds);
        
        shipments = new list<Shipment__c>();
                if (!setShipIds.isEmpty()) {
                        shipments = [select Id, Name, Carrier__c, Opportunity__c, Organization__c, Shipping_Contact__c, City__c, State__c from Shipment__c where id in :setShipIds order by Shipment_Number_Name__c];
                }
                system.debug('\n ### shipments.size ' + shipments.size() + ' => ' + shipments);
    }
}