kqed_dev4/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCOUNT_ID_FDNDEV__c</fullName>
        <label>ACCOUNT_ID_FDNDEV</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCOUNT_ID_LOCKBOX__c</fullName>
        <label>ACCOUNT_ID_LOCKBOX</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCOUNT_ID_PBSD__c</fullName>
        <label>ACCOUNT_ID_PBSD</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_ID_Auction__c</fullName>
        <label>Account ID Auction</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_ID_Cars__c</fullName>
        <label>Account ID Cars</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCity__c</fullName>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCountry__c</fullName>
        <label>Mailing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingPostalCode__c</fullName>
        <label>Mailing Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <label>Mailing State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingStreet__c</fullName>
        <label>Mailing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <label>UniqueID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_ARIA__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_ARIA</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_AUCTION__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_AUCTION</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_CARS__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_CARS</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_FDNDEV__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_FDNDEV</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_LOCKBOX__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_LOCKBOX</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_ALT_ACCOUNT_ID_PBSD__c</fullName>
        <description>Vendor&apos;s ID of the account making the pledge: Maps to: UL_ACCOUNTS.ALT_ACCOUNT_ID</description>
        <label>PB5_ALT_ACCOUNT_ID_PBSD</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME_2__c</fullName>
        <description>The first name of the second named account in the file</description>
        <label>PB5_FIRST_NAME_2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_FIRST_NAME__c</fullName>
        <description>First name of household or contact or organziation. Maps to: UL_NAMES.FIRST_NAME</description>
        <label>PB5_FIRST_NAME</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME_2__c</fullName>
        <description>The last name of the second person in the file</description>
        <label>PB5_LAST_NAME_2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_LAST_NAME__c</fullName>
        <description>Last name of household, contact, organizaiton. Maps to: UL_NAMES.LAST_NAME</description>
        <label>PB5_LAST_NAME</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SFDC_ID__c</fullName>
        <description>Salesforce ID of household, contact or organization maps to: UL_ACCOUNTS.ACCOUNT_ID</description>
        <label>PB5_SFDC_ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_CITY__c</fullName>
        <label>PB5_SHIP_TO_CITY</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STATE__c</fullName>
        <label>PB5_SHIP_TO_STATE</label>
        <picklist>
            <picklistValues>
                <fullName>GET PICK LIST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_STREET_1__c</fullName>
        <label>PB5_SHIP_TO_STREET_1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB5_SHIP_TO_ZIP_CODE__c</fullName>
        <label>PB5_SHIP_TO_ZIP_CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/classes/UploadRecordMatchingHouseHold.cls
public class UploadRecordMatchingHouseHold{
    public static Account objHouse = new Account();
    public static String ProcessHousehold(WGBH_PB5_UPLOAD__c PB5){
        //String MatchingCriteria = 'ACCOUNT_ID_ARIA__c=PB5_ALT_ACCOUNT_ID_ARIA__c;ACCOUNT_ID_AUCTION__c=PB5_ALT_ACCOUNT_ID_AUCTION__c;ACCOUNT_ID_CARS__c=PB5_ALT_ACCOUNT_ID_CARS__c;ACCOUNT_ID_FDNDEV__c=PB5_ALT_ACCOUNT_ID_FDNDEV__c;ACCOUNT_ID_LOCKBOX__c=PB5_ALT_ACCOUNT_ID_LOCKBOX__c;ACCOUNT_ID_PBSD__c=PB5_ALT_ACCOUNT_ID_PBSD__c';
        String MatchingCriteria = 'UniqueID__c=PB5_SFDC_ID__c';
        List<sObject> lstTarget;
        lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Account',MatchingCriteria);
        if(lstTarget.size()==0){
            insertHousehold(PB5);
        }
        else if(lstTarget.size()==1){
            objHouse = (Account)lstTarget[0];
            updateHousehold(PB5);
        }
        else if(lstTarget.size()>1){
        }
        return String.valueOf(objHouse.Id);
    }
    public static boolean UpdateHousehold(WGBH_PB5_UPLOAD__c pb){
        boolean blnSuccess=false;        
        mapHouseholdField(pb);
        try{
            update objHouse;
            if(objHouse.Id != null && String.valueOf(objHouse.Id).length()>0)
                blnSuccess = true;
            else
                blnSuccess = false;
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    public static boolean InsertHousehold(WGBH_PB5_UPLOAD__c pb){
        boolean blnSuccess=false;
        mapHouseholdField(pb);
        try{
            insert objHouse;
            if(objHouse.Id != null && String.valueOf(objHouse.Id).length()>0)
                blnSuccess = true;
            else
                blnSuccess = false;
        }Catch(Exception ex){
            blnSuccess = false;
        }
        return blnSuccess;
    }
    static string getValues(string val1, string val2){
        if(NVL(val1)=='')
            return NVL(val2);
        else
            return NVL(val1);
    }
    static string NVL(string val){
        if(val == null)
            return '';
        else
            return val.trim();
    }
    static ID getRecordTypeId(String developerName){
        ID recordTypeId = null;
        
        List<RecordType> lstRc = [Select Id, DeveloperName from RecordType Where DeveloperName =: DeveloperName];
        if(lstRc != null && lstRc.size()>0){
            recordTypeId = lstRc[0].Id;
        }
        return recordTypeId;
    }
    public static void mapHouseholdField(WGBH_PB5_UPLOAD__c pb){        
        objHouse.name = getValues(pb.PB5_FIRST_NAME__c, pb.PB5_FIRST_NAME_2__c) + ' ' + getValues(pb.PB5_LAST_NAME__c, pb.PB5_LAST_NAME_2__c);
        objHouse.recordTypeId = getRecordTypeId('Household');
        objHouse.MailingCity__c = pb.PB5_SHIP_TO_CITY__c;
        //objHouse.MailingCountry__c
        objHouse.MailingState__c = pb.PB5_SHIP_TO_STATE__c;
        objHouse.MailingStreet__c = pb.PB5_SHIP_TO_STREET_1__c;
        objHouse.MailingPostalCode__c = pb.PB5_SHIP_TO_ZIP_CODE__c;        
        return;
    }
    
    static testMethod void myTest() {
        WGBH_PB5_UPLOAD__c pb5 = new WGBH_PB5_UPLOAD__c();
        insert pb5;
        
        UploadRecordMatchingHouseHold.ProcessHousehold(pb5);
        UploadRecordMatchingHouseHold.UpdateHousehold(pb5);
        UploadRecordMatchingHouseHold.InsertHousehold(pb5);
        UploadRecordMatchingHouseHold.mapHouseholdField(pb5);



    }
    
}