kqed_dev4/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>end_date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Department__c.object
<CustomObject>
    <description>Object to store department records from Lawson.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Code__c</fullName>
        <label>Activity Code</label>
        <referenceTo>WGBH_AUAC__c</referenceTo>
        <relationshipLabel>Job Requisitions (Activity Code)</relationshipLabel>
        <relationshipName>Job_Requisitions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>AEEF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NABET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Building_Location__c</fullName>
        <label>Building Location</label>
        <picklist>
            <picklistValues>
                <fullName>One Guest St</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 Guest St</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape and Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caption Center LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caption Center NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Greenfield MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York Promotion Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOVA scienceNOW NY Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGBY Springfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&quot;God in America&quot; Rhode Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&quot;God In America&quot; S. Carolina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMX &quot;Whaling&quot; PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMX Whaling CT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co - Op</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_By_Email__c</fullName>
        <defaultValue>$User.Email</defaultValue>
        <label>Created By Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Departments__c</fullName>
        <label>Departments</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Job Requisitions</relationshipLabel>
        <relationshipName>Job_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Educational_Requirements__c</fullName>
        <label>Educational Requirements</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours_Per_Week__c</fullName>
        <description>Number of hours per week.</description>
        <inlineHelpText>Number of hours per week for the position</inlineHelpText>
        <label>Hours Per Week</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Description__c</fullName>
        <description>High-level description of the job and what its duties are.</description>
        <label>Department Overview</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greenfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape &amp; Islands</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <description>Max. pay allowed for the position.</description>
        <inlineHelpText>Max. pay allowed for the position.</inlineHelpText>
        <label>Maximum Budgeted Salary</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <description>Min. Pay for the position.</description>
        <inlineHelpText>Min. Pay for the position.</inlineHelpText>
        <label>Minimum Budgeted Salary</label>
        <precision>9</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Openings_for_this_job__c</fullName>
        <label>Number of Openings for this job</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <label>Position Title</label>
        <referenceTo>WGBH_Job_Titles__c</referenceTo>
        <relationshipLabel>Job Requisitions</relationshipLabel>
        <relationshipName>Job_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Length__c</fullName>
        <label>Project Length (in weeks)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publish_OpenDate__c</fullName>
        <description>Date when position is published.</description>
        <inlineHelpText>Date when position is published.</inlineHelpText>
        <label>Posting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Position Overview</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Travel Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Union_Maximum_Salary__c</fullName>
        <label>Maximum Union Salary</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Union_Minimum_Salary__c</fullName>
        <label>Minimum Union Salary</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Job Requisition</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/WGBH_AUAC__c.object
<CustomObject>
    <description>List of accounting units with activity codes (General Ledge codes)</description>
    <fields>
        <fullName>AUAC__c</fullName>
        <description>Combination of the accounting unit and activity which makes the record unique</description>
        <externalId>true</externalId>
        <label>AUAC</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of AU AC Combo</description>
        <label>Description</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Teh date the AU AC Combo ceases to be active</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the AU AC Combo becomes active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>AUAC</label>
    <nameField>
        <label>AUAC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AUAC&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/WGBH_Job_Titles__c.object
<CustomObject>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>The Union Affiliation for the position</description>
        <label>Affiliation</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The Job Title</description>
        <label>Description</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Job Title</label>
    <nameField>
        <label>Job Titles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/positiondetail.cls
public class positiondetail 
{
    public String p { get; set; }
    public string posid{get; set;}
    public position__c Pos{get; set;}
    public string strOpen {get;set;} 
    
    public pagereference met()
    {
        if (posid == null || posid == '')
        {
            posid = ApexPages.currentPage().getParameters().get('id');
        }
    /*Ketan Benegal - Added Classification Type and Project Length to the query*/
        Pos = [SELECT Id, Name, Affiliation__c, position_Title__r.Description__c, Responsibilities__c, Skills_Required__c, Job_Description__c, Location__c, Max_Pay__c, Min_Pay__c,Hours_Per_Week__c, 
             Educational_Requirements__c, Close_Date__c, publish_OpenDate__c, Project_Name__c,Project_length__c, Travel_Required__c, Project_Start_Date__c, 
             Number_of_Openings_for_this_job__c,Building_Location__c,departments__r.name,Union_Maximum_Salary__c,Union_Minimum_Salary__c, Type__c, Classification__c from Position__c where id=:posid];
             
        if (Pos.Publish_OpenDate__c != null)
        {
            strOpen = Pos.Publish_OpenDate__c.format();
        }
            
        return null;
     }

    public String travelRequired()
    {
        if (pos.Travel_Required__c == true) return 'Yes';
        else return 'No';
    }

    Public pagereference Apply()
    {
        if(Pos.Close_Date__c != null){
            String err='Thank you for your interest in employment opportunities at WGBH. Unfortunately, the position for which you are applying has been closed. For a list of current employment opportunities please visit the WGBH career website at <a href="http://www.wgbh.org/about/employmentOpportunities.cfm">here</a>';
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,err)); 
        }else{
                if(Userinfo.getUsertype()=='Guest')
                {
                    pagereference pg = new Pagereference('/apex/ats_login_user?thisid='+posid);
                    return pg;
                }
                else
                {
                     pagereference pg = new Pagereference('/apex/appwizard?id='+posid);
                    return pg;
                }
        }
        return null;
    }
    
    public static testMethod void testApply()
    {
        //Test.startTest();
        positiondetail pd   = new positiondetail();
        position__c p = new position__c();
        pd.pos = p;
        pd.Apply();
        //Test.stopTest();
    }
    
    public static testMethod void testMet()
    {
        WGBH_AUAC__c auac          = new WGBH_AUAC__c();
        //initialize auac
        auac.Name = 'Fred AUAC';
        auac.Activity__c    = 'Activity';
        auac.start_date__c  = system.today();
        auac.end_date__c    = system.today() + 1;
        auac.description__c = 'NEW AUAC';
        auac.auac__c        = 'YANKEES';
        //insert
        insert auac;
        
        Position__c jobReq         = new Position__c();
        jobReq.Created_By_Email__c = 'brian_wainwright@wgbh.org';
        jobReq.Max_Pay__c          = 10000.0;
        jobReq.Min_Pay__c          = 5000.0;
        jobReq.Activity_Code__c    = auac.id;
        jobReq.Publish_OpenDate__c = System.today();
        
        insert jobReq;
        
        //Test.startTest();
        positiondetail pd   = new positiondetail();
        pd.posid = jobReq.Id;
        pd.met();
        System.assertEquals(pd.travelRequired(), 'No');
        jobReq.Travel_Required__c  = true;
        jobReq.Publish_OpenDate__c = null;
        update jobReq;
        pd.met();
        System.assertEquals(pd.travelRequired(), 'Yes');
        //Test.stopTest();
    }
}