kqed_dev4/src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <type>TextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <externalId>true</externalId>
        <label>TA Contact Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>middle_name__c</fullName>
        <description>Middle Name</description>
        <label>Middle Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate_First_Name__c</fullName>
        <label>Candidate First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate_Last_Name__c</fullName>
        <label>Candidate Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Question__c</fullName>
        <label>Security Question</label>
        <picklist>
            <picklistValues>
                <fullName>What is your pets name?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What is your mothers maiden name?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What city were you born in?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In what city was your first job?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What is the name of your favorite childhood friend?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In what city did you meet your spouse/significant other?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What was your childhood nick name?</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed/src/classes/AtsCreatePortalUser_Util.cls
public class AtsCreatePortalUser_Util {
    public Boolean registerUser(String firstname, String lastname, String username, String password) {
        User u = new User();
        u.Username = username;
        u.Email =  username;
        u.Candidate_first_name__c = firstName;
        u.Candidate_last_name__c = lastName;
        u.CommunityNickname = username;      
        u.FirstName = firstName;
        u.LastName = lastName;
        //?? u.security_question__c= question;
        //?? u.answer__c= ans;
        
        String accountId = '060A0000000HOXp';

        // lastName is a required field on user, but if it isn't specified, we'll default it to the username
        String userId = Site.createPortalUser(u, accountId, password);
        if (userId != null) { 
            return true;
        }
        return false;
    }
    public Boolean go() {
        Contact[] contacts = [Select c.middle_name__c, c.bulk_load__c, c.TaContactId__c, c.OtherCity, c.MailingCity, c.LastName, c.FirstName, c.Email From Contact c  where email = 'janeapplicantwgbh@gmail.com'];             
        //Contact[] contacts = [Select c.middle_name__c, c.bulk_load__c, c.TaContactId__c, c.OtherCity, c.MailingCity, c.LastName, c.FirstName, c.Email From Contact c  where othercity = 'Timbukto'];      
        for(Contact cnt : contacts) {
            registeruser(cnt.firstname, cnt.lastname, cnt.email, 'fr3dfr3d');
        } 
        return true;    
    }
    
    static testMethod void Mytest() {
        AtsCreatePortalUser_Util clsTest = new AtsCreatePortalUser_Util();
        clsTest.registerUser('test','test','test','test');
        clsTest.go();
        
    }
}

//new AtsCreatePortalUser_Util().go();