kqed_dev4/src/objects/Bios__c.object
<CustomObject>
    <description>Object utilized for listing the various ways in which a Contact is related to the Organization and/or personal highlights that are important for profiling a person.  This object will has multiple record types and field dependencies to represent the different types of records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Board_Level__c</fullName>
        <label>Board Level</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overseer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tribune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date Term Completes (or is expected to complete)</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAL ACADEMY SCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAL PERFORMANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EARTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPLOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIDDENVILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIDDENVLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLANPARENTGG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAN JOSE MUSEUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAN JOSE REP THEATRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF BALLET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF ED FUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF MOMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF OPERA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF SYMPHONY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TECH MUSEUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THEATREWORKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YERBA BUENA CTR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nominated_By__c</fullName>
        <label>Nominated By</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bios</relationshipLabel>
        <relationshipName>Bios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date Term Initiates</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Of_Degree__c</fullName>
        <formula>MID(degree_year__c , 0, 4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year of Degree</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>degree_code__c</fullName>
        <description>Degree Code</description>
        <inlineHelpText>Degree Code</inlineHelpText>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PhD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>degree_major__c</fullName>
        <description>Degree Major</description>
        <inlineHelpText>Enter the field for the major i.e. Accounting, Science, Engineering</inlineHelpText>
        <label>Major</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>degree_year__c</fullName>
        <description>Degree Year</description>
        <inlineHelpText>Degree Year</inlineHelpText>
        <label>Degree Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>education_begin_date__c</fullName>
        <description>Education Begin Date</description>
        <inlineHelpText>Education Begin Date</inlineHelpText>
        <label>Education Begin Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>education_end_date__c</fullName>
        <description>Education End Date</description>
        <inlineHelpText>Education End Date</inlineHelpText>
        <label>Education End Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>first_interest_source_value__c</fullName>
        <description>First Interest Source</description>
        <inlineHelpText>First Interest Source</inlineHelpText>
        <label>First Interest Source Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>first_program__c</fullName>
        <label>First Program</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interest_code__c</fullName>
        <description>Interest Code</description>
        <inlineHelpText>Interest Code</inlineHelpText>
        <label>Interest</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interest_code_value__c</fullName>
        <description>Interest Code</description>
        <inlineHelpText>Interest Code</inlineHelpText>
        <label>Interest Code Value</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_interest_source_value__c</fullName>
        <description>Last Interest Source</description>
        <inlineHelpText>Last Interest Source</inlineHelpText>
        <label>Last Interest Source Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_program__c</fullName>
        <label>Last Program</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>school_code__c</fullName>
        <description>School Name</description>
        <inlineHelpText>Name of school, university, college, community college, continuing education</inlineHelpText>
        <label>School Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bio</label>
    <nameField>
        <displayFormat>Bio-{00000000}</displayFormat>
        <label>Bio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Prospect_Research_Reports__c.object
<CustomObject>
    <description>Prospect Research Reports are utilized for profiling of members, prospective members and constituents by the Prospect Research Team.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prospect Research Report</label>
    <nameField>
        <label>PRR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Research Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/classes/PRROtherBoards.cls
Public Class PRROtherBoards{

    public list<Bios__c> TruBios{get;set;}
    public String Delid{get;set;}
    public string id{get;set;}
    public string TruRTid{get; set;}
    public string Trusize{get; set;}
        
    Public String Contactname{get; set;}
    public PRROtherBoards(ApexPages.StandardController controller) {
        PageLoad();
    }
    public PRROtherBoards() {
        PageLoad();
    }
    public void PageLoad(){
        try{
            TruRTid=[Select id from recordtype where name = 'Board/Trustee'][0].id;
        }
        catch(Exception ex)
        {
            System.debug('Exception in catch'+ex.getmessage());
        }
    
        List<Prospect_Research_Reports__c> lstId =[select contact__c from Prospect_Research_Reports__c where id=: ApexPages.CurrentPage().getParameters().get('id')];
        id = lstId[0].contact__c;
        Delid='aaa';
        List<Recordtype> rt = [Select r.Name, r.Id From RecordType r where name ='Education'];
    
        Trusize='';
        met();
    }    
    

    
    public void Met(){
        TruBios=[SELECT Id, Name,name__C, Account__c, Board_Level__c,Nominated_By__c, Interest_Code__c, School_Code__c, Degree_Code__c, Degree_Year__c, Year_Of_Degree__c,
         Degree_Major__c, Education_Begin_Date__c, Education_End_Date__c, Interest_Code_Value__c, First_Program__c,recordtypeid,
         Last_Program__c, First_Interest_Source_Value__c, Last_Interest_Source_Value__c, Start_Date__c, End_Date__c  from Bios__c 
         where Related_To__c=:id and recordtypeid=:trurtid];
         
         if(Trubios!=null)
         Trusize='Other Board' +' '+'['+String.valueof(Trubios.size()) +']';
         if(Trubios.size()==0)
         Trusize='Other Board';
         
    }

    public PageReference Delmet() {
    System.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'+''+Delid);
    try{
    Bios__c b= [SELECT Id, Name from Bios__c where id=:DelId];
    delete b;
    }
    catch(Exception e)
    {
    System.debug('Delid not available');
    System.debug(e);
    }
    pagereference pg = new pagereference('/apex/tabpanel?id='+id);
    return pg;
    }
    
    

    public static testmethod void tes(){
        Contact c = new Contact();
        c.Lastname='test';
        insert c;
        List<Bios__c> bb = [Select id, name from Bios__c limit 1];
        Apexpages.CurrentPage().getParameters().put('id', c.id);
        tabscontroller tc = new tabscontroller(new ApexPages.StandardController(c));
        //Pagereference pg = tc.bio();
        if(bb != null && bb.size() > 0) {              
        tc.met();
        pagereference pgg = tc.newfun();
        //List<Bios__c> b = new List<bios__c>([SELECT id, name from Bios__c where id=:bb[0].id limit 1]); 
        tc.delId=bb[0].id;
        pagereference pg = tc.delmet(); 
        }
    }
    
}