kqed_dev4/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <label>Merchant ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Country__c.object
<CustomObject>
    <description>Country objects</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <label>Response Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charge Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complimentary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Funds Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutual fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Deduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carte Blanche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diner&apos;s Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generic Charge Card - No CC# Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Dated Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>The id of the pledge</description>
        <label>Opportunity_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <description>If the payment is rejected what is the message</description>
        <label>Response_Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submit_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How many times the payment has been submitted for processing</description>
        <label>Submit_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TRANSACTION_BATCH</label>
    <nameField>
        <label>TRANSACTION_BATCH Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TRANSACTION_BATCHS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/classes/BatchExecPAYMENT_BATCH.cls
global class BatchExecPAYMENT_BATCH implements Database.Batchable<sObject>,Database.AllowsCallouts {
    global final String Query;
 
    global BatchExecPAYMENT_BATCH(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoPaymentBatchStatus(scope);
    }

    void DoPaymentBatchStatus(List<sObject> scope) {
        
        System.debug('###start1');
        
                
        Boolean Success;
        String strId;
        String M_ID;
        String M_KEY;
        
        String C_NAME;
        String C_ADDRESS;
        String C_CITY;
        String C_STATE;
        String C_ZIP;
        String C_COUNTRY;
        String C_EMAIL;
        String GUID;
        String T_CUSTOMER_NUMBER;
        String T_AMT;
        String T_SHIPPING;
        String T_TAX;
        String T_ORDERNUM;
        String C_TELEPHONE;
        String C_FAX;
        String C_SHIP_NAME;
        String C_SHIP_ADDRESS;
        String C_SHIP_CITY;
        String C_SHIP_STATE;
        String C_SHIP_ZIP;
        String C_SHIP_COUNTRY;
        
        String C_FIRST_NAME,C_MIDDLE_INITIAL,C_LAST_NAME,C_SUFFIX;
        
        for(sObject s : scope) {
            Transaction_Batch__c ObjTrasBatch = (Transaction_Batch__c)s;
            
            strId = BlankIsNull(ObjTrasBatch.Opportunity_Id__c);
            M_ID = BlankIsNull(ObjTrasBatch.Merchant_id__c);
            M_KEY = BlankIsNull(ObjTrasBatch.Merchant_key__c);
            C_NAME = '';
            C_ADDRESS = '';
            C_CITY = '';
            C_STATE = '';
            C_ZIP = '';
            C_COUNTRY = '';
            C_EMAIL= '';
            GUID = BlankIsNull(ObjTrasBatch.GUID__c);
            T_CUSTOMER_NUMBER = '';
            T_AMT = '';
            T_SHIPPING = '';
            T_TAX = '';
            T_ORDERNUM = '';
            C_TELEPHONE = '';
            C_FAX = '';
            C_SHIP_NAME = '';
            C_SHIP_ADDRESS = '';
            C_SHIP_CITY = '';
            C_SHIP_STATE = '';
            C_SHIP_ZIP = '';
            C_SHIP_COUNTRY = '';
            
            C_FIRST_NAME = '';
            C_MIDDLE_INITIAL = '';
            C_LAST_NAME = '';
            C_SUFFIX = '';
            
           If(strId != null && strId != ''){
                 List<Opportunity> lstOpp = New List<Opportunity>
                ([Select ID, CC_EFT_Alias__r.Contact__r.Preferred_Address__r.City__c,CC_EFT_Alias__r.Account__r.Preferred_Address__r.City__c 
                   ,Status__c,Response_message__c,Response_Code__c From Opportunity where ID=: strId]);
                System.debug('###lstoppsize:' + lstOpp.size());
                if(lstOpp.size() == 1)
                {
                    Opportunity o = lstOpp[0];
                    
                    
                    if (o.CC_EFT_Alias__r.Contact__c != null){
                        C_NAME = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.FirstName) + '' + BlankIsNull(o.CC_EFT_Alias__r.Contact__r.LastName);
                        C_ADDRESS =  BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Preferred_Address__r.Street_1__c);
                        C_CITY =  BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Preferred_Address__r.City__c);
                        C_STATE =  BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Preferred_Address__r.State__c);
                        C_ZIP =   BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Preferred_Address__r.Postal_Code__c);
                        C_COUNTRY = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Preferred_Address__r.Country__c);
                        C_EMAIL = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Email);
                        T_CUSTOMER_NUMBER = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Id);
                        
                        C_FIRST_NAME = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.FirstName);
                        C_MIDDLE_INITIAL = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.middle_name__c);
                        IF(C_MIDDLE_INITIAL != null && C_MIDDLE_INITIAL != '')
                        {
                            C_MIDDLE_INITIAL = C_MIDDLE_INITIAL.Substring(0,1).toUpperCase();
                        }
                        C_LAST_NAME = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.LastName);
                        C_SUFFIX = BlankIsNull(o.CC_EFT_Alias__r.Contact__r.Suffix__c);
                       
                    }
                    else if (o.CC_EFT_Alias__r.Account__c != null) {
                        C_NAME = BlankIsNull(o.CC_EFT_Alias__r.Account__r.Name);
                        C_ADDRESS =  BlankIsNull(o.CC_EFT_Alias__r.Account__r.Preferred_Address__r.Street_1__c);
                        C_CITY =  BlankIsNull(o.CC_EFT_Alias__r.Account__r.Preferred_Address__r.City__c);
                        C_STATE =  BlankIsNull(o.CC_EFT_Alias__r.Account__r.Preferred_Address__r.State__c);
                        C_ZIP =   BlankIsNull(o.CC_EFT_Alias__r.Account__r.Preferred_Address__r.Postal_Code__c);
                        C_COUNTRY = BlankIsNull(o.CC_EFT_Alias__r.Account__r.Preferred_Address__r.Country__c);
                        C_EMAIL = '';
                        T_CUSTOMER_NUMBER = BlankIsNull(o.CC_EFT_Alias__r.Account__r.Id);
                    }                   
                    
                    String strAmt='';
                    if(ObjTrasBatch.Payment_Amount__c != null){
                        strAmt= ObjTrasBatch.Payment_Amount__c.toPlainString();
                    }
                    T_AMT = BlankIsNull(strAmt);
                    T_SHIPPING = '';
                    T_TAX = '';
                    T_ORDERNUM = '';
                    C_TELEPHONE = '';
                    C_FAX = '';
                    C_SHIP_NAME = '';
                    C_SHIP_ADDRESS = '';
                    C_SHIP_CITY = '';
                    C_SHIP_STATE = '';
                    C_SHIP_ZIP = '';
                    C_SHIP_COUNTRY  = '';                   
                                       
                    Success = false;
                    SageTransactionProcess objSageTP = new SageTransactionProcess();
                    if(o.Payment_method__c == 'Electronic Funds Transfer')
                    {
                        String C_ORIGINATOR_ID= '';
                        
                        Success = objSageTP.SageVirtualCheckPaymentRequest(M_ID,M_KEY,C_ORIGINATOR_ID,C_FIRST_NAME,C_MIDDLE_INITIAL,
                                            C_LAST_NAME,C_SUFFIX,C_ADDRESS,C_CITY,C_STATE,C_ZIP,C_COUNTRY,C_EMAIL,GUID,T_AMT,
                                            T_SHIPPING,T_TAX,T_ORDERNUM,C_TELEPHONE,C_FAX,C_SHIP_NAME,C_SHIP_ADDRESS,C_SHIP_CITY,
                                            C_SHIP_STATE,C_SHIP_ZIP,C_SHIP_COUNTRY);
                    }
                    else
                    {
                        Success = objSageTP.SagePaymentRequest(M_ID,M_KEY,C_NAME,C_ADDRESS,C_CITY,C_STATE,C_ZIP,C_COUNTRY,C_EMAIL,GUID,
                                            T_CUSTOMER_NUMBER,T_AMT,T_SHIPPING,T_TAX,T_ORDERNUM,C_TELEPHONE,C_FAX,C_SHIP_NAME,
                                            C_SHIP_ADDRESS,C_SHIP_CITY,C_SHIP_STATE,C_SHIP_ZIP,C_SHIP_COUNTRY);
                    }
                    ObjTrasBatch.Process_date__c = System.Today();
                    ObjTrasBatch.Submit_count__c = ObjTrasBatch.Submit_count__c + 1 ;
                    
                    If(Success == true && objSageTP.strStatus =='A')
                    {
                      //if(ObjTrasBatch.Status__c != null && ObjTrasBatch.Status__c == 'FAIL') {
                      ObjTrasBatch.Response_Code__c = '';
                      ObjTrasBatch.Response_message__c = '';
                      //}
                      ObjTrasBatch.Status__c = 'SUCCESS';
                    } else
                    {
                       ObjTrasBatch.Response_message__c = objSageTP.Response_message;
                       ObjTrasBatch.Status__c = 'FAIL';
                       //if(Response_Code != ''){ 
                       ObjTrasBatch.Response_Code__c = objSageTP.Response_Code;
                       //}
                    }
                    //lstbatch.add(ObjTrasBatch);
                    Update ObjTrasBatch;
                    
                    //List<Opportunity> objOpp = new List<Opportunity>([Select Id From Opportunity Where Id =: strId]);
                    //if(objOpp.Size()>0)
                    //{
                    o.Status__c =  ObjTrasBatch.Status__c;
                    o.Response_Code__c =  ObjTrasBatch.Response_Code__c;
                    o.Response_message__c = ObjTrasBatch.Response_message__c;
                    Update o;
                    //}
                }               
            }
        }

    }

    Private String BlankIsNull(String Value)
    {
        if(Value == null) 
            return '';
        else
            return Value; 
    }

    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }
}