kqed_dev4/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <label>Card Holder Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/classes/SageVaultResponseHandler.cls
public class SageVaultResponseHandler {
static{
			String strtemp = ApexPages.currentPage().getParameters().get('response');
			Map<String, String> myMap = ApexPages.currentPage().getParameters();
			//Set<String> s = ApexPages.currentPage().getHeaders().keySet();
			//List<String> headerList = ApexPages.currentPage().getHeaders().values();
/*			for(String listVal : headerList){
				System.debug('listVal value: ' + listVal);
			}
			*/
			for(String strKey : myMap.keySet())
{
    String thisList = myMap.get(strKey);

        System.debug('key: '+ strKey +'  listVal value: ' + thisList);

}
	//	System.debug('strtemp: ' + strtemp + '  set size:' + s.size());		
	
}
    public String response_v1{get{System.debug('response value:' + response_v1); return this.response_v1;} set;}
    public String res{get; set;}
    public CC_Alias__c  vccAlias ;
    
    public SageVaultResponseHandler(){

        String strtemp = ApexPages.currentPage().getParameters().get('Response');
        System.debug('strtemp: ' + strtemp);
        res = strtemp;     
        vccAlias = new CC_Alias__c();
        
    /*  vccAlias = new CC_Alias__c();
        vccAlias.Response__c = this.response_v1;
        vccAlias.Card_Holder_Name__c = 'aaa';
        insert vccAlias;
        System.debug('constructor; '+ vccAlias.Id);*/
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'response value:' + response_v1));
    }
    public void Save(){
        System.debug('response value 222:' + this.response_v1);
        vccAlias.Response__c = this.response_v1;
        insert vccAlias;
    }
    
    public String doData()
    {
       return res;
    } 
    
    public void methodA(){
        System.debug('methodA');
        
    }

}