kqed_dev4/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Classification_Code_Value__c</fullName>
        <label>Classification Code Value</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Classification</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>TA Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_tabname__c</fullName>
        <description>delete when you can untangle the visual force page</description>
        <label>Classification Tab Name X</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>TA Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>record_seq__c</fullName>
        <label>Record Seq</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed_dev4/src/objects/Classification_Code__c.object
<CustomObject>
    <description>This values is used to match the PB5 input on a new contact giving a donation to match their preferences.  Do not delete.</description>
    <fields>
        <fullName>classification_code__c</fullName>
        <label>Classification Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>classification_value__c</fullName>
        <label>Classification Value</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Classification Code/Value</label>
    <nameField>
        <label>Classification Code/Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Code/Value</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>comments__c</fullName>
        <description>Comments</description>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>Flag_Review_Reason__c</fullName>
        <label>Flag Review Reason</label>
        <picklist>
            <picklistValues>
                <fullName>MORE THAN 1 MATCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC PLEDGE ID or PLEDGE NUMBER EXIST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS AMT equal to PAYMENT AMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT DATE ON PLEDGE WITH PREMIUMS &lt; 1 YEAR FROM CURRENT DATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; SUM OF PRODUCTS MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLEDGE AMOUNT &lt; PRODUCT MINIMUM AMOUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIFT TYPE IS NULL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flag_for_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag for Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PB5_Stage__c</fullName>
        <label>PB5 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SF_Duplicate_ID__c</fullName>
        <label>SF Duplicate ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/UploadRecordMatchingClassification.cls
public class UploadRecordMatchingClassification{
    public static void ProcessClassification(WGBH_PB5_UPLOAD__c PB5){
        List<sObject> lstTarget;
        List<Classification__c> lstClassification = new List<Classification__c>();
        List<Classification__c> lstInsert = new List<Classification__c>();
        List<Classification__c> lstUpdate = new List<Classification__c>();
        
        //UploadRecordMatchingProcess__c csMatchingFields = UploadRecordMatchingProcess__c.getOrgDefaults();
        //String MatchingCriteria = csMatchingFields.Matching_Criteria__c;
        //lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        //ProcessContact(PB5, lstTarget, '1');
        //MatchingCriteria = csMatchingFields.Contact_Matching_Criteria_2__c;
        //lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Contact',MatchingCriteria);
        //ProcessContact(PB5, lstTarget, '1');
        for(Integer i = 0; i < 10; i++){
            String MatchingCriteria = 'classification_code__c=PB5_CLASSIFICATION_CODE_' 
            + String.valueOf(i+1) 
            + '__c,classification_value__c=PB5_CLASSIFICATION_VALUE_' 
            + String.valueOf(i+1) + '__c';    
            lstTarget = UploadRecordMatching.getMatchingRows(PB5,'Classification__c',MatchingCriteria);
            if(lstTarget.size()==0){
                //insert new
                lstInsert.addAll(mapClassificationField((sObject)PB5));
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'C';
            }            
            else if(lstTarget.size()==1){
                //update
                PB5.Flag_for_Review__c = false;
                PB5.PB5_Stage__c = 'C';
            }
            else if(lstTarget.size()>1){
                String duplicateId='';
                for(sObject t:lstTarget){
                    if(duplicateId.length()==0)
                        duplicateId = String.valueOf(t.get('Id')) + '#' + String.valueOf(t.get('name'));
                    else
                        duplicateId += +', ' + String.valueOf(t.get('Id')) + '#' + String.valueOf(t.get('name'));                        
                }
                PB5.SF_Duplicate_ID__c = duplicateId;
                PB5.Flag_for_Review__c = true;
                PB5.Flag_Review_Reason__c = 'MORE THAN 1 MATCH';                
            }
        }
        if(lstInsert.size()>0)
            insert lstInsert;
    }
    
    public static List<Classification__c> mapClassificationField(sObject pb){
        List<Classification__c> lstCls = new List<Classification__c>();
        Date startdate;
        Date enddate;
        for(integer i=1; i<=10; i++){
            Classification__c cls = new Classification__c();
            cls.active__c = true;
            cls.classification_code__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            //cls.Classification_Code_Value__c = String.valueOf(pb.get('PB5_CLASSIFICATION_VALUE_' + String.valueOf(i) + '__c')); //Lookup(Classification Code/Value) 
            //cls.classification_tabname__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            cls.classification_value__c = String.valueOf(pb.get('PB5_CLASSIFICATION_VALUE_' + String.valueOf(i) + '__c'));
            //cls.comments__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            //cls.Contact__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));            
            //cls.Household__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            //cls.Organization__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            //cls.record_seq__c = String.valueOf(pb.get('PB5_CLASSIFICATION_CODE_' + String.valueOf(i) + '__c'));
            startdate = Date.valueOf(pb.get('PB5_START_CDATE_' + String.valueOf(i) + '__c'));
            if(startdate == null)//If startdate null in upload data, apply current date as startdate.
                startdate = system.today();            
            cls.start_date__c = startdate;
            enddate = Date.valueOf(pb.get('PB5_END_CDATE_' + String.valueOf(i) + '__c'));
            if(enddate != null)
                cls.end_date__c = enddate;
            lstCls.add(cls);            
        }
        return lstCls;
    }
    
}