kqed_dev4/src/objects/Classification__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classifications</relationshipLabel>
        <relationshipName>Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preference_Value__c</fullName>
        <inlineHelpText>Related to Preference</inlineHelpText>
        <label>Preference Value</label>
        <picklist>
            <controllingField>Preference__c</controllingField>
            <picklistValues>
                <fullName>Payment via EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCRB Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Auction Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Special Archangel Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Appeals/Solicitations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Mail Renewal Only - No Other Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eGuide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Guide Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Class Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Guest Auctioneer Invites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Invitations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RLS Special Invites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Leadership Event Invites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Program Invites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJORDONOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUSIC *</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEWS *</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CULTURAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No MemberCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Sustainer Newsletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Newsletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Leadership Circle Newsletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Program Partner Newsletters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned Giving Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No End of Year Tax Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leadership Circle Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>History Club</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preference__c</fullName>
        <label>Preference</label>
        <picklist>
            <controllingField>Classification_Type__c</controllingField>
            <picklistValues>
                <fullName>Acknowledgement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Gift Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Donor Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MemberCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainer Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Tags</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Handling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age Range (pledge reported)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anonymous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Append</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Solicitation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Classification</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Classification #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/objects/Giving_Summary__c.object
<CustomObject>
    <description>This is a custom area to identify the giving over multiple years by type i.e. Capital Campaign giving for all cumulative years; Major Gift giving for all cumulative years; membership giving, in kind, underwriting and sales.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Household or Organization tied to the Giving Summary.</description>
        <inlineHelpText>Household or Organization tied to the Giving Summary.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Giving Summaries (Account)</relationshipLabel>
        <relationshipName>Account_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Giving Summary</label>
    <nameField>
        <displayFormat>GS#-{0000000000}</displayFormat>
        <label>Giving Summary #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giving Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Oppty_Related_Contact__c</fullName>
        <description>The contact associated to the opportunity/ask</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposal/Pledge</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

kqed/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Club__c</fullName>
        <label>Club</label>
        <picklist>
            <picklistValues>
                <fullName>Arts &amp; Drama Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celtic &amp; Folk Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classical Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>History Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; Travel Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jazz Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kids &amp; Family Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookworm&apos;s Book Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVD Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cookbook Club</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

KQED -/src/objects/Product2.object
    <fields>
        <fullName>Account__c</fullName>
        <description>Drive Premiums</description>
        <inlineHelpText>Use this to connect a Drive Premium to the giving Account.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Premiums/Benefits</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>

kqed/src/classes/Test_trgOppLineAfterInsert.cls
@isTest 
private class Test_trgOppLineAfterInsert {
    static testMethod void myTest() {
        Account a = new Account(Name = 'Test');
        insert a;
        
        Contact cnt = new Contact();
        cnt.firstName = 'Test';
        cnt.lastName = 'test';
        cnt.AccountID = a.Id;
        insert cnt;
        
        
        Campaign c = new Campaign(Name = 'Test');
        Insert c;
        
        Giving_Summary__c g = new Giving_Summary__c();
        g.Account__c = a.Id;
        insert g;
        
        Opportunity opp = New Opportunity();
        opp.AccountID = a.Id;
        opp.Name = 'Test';
        opp.CloseDate = system.Today().AddDays(15);
        opp.StageName = 'Pledged';
        opp.CampaignID = c.Id;
        opp.Oppty_Related_Contact__c = cnt.id;
        insert opp;

        RecordType r = [Select ID from RecordType where DeveloperName='benefit_preferences' limit 1];

        Classification__c objC = new Classification__c();
        objC.RecordTypeID = r.ID;
        objC.Account__c = a.ID;
        objC.Contact__c = opp.Oppty_Related_Contact__c;
        objC.Preference__c = 'Club Type';
        objC.Preference_Value__c = 'History Club';
        insert objC;

        Classification__c objC1 = new Classification__c();
        objC1.RecordTypeID = r.ID;
        objC1.Account__c = a.ID;
        objC1.Contact__c = opp.Oppty_Related_Contact__c;
        objC1.Preference__c = 'Club Type';
        objC1.Preference_Value__c = 'History Club';
        insert objC1;        
        
        Product2 objProduct = new Product2();
        objProduct.name = 'TestProduct';
        objProduct.Family = 'Renewable Energy Inverters';
        objProduct.ProductCode = 'TESTPRODUCT';
        objProduct.Description = 'TestProduct';
        objProduct.Club__c = 'Arts & Drama Club';
        Insert objProduct;

        Product2 objProduct1 = new Product2();
        objProduct1.name = 'TestProduct';
        objProduct1.Family = 'Renewable Energy Inverters';
        objProduct1.ProductCode = 'TESTPRODUCT';
        objProduct1.Description = 'TestProduct';
        objProduct1.Club__c = 'History Club';
        Insert objProduct1;        

        Pricebook2 objPB2 = [Select ID from Pricebook2 where Name = 'Standard Price Book' limit 1];

        PriceBookEntry objPB = new PriceBookEntry();
        objPB.UnitPrice = 15;
        objPB.Pricebook2Id = objPB2.Id;
        objPB.Product2Id = objProduct.Id;
        //objPB.UseStandardPrice = true;
        objPB.IsActive = true;
        insert objPB;
        
        PriceBookEntry objPB1 = new PriceBookEntry();
        objPB1.UnitPrice = 15;
        objPB1.Pricebook2Id = objPB2.Id;
        objPB1.Product2Id = objProduct1.Id;
        //objPB.UseStandardPrice = true;
        objPB1.IsActive = true;
        insert objPB1;        
        
        OpportunityLineItem objOppLine = new OpportunityLineItem();
        objOppLine.OpportunityId = opp.Id;
        objOppLine.Quantity = 10;
        objOppLine.UnitPrice = 15;
        objOppLine.PricebookEntryId = objPB.Id;
        Insert objOppLine;   
             
        OpportunityLineItem objOppLine1 = new OpportunityLineItem();
        objOppLine1.OpportunityId = opp.Id;
        objOppLine1.Quantity = 10;
        objOppLine1.UnitPrice = 15;
        objOppLine1.PricebookEntryId = objPB1.Id;
        Insert objOppLine1; 

    }
}