kqed_dev4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cultivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

KQED -/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Unshipped_Quantity__c</fullName>
        <formula>IF( ISPICKVAL( PricebookEntry.Product2.Inventory_Type__c, &quot;Standard Inventory&quot;), 
  Quantity -  Shipped_Quantity__c,
  0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unshipped Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

kqed/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Units_Ordered_calc__c</fullName>
        <label>Units Ordered (calc)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Pending_Shipment_calc__c</fullName>
        <label>Units Pending Shipment (calc)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Received_calc__c</fullName>
        <label>Units Received (calc)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Shipped_calc__c</fullName>
        <label>Units Shipped (calc)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Sold_calc__c</fullName>
        <label>Units Sold (calc)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

KQED -/src/objects/Purchase_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Premium/Benefit</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Products</relationshipLabel>
        <relationshipName>Purchase_Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Received_Quantity__c</fullName>
        <label>Received Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Order Product</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Purchase Order Premium/Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Ship-{0000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Shipment_Line__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Premium/Benefit</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Shipment Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed_dev4/src/classes/BatchInventoryStatistics.cls
/**********************************************************
 * Description			: Batch process to calculate inventory statistics
 * @date						: May 11, 2011
 **********************************************************/

global class BatchInventoryStatistics implements Database.Batchable<Id> {
	private final list<Id> productIds;
	private final String mode;			 
	
	global BatchInventoryStatistics(set<Id> pIds, String m) {
		this.productIds = Util.convertSetToList(pids);
		this.mode = m;
		system.debug('\n ### mode ' + mode + ' productIds.size ' + this.productIds.size() + ' ' + this.productIds);
	}

	global Iterable<Id> start(Database.BatchableContext info) {
		return productIds;
	}

	global void execute(Database.BatchableContext BC, list<Id> pids) {
		calculateInventoryStatistics(pids, this.mode);
	}

	public static void calculateInventoryStatistics(list<Id> productIds, String mode) {
		system.debug('\n ### productIds.size ' + productIds.size() + ' => ' + productIds);
		if (!productIds.isEmpty()) {
				
			list<Product2> products_to_update = new list<Product2>();
				
			if (mode == 'ProductUnitsReceived') {
				Map<Id, AggregateResult> aggResults = new Map<Id, AggregateResult>();
				for (AggregateResult res : [Select Product__c, sum(Received_Quantity__c) receivedQty, sum(Quantity__c) totalQty from Purchase_Order_Product__c where Product__c != null AND Product__c in : productIds group by Product__c]) {
					aggResults.put( (Id) res.get('Product__c'), res);
				}
				
				for (Id pId : productIds) {
					Product2 p = new Product2(
						Id = pId,
						Units_Ordered_calc__c = 0,
						Units_Received_calc__c = 0
					);
					if (aggresults.containsKey(pId)) {
						Double totalQty = (Double) aggResults.get(pId).get('totalQty');
						Double receivedQty = (Double) aggResults.get(pId).get('receivedQty');
						if (totalQty != null) p.Units_Ordered_calc__c = totalQty.intValue();
						if (receivedQty != null) p.Units_Received_calc__c = receivedQty.intValue();
					}
					products_to_update.add(p);
				}
			}
					
			if (mode == 'ProductUnitsSold') {
				Map<Id, AggregateResult> aggResults = new Map<Id, AggregateResult>();
				for (AggregateResult res : [Select PricebookEntry.Product2Id, sum(Unshipped_Quantity__c) aggTotal from OpportunityLineItem where PricebookEntry.Product2Id in : productIds and Opportunity.isWon = true group by PricebookEntry.Product2Id]) {
					aggResults.put( (Id) res.get('Product2Id'), res);
				}

				for (Id pId : productIds) {
					Product2 p = new Product2(
						Id = pId,
						Units_Sold_calc__c = 0
					);
					if (aggresults.containsKey(pId)) {
						Double aggTotal = (Double) aggResults.get(pId).get('aggTotal');
						if (aggTotal != null) p.Units_Sold_calc__c = aggTotal.intValue();
					}
					products_to_update.add(p);
				}
			}

			if (mode == 'ProductUnitsPending' || mode == 'ProductUnitsShipped') {
				Map<Id, AggregateResult> aggResults = new Map<Id, AggregateResult>();
				for (AggregateResult res : [Select Product__c, sum(Quantity__c) aggTotal from Shipment_Line__c where Product__c in : productIds and Shipment__r.Status__c = : (mode == 'ProductUnitsPending' ? 'Pending' : 'Shipped') group by Product__c]) {
					aggResults.put( (Id) res.get('Product__c'), res);
				}

				for (Id pId : productIds) {
					Product2 p = new Product2(Id = pId);
					if (mode == 'ProductUnitsPending') p.Units_Pending_Shipment_calc__c = 0;
					if (mode == 'ProductUnitsShipped') p.Units_Shipped_calc__c = 0;

					if (aggresults.containsKey(pId)) {
						Double aggTotal = (Double) aggResults.get(pId).get('aggTotal');
						if (mode == 'ProductUnitsPending' && aggTotal != null) p.Units_Pending_Shipment_calc__c = aggTotal.intValue();
						if (mode == 'ProductUnitsShipped' && aggTotal != null) p.Units_Shipped_calc__c = aggTotal.intValue();
					}
					products_to_update.add(p);
				}
			}
				
			if (!products_to_update.isEmpty()) {
				Database.update(products_to_update, false);
			}
		}
	}
		
	// TO DO - move the function to Util class, if we are not planning to schedule a batch job.	 
	global static map<Id, decimal> getAggResultsMap(String fieldName, String fieldNameAgg, AggregateResult[] aggResults) {
		Id cid;
		decimal aggTotal;
		map<Id, decimal> aggResultsMap = new map<Id, decimal>();
							
		if (aggResults != null) {
			for (AggregateResult ar : aggResults) {
				System.debug('\n ### ar ' + fieldName + ' ' + ar);
				
				cid = (Id)ar.get(fieldName);
				aggTotal = (decimal)ar.get(fieldNameAgg);
				System.debug('\n ### cid ' + cid + ' Agg. Summary ' + aggTotal);
				
				aggResultsMap.put(cid, aggTotal);
			}
		}
		return aggResultsMap;
	}	 
				
	global void finish(Database.BatchableContext BC) {
		// Get the ID of the AsyncApexJob representing this batch job 
		// from Database.BatchableContext.
		// Query the AsyncApexJob object to retrieve the current job's information. 
		AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
		
		if (a.NumberOfErrors > 0 || Test.isRunningTest()) {
			//Send an email to the Apex job's submitter notifying of job completion.
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {'ryan.huff@roundcorner.com'};
			mail.setToAddresses(toAddresses);
			mail.setSubject('Batch Inventory Statistics ' + a.Status);
			mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +
															' batches with '+ a.NumberOfErrors + ' failures.');
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
	}
		
	public static testMethod void test() {
		//list<Id> productIds = [select id from Product2 limit 5];
		set<Id> productIds = new set<Id>();
		for (Product2 p : [select id from Product2 where IsActive = true and IsDeleted = false limit 5]) {
				productIds.add(p.Id);
		}
		BatchInventoryStatistics scriptBatch = new BatchInventoryStatistics(productIds, 'ProductUnitsReceived');
		ID batchProcessid = Database.executeBatch(scriptBatch);
	}
}