kqed_dev4/src/objects/WGBH_PB5_UPLOAD__c.object
<CustomObject>
    <description>This object stores PB5 data from various 3rd party gift processing vendors (e.g. Convio, Kimbia, PBSd, Auction, CARS, ACD Pledge, ACD Telemarketing, Lockbox, Aria)</description>
    <fields>
        <fullName>PB5_SFDC_ID__c</fullName>
        <description>Salesforce ID of household, contact or organization maps to: UL_ACCOUNTS.ACCOUNT_ID</description>
        <label>PB5_SFDC_ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PB5_UPLOAD</label>
    <nameField>
        <displayFormat>PB5-{0000}</displayFormat>
        <label>PB5_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB5_UPLOADS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

kqed/src/classes/BatchUploadRecordMatchingProcessExec1.cls
global class BatchUploadRecordMatchingProcessExec1 implements Database.Batchable<sObject> {
    global final String Query;
    global boolean IsTest;    
    global BatchUploadRecordMatchingProcessExec1 (String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchPB5HouseHoldProcess (scope);
    }
    
    void DoBatchPB5HouseHoldProcess (List<sObject> scope) {

        Set<Decimal> SFDCID = New Set<Decimal>();
        Set<String> SFDCID_String = New Set<String>();
        
        
        for(sObject s : scope) {
            WGBH_PB5_UPLOAD__c PB5 = (WGBH_PB5_UPLOAD__c)s;
            String householdId = UploadRecordMatchingHouseHold.ProcessHousehold(PB5);
            UploadRecordMatchingContact.ProcessContact(PB5,householdId);
            //UploadRecordMatchingClassification.ProcessClassification(PB5);
            SFDCID.add(PB5.PB5_SFDC_ID__c);
            SFDCID_String.add(string.valueOf(PB5.PB5_SFDC_ID__c));
        }
    }
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

    static testMethod void TestBatchExecPB5HouseHoldProcess () {
        Test.startTest();
        /*
        ID batchprocessid;
        BatchUploadRecordMatchingProcessExec1 reassign;
        reassign = new BatchUploadRecordMatchingProcessExec1 ('Select ID from Lead limit 200');
        batchprocessid = Database.executeBatch(reassign);   
        Test.StopTest();
        */
    }    
}