KQED -/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Household_Email__c</fullName>
        <label>Household Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Household_Phone__c</fullName>
        <label>Household Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkPhone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <label>Household</label>
    </recordTypes>
</CustomObject>

KQED -/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Household__c</fullName>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HomeEmail__c</fullName>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PreferredPhone__c</fullName>
        <label>Preferred Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <label>Preferred Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Email__c</fullName>
        <label>Preferred Email</label>
        <picklist>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TaContactId__c</fullName>
        <description>TA Contact Id</description>
        <externalId>true</externalId>
        <label>TA Contact Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkEmail__c</fullName>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WorkPhone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>bulk_load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ETL migration process</description>
        <label>bulk_load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

KQED -/src/classes/BatchHouseholdContactPrefDataLink.cls
global class BatchHouseholdContactPrefDataLink implements Database.Batchable<sObject>{
    global String query;
    global Boolean chainFlag = false;

    global BatchHouseholdContactPrefDataLink(){
        this.query = 'SELECT Preferred_Address__c, Household_Phone__c, Household_Email__c, ' +  
                         '(SELECT TaContactId__c, WorkPhone__c, WorkEmail__c, Preferred_Email__c, Preferred_Address__c, PreferredPhone__c, MobilePhone, HomePhone, HomeEmail__c, bulk_load__c ' +   
                         'From Contacts__r) ' +  
                         //'WHERE ((WorkPhone__c = null AND MobilePhone = null AND HomePhone = null) OR (WorkEmail__c = null AND HomeEmail__c = null) OR Preferred_Address__c = null)) ' +  
                     'FROM Account ';  
    }
    
    global BatchHouseholdContactPrefDataLink(Boolean chainFlag){
        this();
        this.chainFlag = chainFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Contact> contacts2bUpdated = new List<Contact>();
        for(Sobject s : scope){
            Account h = (Account) s;
            List<Contact> cs = h.Contacts__r;
            for(Contact c : cs) {
                //Make sure Contact.Preferred_Address__c filtered lookup is optional and not required.
                if(c.Preferred_Address__c == null && h.Preferred_Address__c != null) {
                   c.Preferred_Address__c = h.Preferred_Address__c;
                   c.bulk_load__c = true;
                }
                
                if(c.WorkPhone__c == null && c.MobilePhone == null && c.HomePhone == null && h.Household_Phone__c != null) {
                    c.HomePhone = h.Household_Phone__c;
                    c.PreferredPhone__c = 'Household';
                    c.bulk_load__c = true;
                }
                
                //Update email for first and only Contact
                if(cs.size() == 1 && c.WorkEmail__c == null && c.HomeEmail__c == null && h.Household_Email__c != null) {
                    c.HomeEmail__c = h.Household_Email__c;
                    c.Preferred_Email__c = 'Household';
                    c.bulk_load__c = true;
                }
            }
            contacts2bUpdated.addAll(cs);
        }
        update contacts2bUpdated;
    }

    public static testMethod void testBatch() {
        Test.StartTest();
        BatchHouseholdContactPrefDataLink batch = new BatchHouseholdContactPrefDataLink();
        batch.query += ' LIMIT 2 ';
        ID batchprocessid = Database.executeBatch(batch);
        Test.StopTest();

    }

    global void finish(Database.BatchableContext BC){
        BatchDispatcherInboundEmail bdie = new BatchDispatcherInboundEmail();
        bdie.dispatchBatch('BatchHouseholdContactPrefDataLink', chainFlag);
    }
}