KQED -/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <description>This is the URL for the logo. This field is automatically populated by the image upload.</description>
        <inlineHelpText>This is the URL for the logo. This field is automatically populated by the image upload.</inlineHelpText>
        <label>Logo Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Member_Discount_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Participates in a member discount offer</description>
        <inlineHelpText>Check this box if this organization participates in a member discount offer</inlineHelpText>
        <label>Member Discount Offer</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account additional locations</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Telephone Number</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>Zip Code</description>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State or Province</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street Address</description>
        <label>Street</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KQED -/src/objects/Member_Benefit__c.object
<CustomObject>
    <description>Member Discount Partners offer discounts to the WGBH members, you can view which Organizations offer discounts by searching on an Organization name.</description>
    <fields>
        <fullName>BenefitImage__c</fullName>
        <label>Benefit Image</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Business_Member_Partner__c</fullName>
        <description>Business Member Partner associated with offer benefit</description>
        <inlineHelpText>Business Member Partner associated with offer benefit</inlineHelpText>
        <label>Business Member Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category&apos;s associated with member benefit</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Up-to-the-minute Additions</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Education &amp; Family Fun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food &amp; Drink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live Performances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Museums</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Recreation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Blank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abbot Kinney Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure, Recreation &amp; Attractions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts &amp; Crafts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstores / Magazines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s Corner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classes &amp; Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concerts, Clubs &amp; Performing Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fashion, Clothing &amp; Beauty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Foods &amp; Gourmet Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Furnishings &amp; Decor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts, Galleries &amp; Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Street Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana Avenue Merchants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Music Stores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Care &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Coast Plaza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spas &amp; Salons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theatre &amp; Film</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <description>This is the URL for the logo. This field is automatically populated by the image upload.</description>
        <inlineHelpText>This is the URL for the logo. This field is automatically populated by the image upload.</inlineHelpText>
        <label>Logo Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Member Discount Organization</label>
    <nameField>
        <label>Member Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Discount Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed_dev4/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

KQED -/src/classes/BatchMemberBenefitImageLoad.cls
public class BatchMemberBenefitImageLoad {
 
    public Boolean isTest = false;
    
    public BatchMemberBenefitImageLoad(){
        
    }

    public void execute(){
        String queryStr = 'select id, BenefitImage__c, Logo_Url__c from Member_Benefit__c where logo_url__c = null';
        if(this.isTest) {
            queryStr += ' and name like \'%Blue Ribbon BBQ%\' Limit 1';
        }
        List<Member_Benefit__c> mbs = Database.query(queryStr);
        
        List<Document> images = new List<Document>();
        Folder folder = [Select Id FROM Folder WHERE developerName = 'Member_Benefit_Images'];
        
        for(Member_Benefit__c mb : mbs){
            if(mb.BenefitImage__c != null) {
                String iname = mb.BenefitImage__c.substring(mb.BenefitImage__c.lastIndexOf('s/')+2, mb.BenefitImage__c.lastIndexOf('.')+4).replace('&#39;', '\'').replace('&amp;', '&');
                System.debug(Logginglevel.WARN, iname);
                PageReference pageRef = new PageReference('/resource/mdo_images/'+iname);
                System.debug(Logginglevel.WARN, pageRef.getUrl());
                Blob img = pageRef.getContent();
                
                if(img != null) {
                    Document newImage = new Document();
                    newImage.Body = img;
                    newImage.Name = ((String)mb.Id).substring(0, 15) + '-Logo_Url__c';
                    newImage.IsPublic = true;
                    newImage.FolderId = folder.Id;
                    
                    images.add(newImage);
                }
            }
        }
        insert images;
        
        Map<String, Id> imageMap = new Map<String, Id>();
        images = [SELECT id, Name from Document];
        for(Document d : images) {
            imageMap.put(d.Name, d.id);
        }
        
        for(Member_Benefit__c mb : mbs){
            if(mb.BenefitImage__c != null) {
                String url = '/servlet/servlet.ImageServer?id='+imageMap.get(((String) mb.Id).substring(0, 15) + '-Logo_Url__c') + '&oid=' + UserInfo.getOrganizationId();
                mb.Logo_Url__c = url;
            }
        }
        update mbs;
    }

    @isTest
    public static void testImageUpload() {
        Account bmp = new Account(
           Name = 'Blue Ribbon BBQ', 
           Member_Discount_Offer__c = true, 
           Logo__c = 's/BlueRibbonBBQ.jpg'
        );
        insert bmp;
        
        Location__c loc = new Location__c(
           Name = 'Boylston St', 
           Account__c = bmp.id, 
           Street__c = '885 Boylston Street', 
           City__c = 'Boston', 
           State__c = 'MA', 
           PostalCode__c = '02116', 
           Phone__c = '(617) 262-5551', 
           Latitude__c = 42.348442,
           Longitude__c = -71.083608
        );
        insert loc;
        
        Member_Benefit__c mb = new Member_Benefit__c(
           Name = 'Blue Ribbon BBQ', 
           Offer__c = 'Get 15 cent wings, Sunday to Thursday 3pm to 2am with a purchase of an alcholic beverage.',  
           Category__c = 'Food & Drink', 
           Business_Member_Partner__c =  bmp.id
        );
        insert mb;
        
        Test.StartTest();
        BatchMemberBenefitImageLoad bmbil = new BatchMemberBenefitImageLoad();
        bmbil.isTest = true;
        bmbil.execute();
        Test.StopTest();
        
        Member_Benefit__c mbUpdated = [select id, Logo_Url__c from Member_Benefit__c where name like '%Blue Ribbon BBQ%' Limit 1];
        System.debug('mbUpdated: '+mbUpdated.Logo_Url__c);
    }
}