KQED -/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AboutUs__c</fullName>
        <description>AboutUs field added for Business Member Partners</description>
        <label>AboutUs</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Logo_Url__c</fullName>
        <description>This is the URL for the logo. This field is automatically populated by the image upload.</description>
        <inlineHelpText>This is the URL for the logo. This field is automatically populated by the image upload.</inlineHelpText>
        <label>Logo Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed/src/objects/Location__c.object
<CustomObject>
    <description>Additional Locations for Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account additional locations</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Telephone Number</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>Zip Code</description>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State or Province</description>
        <label>State</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street Address</description>
        <label>Street</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed/src/objects/Member_benefit_Location__c.object
<CustomObject>
    <description>Junction Table for relating Member Benefits to Location</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Member_Benefit_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Partner Location</label>
    <nameField>
        <label>Member Discount Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Partner Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

kqed_dev4/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

KQED -/src/classes/MemberBenefitWs.cls
global class MemberBenefitWs {
	
	public static Boolean isTest = false;
	
	global class MemberBenefitWs_Result {
		webservice String status {get; set;} // 'Success','Error','Exception' 
		webservice String description {get; set;} // 'Success', message, execption message
		webservice String xml {get; set;} //result
		
	}
	
	webservice static MemberBenefitWs_Result getMemberBenfits() {
		try {
			MemberBenefitWs_Result result = new MemberBenefitWs_Result();
            result.status='Success';
            result.Description='Success';
            
            MemberBenefitController mbc = new MemberBenefitController();
            if(MemberBenefitWs.isTest) {
            	mbc.isTest = true;
            }
            mbc.retrieveMemberBenefits();
            
            Map<Id, List<MemberBenefitWrapper>> mbwAccountMap = new Map<Id, List<MemberBenefitWrapper>>();
            for(MemberBenefitWrapper mbw : mbc.memberBenefitWrappers) {
                Id partnerId = mbw.memberBenefit.Business_Member_Partner__c;
                List<MemberBenefitWrapper> mbwList = null;
                if(mbwAccountMap.get(partnerId) == null) {
                    mbwList = new List<MemberBenefitWrapper>();                 
                }
                else {
                    mbwList = mbwAccountMap.get(partnerId);
                }
                mbwList.add(mbw);
                mbwAccountMap.put(partnerId, mbwList);
            }
            
            for(Id pId : mbwAccountMap.keySet()) {
                //System.debug(Logginglevel.WARN, 'id: '+pId+', size: '+mbwAccountMap.get(pId).size());
            }
            
            /*Map<Id, Account> accountLocationsMap = new Map<Id, Account>();
            accountLocationsMap.putAll(
                [Select Id, 
                    (Select Id, Street__c, City__c, State__c, PostalCode__c, Phone__c, Latitude__c, Longitude__c From Locations__r)
                 From Account Where Id IN :mbwAccountMap.keySet()]
            );
            System.debug(Logginglevel.WARN, 'AccMbMap len: '+mbwAccountMap.size()+', AccLocMap len: '+accountLocationsMap.size());  */
            
            String xmlResult = '<underwriters>';
            for(Id partnerId : mbwAccountMap.keySet()) {
                List<MemberBenefitWrapper> mbwList = mbwAccountMap.get(partnerId);
                MemberBenefitWrapper mbwTemp = mbwList.get(0);
                xmlResult += '<underwriter>';
                    xmlResult += createElement('id', partnerId);//' +  + '
                    xmlResult += createElement('name', mbwTemp.memberBenefit.Business_Member_Partner__r.Name);
                    xmlResult += createElement('description', mbwTemp.memberBenefit.Business_Member_Partner__r.AboutUs__c);
                    xmlResult += createElement('url', mbwTemp.memberBenefit.Business_Member_Partner__r.Website);
                    if(mbwTemp.memberBenefit.Business_Member_Partner__r.Logo_Url__c != null && mbwTemp.memberBenefit.Business_Member_Partner__r.Logo_Url__c.length() > 0) {
                    	xmlResult += createElement('logo_url', 'http://wgbh.force.com' + mbwTemp.memberBenefit.Business_Member_Partner__r.Logo_Url__c);
                    }
                    
                    Map<Id, Member_benefit_Location__c> mbLocations = new Map<Id, Member_benefit_Location__c>();
                    for(MemberBenefitWrapper mbw : mbwList) {
                    	for(Member_benefit_Location__c mblTemp : mbw.memberBenefitLocations) {
                    		mbLocations.put(mblTemp.Id, mblTemp);
                    	}
                    }
                    xmlResult += '<locations>';
                    for(Id locationId : mbLocations.keySet()) {
                    	Location__c location = mbLocations.get(locationId).Location__r;
                    	xmlResult += '<location>';
                    	    xmlResult += createElement('id', location.Id);
                    	    xmlResult += createElement('street', location.Street__c);
                    	    xmlResult += createElement('city', location.City__c);
                    	    xmlResult += createElement('state', location.State__c);
                    	    xmlResult += createElement('postal_code', location.PostalCode__c);
                    	    xmlResult += createElement('phone', location.Phone__c);
                    	    xmlResult += createElement('latitude', location.Latitude__c.toPlainString());
                    	    xmlResult += createElement('longitude', location.Longitude__c.toPlainString());
                    	xmlResult += '</location>';
                    }
                    xmlResult += '</locations>';
                    
                    xmlResult += '<benefits>';
                    for(MemberBenefitWrapper mbw : mbwList) {
                    	xmlResult += '<benefit>';
                    	    xmlResult += createElement('id', mbw.memberBenefit.Id);
                    	    xmlResult += createElement('name', mbw.memberBenefit.Name);
                    	    //xmlResult += createElement('start_date', mbw.memberBenefit.Start_Date__c.format());
                    	    //xmlResult += createElement('end_date', mbw.memberBenefit.End_Date__c.format());
                    	    xmlResult += createElement('description', mbw.memberBenefit.Offer__c);
                    	    xmlResult += createElement('category', mbw.memberBenefit.Category__c);
                    	    xmlResult += createElement('featured', String.valueOf(mbw.memberBenefit.Featured__c));
                    	    xmlResult += createElement('top_two_featured', String.valueOf(mbw.memberBenefit.Top_Two_Featured__c));
                    	    
                    	    xmlResult += '<benefit_locations>';
                    	    for(Member_benefit_Location__c mbl : mbw.memberBenefitLocations) {
                                xmlResult += createElement('id', mbl.Location__r.Id);
                    	    }
                    	    xmlResult += '</benefit_locations>';
                    	xmlResult += '</benefit>';
                    }
                    xmlResult += '</benefits>';
                   
                xmlResult += '</underwriter>';
            }
            xmlResult += '</underwriters>';
            
            result.xml = xmlResult; 
            
            //System.debug(Logginglevel.WARN, '***********************'+result.xml);	
			return result;
		}
		catch  (Exception ex) {
            MemberBenefitWs_Result result = new MemberBenefitWs_Result();
            result.status='Exception';
            result.Description=ex.getMessage();
            result.xml=null;
            return result;        			
		}		
	} 
	
	static String createElement(String tag, String value) {
		return (value != null && value.length() > 0) ? ('<' + tag + '>' + value + '</' + tag + '>') : ('<' + tag + '/>');
	}
    
    
}