KQED -/src/objects/CC_Alias__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Merchant_Account__c</fullName>
        <label>Merchant Account</label>
        <referenceTo>Merchant_Accounts__c</referenceTo>
        <relationshipLabel>CC &amp; EFT Aliases</relationshipLabel>
        <relationshipName>CC_EFT_Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merchant_ID__c</fullName>
        <label>Merchant ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CC &amp; EFT Alias</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>CC &amp; EFT Alias #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC &amp; EFT Aliases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

KQED -/src/objects/Merchant_Accounts__c.object
<CustomObject>
    <description>merchant key and id info for Sage charge processing</description>
    <label>Merchant Account</label>
    <nameField>
        <label>Merchant Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchant Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KQED -/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_EFT_Alias__c</fullName>
        <label>CC &amp; EFT Alias</label>
        <referenceTo>CC_Alias__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_GIVING_NUMBER__c</fullName>
        <displayFormat>G{000000000}</displayFormat>
        <label>SFDC GIVING NUMBER</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pledge Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>payment_amount__c</fullName>
        <description>Payment Amount</description>
        <inlineHelpText>Payment Amount</inlineHelpText>
        <label>Payment Amount $</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pledge_number__c</fullName>
        <description>Pledge Number</description>
        <inlineHelpText>Pledge Number</inlineHelpText>
        <label>TA Pledge Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

kqed_dev4/src/objects/TRANSACTION_BATCH__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <description>the GUID from the pledge to be processed</description>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Id__c</fullName>
        <label>Merchant_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Key__c</fullName>
        <label>Merchant_Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>The id of the pledge</description>
        <label>Opportunity_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The amount to be processed from the pledge</description>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pledge_Number__c</fullName>
        <description>The pledge number from the pledge</description>
        <label>Pledge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_date__c</fullName>
        <description>The date the batch is being processed</description>
        <label>Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status has the payment been sent and a response received from Sage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROCESS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAYMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TRANSACTION_BATCH</label>
    <nameField>
        <label>TRANSACTION_BATCH Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TRANSACTION_BATCHS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

KQED -/src/classes/BatchExecTransaction_Batch.cls
global class BatchExecTransaction_Batch implements Database.Batchable<sObject> {
    global final String Query;
 
    global BatchExecTransaction_Batch(String q){Query=q;}

    global Database.QueryLocator start(Database.BatchableContext BC)   {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope)   {
        DoBatchTransactionbatchInsert(scope);
    }
    
    void DoBatchTransactionbatchInsert(List<sObject> scope) {
        List<Transaction_Batch__c> lstbatch = new List<Transaction_Batch__c>();
        
        Transaction_Batch__c TB;
        
        for(sObject s : scope) {
            Opportunity ObjPledge = (Opportunity)s;
            TB = new Transaction_Batch__c();
            System.debug('pledgeid: '+ ObjPledge.Id );

            TB.Process_date__c = ObjPledge.Payment_Date__c;
            TB.GUID__c = ObjPledge.CC_EFT_Alias__r.GUID__c;
            TB.Payment_Amount__c = ObjPledge.Payment_Amount__c;
            TB.Pledge_Number__c = ObjPledge.SFDC_GIVING_NUMBER__c;
            TB.Opportunity_Id__c = ObjPledge.Id;
            TB.Merchant_ID__c = ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c;
            TB.Merchant_Key__c =  ObjPledge.CC_EFT_Alias__r.Merchant_Account__r.Merchant_Key__c;
            TB.Transaction_Type__c = 'PAYMENT';
            TB.Status__c = 'PROCESS';
            lstbatch.add(TB);
        }
        
        if(lstbatch != null && lstbatch.size()>0) 
        {
            Insert lstbatch;
        }

    }
    
    global void finish(Database.BatchableContext BC) {
        //System.debug('####Update Completed...');
    }    

    static testMethod void TestBatchExecTransaction_Batch() {
       Test.startTest();
        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'Pledge';
        o.CloseDate = system.today().addDays(10);
        o.Payment_Date__c =  System.today();
        o.Payment_Amount__c= 15;
        insert o;
        
        Opportunity o1 = new Opportunity();
        o1.Name = 'test';
        o1.StageName = 'Pledge';
        o1.CloseDate = system.today().addDays(10);
        o1.Payment_Date__c =  System.today();
        o1.Payment_Amount__c= 16;                
        insert o1;
        
       
        BatchExecTransaction_Batch reassign = new BatchExecTransaction_Batch ('Select ID,Payment_Date__c,Payment_Amount__c,SFDC_GIVING_NUMBER__c,CC_EFT_Alias__r.Merchant_Account__r.Merchant_ID__c from Opportunity Where Payment_Date__c = Today Limit 2');
        ID batchprocessid = Database.executeBatch(reassign,2);
 
        Test.StopTest();     
        
    }
}