KQED -/src/objects/Prospect_Research_Reports__c.object
<CustomObject>
    <description>Prospect Research Reports are utilized for profiling of members, prospective members and constituents by the Prospect Research Team.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Born_Day__c</fullName>
        <formula>Contact__r.Birth_Day__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Born Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Born_Month__c</fullName>
        <formula>Contact__r.Birth_Month__c</formula>
        <label>Born Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Born_Year__c</fullName>
        <formula>Contact__r.Birth_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Born Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account__r.Preferred_Address__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports</relationshipLabel>
        <relationshipName>Prospect_Research_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Spouse_Name__c</fullName>
        <label>Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Prospect Research Reports (Spouse Name)</relationshipLabel>
        <relationshipName>Prospect_Research_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account__r.Preferred_Address__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Prospect Research Report</label>
    <nameField>
        <label>PRR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Research Reports</pluralLabel>
    <recordTypes>
        <fullName>Profile</fullName>
        <active>true</active>
        <description>Detailed PRR for major gift/board prospects (i.e. 1-3 pages)</description>
        <label>Profile</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

kqed_dev4/src/objects/State__c.object
<CustomObject>
    <description>List of states from Lawson</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

KQED -/src/classes/ProspectResearchReport.cls
Public Class ProspectResearchReport{

    Public String ID;
    
    Public List<Prospect_Research_Reports__c> lstEventBios{get;set;}
    Public List<Prospect_Research_Reports__c> lstResearchNote{get;set;}
    Public List<Prospect_Research_Reports__c> lstProfile{get;set;}
    
    Public String SizeEventBios{get;set;}
    Public String SizeResearchNote{get;set;}//Research Note
    Public String SizeProfile{get;set;}//Profile
    
    Public String EventBioId{get;set;}
    Public String ResearchNoteId{get;set;}
    Public String ProfileId{get;set;}
    
    String getRecordTypeId(String RcName){
        return [Select id from recordtype where name =: RcName][0].id;
    }
    
    Private void PageLoad(){
        lstEventBios = new List<Prospect_Research_Reports__c>();
        lstResearchNote = new List<Prospect_Research_Reports__c>();
        lstProfile = new List<Prospect_Research_Reports__c>();
        
        ID=ApexPages.CurrentPage().getParameters().get('id');
                
        EventBioId = getRecordTypeId('Event Bio');
        ResearchNoteId = getRecordTypeId('Research Note');
        ProfileId = getRecordTypeId('Profile');
        
        //Event Bio
        lstEventBios = getPRRs(ID, EventBioId);
        SizeEventBios = 'Event Bios [' + lstEventBios.size() + ']';     
        
        //Research Note        
        lstResearchNote = getPRRs(ID, ResearchNoteId);
        SizeResearchNote = 'Research Note [' + lstResearchNote.size() + ']';             
        
        //Profile       
        lstProfile = getPRRs(ID, ProfileId);
        SizeProfile = 'Profile [' + lstProfile.size() + ']';             
    }
    
    List<Prospect_Research_Reports__c> getPRRs(String strID, String RecordTypeId){
        List<Prospect_Research_Reports__c> lstPRRTemp = new List<Prospect_Research_Reports__c>();
        String strObject = CommonApex.getObjectNameById(strID);
        If(strObject == 'Account__c')
            lstPRRTemp = [SELECT Id, Name, RecordType.Name, Author__r.Name, Contact__r.Name, Account__r.Name, Notes__c, Spouse_Name__r.Name, City__c, State__c, Born_Day__c, Born_Month__c, Born_Year__c FROM Prospect_Research_Reports__c WHERE Account__c =: strID AND RecordType.Id =: RecordTypeId];
        Else If(strObject == 'Contact')            
            lstPRRTemp = [SELECT Id, Name, RecordType.Name, Author__r.Name, Contact__r.Name, Account__r.Name, Notes__c, Spouse_Name__r.Name, City__c, State__c, Born_Day__c, Born_Month__c, Born_Year__c FROM Prospect_Research_Reports__c WHERE Contact__c =: strID AND RecordType.Id =: RecordTypeId];        
        return lstPRRTemp;
    }
    
    Public ProspectResearchReport(){
        PageLoad();
    }
    Public ProspectResearchReport(ApexPages.StandardController controller) {
        PageLoad();
    }

}