KQED -/src/objects/Vendor_Exports__c.object
<CustomObject>
    <description>List of  pulls generated to send to vendors</description>
    <fields>
        <fullName>Last_Run__c</fullName>
        <label>Last Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pull_Name__c</fullName>
        <label>Pull Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Pull_Type__c</fullName>
        <label>Pull Type</label>
        <picklist>
            <picklistValues>
                <fullName>Premium Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledgements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide Pulls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Membercard Pulls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ask Amount Updates</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vendor Exports</label>
    <nameField>
        <label>Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KQED -/src/classes/RunVendorExportController.cls
public with sharing class RunVendorExportController 
{
	public List<Vendor_Exports__c> premiumFulfillment {get; set;}
	public List<Vendor_Exports__c> ackowledgements {get; set;}
	public List<Vendor_Exports__c> reminders {get; set;}
	public List<Vendor_Exports__c> guidePulls {get; set;}
	public List<Vendor_Exports__c> membercardPulls {get; set;}
	public List<Vendor_Exports__c> askAmountUpdates {get; set;}
	
	public RunVendorExportController() 
	{    
		getPremiumFulfillment();
		getAcknowledgements();
		getReminders();
		getGuidePulls();
		getAskAmountUpdates();
	} 
	
	public PageReference runReport()
	{
		return null;
	}
	
	public PageReference getPremiumFulfillment()
    {
        premiumFulfillment = [SELECT Id, Pull_Name__c, Last_Run__c, Pull_Type__c 
        					  FROM Vendor_Exports__c WHERE Pull_Type__c = 'Premium Fulfillment'];
        return null;
    }
    
    public PageReference getAcknowledgements() 
    {
        ackowledgements = [SELECT Id, Pull_Name__c, Last_Run__c, Pull_Type__c 
        					  FROM Vendor_Exports__c WHERE Pull_Type__c = 'Acknowledgements'];
        return null;
    }
    
    public PageReference getReminders() 
    {
        reminders = [SELECT Id, Pull_Name__c, Last_Run__c, Pull_Type__c 
        					  FROM Vendor_Exports__c WHERE Pull_Type__c = 'Reminders'];
        return null;
    }
    
    public PageReference getGuidePulls() 
    {
        guidePulls = [SELECT Id, Pull_Name__c, Last_Run__c, Pull_Type__c 
        					  FROM Vendor_Exports__c WHERE Pull_Type__c = 'GuidePulls'];
        return null;
    }
    
    public PageReference getAskAmountUpdates() 
    {
        askAmountUpdates = [SELECT Id, Pull_Name__c, Last_Run__c, Pull_Type__c 
        					  FROM Vendor_Exports__c WHERE Pull_Type__c = 'Ask Amount Updates'];
        return null;
    }
    

	
}